client/app/src/network/NetworkService.js
Set Ark price at 0 when offline
=> Price when offline

Brewfile, README.md
I'm a lazy OS X user and don't like typing. What do you think about adding a `Brewfile`?
=> Add a Brewfile for OS X users

.gitignore, client/app/index.html, client/app/src/accounts/view/importAccount.html, client/app/src/changer/ChangerService.js, client/app/src/network/NetworkService.js, client/app/src/storage/StorageService.js
Existing code is really nice and clean, so no "critical changes" or bugs have been identified.
Just local fixes and changes I noticed while learning and getting familiar with the code of the Ark-Desktop client...
best 
--chris
=> Some initial suggestions

client/app/index.html, client/app/src/accounts/view/createAccount.html, client/app/src/accounts/view/createDelegate.html, client/app/src/accounts/view/createSecondPassphrase.html, client/app/src/accounts/view/importAccount.html, client/app/src/accounts/view/manageNetwork.html, client/app/src/accounts/view/savePassphrases.html, client/app/src/accounts/view/sendArk.html, client/app/src/accounts/view/showTransaction.html, client/app/src/accounts/view/vote.html
=> Added new terms and adjusted others

client/app/index.html, client/app/src/accounts/view/sendArk.html, client/app/src/directives.js
=> Add a directive for valid amount

client/app/index.html, client/app/src/network/NetworkService.js
=> Save last price in localStorage

client/app/assets/app.css, client/app/src/accounts/AccountController.js
Normal toast messages and errors should have different styles, sometimes I don't even understand that there is an error message.
=> Error message style

client/app/index.html
Changed the cold wallet message to a more friendly one that wont confuse ARK Users.
=> More User Friendly

client/app/index.html, client/app/src/accounts/AccountController.js
First real dive into promise logic. This can probably be done in a more elegant way?
Fixes #76
=> Add refresh account balance button to dashboard

client/app/src/qrscanner/ScannerController.js
=> Fix deprecated method MediaStream.stop() on QR scan

client/app/src/accounts/AccountController.js, client/app/src/accounts/view/sendArk.html
A filter is just to handle empty values.
=> Add total send amount in current currency selected

client/app/index.html, client/app/src/accounts/AccountController.js, client/app/src/network/NetworkService.js
If there is a newer version, show button "New version available!" in the top left corner that opens the releases page.
=> New version button

client/app/index.html
=> Homepage price change color

client/app/src/accounts/AccountController.js, client/app/src/accounts/AccountService.js, client/app/src/accounts/view/addDelegate.html
Instead of writing the delegate name, show a dropdown menu with all registered delegates to choose from.
=> Adding delegate dropdown

client/app/src/accounts/AccountController.js, client/app/src/accounts/AccountService.js
- reward 'delete' account' to 'remove' account
- make confirm dialog text more clear about the expected results 
- change delete icon to clear icon, since it is a better indicator of actual action
#109
=> reword delete account to remove account

main.js, package.json
electron-about-window integration.
=> electron-about-window

client/app/index.html, client/app/src/Addressbook/AddressbookController.js, client/app/src/Addressbook/addAddressbookContact.html, client/app/src/Addressbook/editAddressbookContact.html, client/app/src/accounts/AccountController.js, client/app/src/accounts/view/sendArk.html
implemented an Address-Book with options to add, delete and modify contacts. to open it, you can click the book symbol in the top menu bar. I've also added an Autocompletion example in the sendArk Function. Just type an username of your added contacts and the text field will fill in the deposited address.
=> Address-Book

client/app/index.html, client/app/src/accounts/view/manageBackground.html, client/app/src/accounts/view/manageNetwork.html, client/app/src/accounts/view/showTransaction.html, client/app/src/accounts/view/timestampDocument.html
Update md-colors directive to use default theme.
=> Fix colors from material angular

client/app/index.html
this is the Tooltip Part from the topbar improvements. Just added some small "On Mouse Hover" Tooltips to the Topbar, so the User can see what is behind the icon.
=> Tooltips in Navigation Bar

client/app/assets/app.css, client/app/index.html, client/app/src/accounts/AccountController.js
this is the Language-Selector Part from the topbar improvements, which is now implemented as a more usable dropdown.
=> Language selector

client/app/src/accounts/AccountController.js, client/app/src/accounts/view/addDelegate.html, client/app/src/accounts/view/addWatchOnlyAddress.html, client/app/src/accounts/view/createAccount.html, client/app/src/accounts/view/createDelegate.html, client/app/src/accounts/view/createSecondPassphrase.html, client/app/src/accounts/view/importAccount.html, client/app/src/accounts/view/manageBackground.html, client/app/src/accounts/view/manageNetwork.html, client/app/src/accounts/view/savePassphrases.html, client/app/src/accounts/view/sendArk.html, client/app/src/accounts/view/showTransaction.html, client/app/src/accounts/view/vote.html
Just a small Usability improvement.
As every Dialog in any case has a "Cancel"-Button, it makes sense to also provide a "X" in the top right corner to close modals for user friendly interaction.
I added it to all actual modal dialogs.
Furthermore I changed the way how "add Watch-Only Address" was handled actually. Every Modal in the Code was handled by an own html template except this one, so i changed it to the regular way here and created a template.
With this change I also added a Close Button here to keep it consistent and solid.
=> Modal close buttons

client/app/index.html, client/app/src/accounts/AccountController.js, client/app/src/storage/StorageService.js
Simple option to clear all data from localStorage.
=> Option to clear localStorage

client/app/src/accounts/AccountController.js, client/app/src/network/NetworkService.js
Refresh the price by clicking the update button on the home screen.
=> Refresh Price

client/app/index.html, client/app/src/accounts/AccountController.js
Add a button to the topbar to change network.
Issue: #160
=> Change Network

client/app/src/accounts/AccountController.js, client/app/src/accounts/view/manageNetwork.html
Remove button create and rename save to add
=> Add instead of save in manager network

client/app/assets/app.css, client/app/index.html
This resolves the issue #185 with the quit button being not in left alignment with the other buttons in the on/off "Application" panel.
=> Fix for quit button alignment #185

client/app/index.html
#186 is done.
the buttons are now in the header which is now sticky to the top. just the list will scroll.
=> improved scrolling account dashboard

client/app/assets/app.css, client/app/index.html, client/app/src/accounts/AccountController.js, package.json
I changed the hidden currency switcher to be a select/option for an easier user experience. Now the user can very quickly change to the currency of their choice without having to potentially cycle through the entire hidden list.
=> Select option for currency

client/app/src/accounts/AccountController.js, client/app/src/accounts/AccountService.js
as the title says. resolving #206
=> implemented input check against hex in message verify

client/app/index.html, client/app/src/accounts/AccountController.js, client/app/src/changer/ChangerService.js, client/app/src/network/NetworkService.js, client/app/src/time/TimeService.js
#57 / #217 - Here's my implementation for this that I did last week. It's different than the other one in that the other one doesn't actually account for server latency from the time the timestamp is retrieved from the server.
=> 57 timeserver update

client/app/src/accounts/AccountController.js, client/app/src/accounts/view/verifyMessage.html
actually there is the possibility to verify messages by klicking on the button(for own messages) or writing all details into the verify dialog. It would also been useful if you can verify the copied string (which you may receive from the other user). For this I added an addtional tab into the verify dialog.
resolving #187
=> implemented verifying of copied messages

client/app/index.html, client/app/src/accounts/AccountController.js
With this you can export the basic account details and transactions to a CSV-List and View it with your favorite spreadsheet software. solving #223
=> CSV Export of Account

README.md
This note could be useful for completeness and point to the fix if someone has this problem.
=> Add a note to README about the node-hid dependencies

client/app/assets/app.css, client/app/index.html
=> Add padding to balance text

main.js
Let me know if y'all want anything changed!
https://github.com/electron/electron/issues/2717
According to this they don't do dynamic updating, and so this is the way to update the menu items at runtime
=> adds update screenshot protection function fixes issue #252

main.js, package.json
=> Update to maintain window state upon close #256

client/app/src/accounts/account.controller.js
=> Include ledger in balance total

client/app/index.html
#277 Check if ledgercomm is set, to determine if the 'Sign Message' tab is… displayed.
This _should_ work. I won't have a Ledger until next month to test 100%. I need someone with one  to test this.
=> #277 - Remove 'Sign / Verify Message' for Ledger users.

client/app/src/accounts/view/sendArk.html
Hi, this should hide the qr-code icon if ledger is connected.
=> Fix qr-code on send ark in ledger account

client/app/src/accounts/account.controller.js, client/app/src/accounts/account.service.js, client/app/src/accounts/view/showTransaction.html
Hi, this should resolve #307. I think the recipient address need to show only in `type == 0`.
=> Remove recipient address and change type to label on the show transaction

client/app/src/accounts/account.controller.js, client/app/src/accounts/account.service.js, client/app/src/accounts/view/addDelegate.html
When no internet connection is available, choosing to "Add Delegate" doesn't show the dropdown. If it's not obvious that internet connection isn't available, it looks like a UI glitch. Initially reported on Reddit:
https://www.reddit.com/r/ArkEcosystem/comments/7210ck/voting_problem_in_client/
=> Add Delegate - Feedback when no internet connection

client/app/src/accounts/account.service.js
Hi. I read the blog and saw that we will change the fees soon and I noticed that the `account.service` uses fixed values to validate and create a transaction.
In api we have this route: https://ark.brianfaust.me/#/Block/blocks_getFees.
I get the fees from it but I made a default variable in case the user is not connected.
Please let me know if you need any changes.
=> Get fees from api before create the transaction

client/app/src/accounts/account.controller.js
fixed the account amount bug by replacing the getAllAccounts() call with myAccounts()
=> swapped method for getting accounts to fix amount display bug

client/app/src/components/addressbook/addressbook.controller.js
There was a bug causing Contacts to be unable to be deleted or edited, due to an undeclared increment variable.
=> declared increment before use to fix contact deletion bug - Resolves #333

client/app/src/accounts/account.controller.js
Resolves #360
Can't remove a Ledger account
=> Hide 'Remove' button for a Ledger account

client/app/index.html
Hi, i noticed that the currency balance is showing the total balance of all accounts
=> Fix current account balance

.vscode/extensions.json, .vscode/settings.json
Added vscode-standardjs as a recommended extension and basic editor options.
=> Add extensions and settings file to .vscode

client/app/config/appearance.js, client/app/src/accounts/account.controller.js, client/app/src/accounts/account.service.js, client/app/src/addons/pluginLoader.addon.js, client/app/src/components/qrScanner/qrScanner.controller.js, client/app/src/components/shapeshift/lib/shapeshift-api.js, client/app/src/components/shapeshift/lib/widget.js, client/app/src/filters/filters.js, client/app/src/services/changer.service.js, client/app/src/services/network.service.js, client/app/src/services/storage.service.js, client/app/src/services/time.service.js, client/app/src/services/toast.service.js, main.js
This commit adapts all the pending code to StandardJS but some parts that imply changing the original logic (removing unused functions that could be invoked in other places, etc.).
=> Adapt more code to StandardJS

test/components/addressbook/addressbook.controller.js
The unit tests were not completely filled out yet so I got them set up for mocked DI. This should help us move forward with additional testing.
=> Add mocked dependency injection for unit testing

client/app/src/services/network.service.js
To prevent hanging of the application by forcing everything (settings, etc) in the storageService to save.
=> Stop force save of storageService

client/app/src/accounts/account.controller.js, client/app/src/components/dashboard/account-box.controller.js, client/app/src/components/dashboard/account-box.html, test/components/dashboard/account-box.controller.js
=> Refresh accounts on connect to network

client/app/src/accounts/account.controller.js, client/app/src/accounts/account.service.js, client/app/src/accounts/view/validateTransactionDialog.html, client/app/src/components/account/templates/account-card.html, client/app/src/components/account/templates/offchain-tab.html, client/app/src/components/account/templates/transaction-tab.html, client/app/src/components/addressbook/addressbook.controller.js, client/app/src/components/dashboard/account-box.html, client/app/src/directives/validAmount.directive.js, client/app/src/filters/filters.js, test/components/addressbook/addressbook.controller.js
As per @luciorubeens suggestion in #407 
Created a filter to convert arktoshi into ark.
=> add arktoshi to ark filter, rather than using a constant and dividing

client/app/src/services/network.service.js
Used @alexbarnsley api call, which meant I didn't need to do the conversion from euros to usd. Also didn't want to deal with merge conflicts and undo some changes so I made a new branch and new pr.
Closes #412
=> Get specific currencies

client/app/src/components/account/templates/send-transaction-dialog.html
@stevenhuijgens I've made some changes that predates the ones from https://github.com/ArkEcosystem/ark-desktop/pull/438.
=> Adapt the width of the transaction amount to deal with language support

client/app/src/accounts/account.controller.js, client/app/src/accounts/account.service.js, client/app/src/components/account/templates/main-sidenav.html, client/app/src/components/account/templates/transaction-tab.html, client/app/src/filters/filters.js
Created a function in filters.js called smallid, smallid filter now calls that, and so does account label.
=> account label filter moved to filters.js

client/app/src/accounts/account.controller.js, client/app/src/accounts/view/addDelegate.html
Noticed that when I clicked add delegate more than once, I started to get errors. This fixes it.
=> Fixes add delegate mddialog error.

client/app/src/accounts/account.controller.js
Bug was introduced by myself.
No need for the PR reward for this.
=> Fix that refresh animation does never stop if you have no accounts

client/app/src/components/dashboard/account-box.html
- 4px needed to not have scroollbar with 5 accounts.
- Ledged loading animation was too big
=> Little dashboard visual fixes

client/app/assets/app.css
I apologize for the tiny PR, but such little things annoy me a lot.
- the import/create buttons are not in the middle
- same with the account type select menu, is up a bit
=> Dashboard accounts box

client/app/src/accounts/account.controller.js, client/app/src/components/account/templates/account-card.html, test/accounts/account.controller.js
Renamed selectNextCurrency() in account.controller.js to selectCurrency().
Added tests for selectCurrency()
=> Added ability to shift-click the currency button to have it rotate backwards

client/app/src/components/account/templates/send-transaction-dialog.html
To avoid problems such as https://cointelegraph.com/news/newly-discovered-vulnerability-in-all-ledger-hardware-wallets-puts-user-funds-at-risk
=> Add a message on the sending dialog when using a Ledger

client/app/src/components/account/templates/account-card.html, client/app/src/components/account/templates/main-sidenav.html, client/app/src/components/addressbook/addContact.html
If account != contact -> add contact instead of edit contact
@alexbarnsley Edit: resolves #550
=> Add contact directly from account overview

client/app/src/services/network.service.js, client/app/src/services/storage.service.js
=> Delete network related data when deleting a network

main.js
Fixes issue #557 and standardizes application's menu to match the system.
<sub><sub><sub>My own approval.</sub></sub></sub>
&nbsp;&nbsp;&nbsp;&nbsp;↓
=> Standardized menu and shortcut to match the system’s

client/app/src/accounts/view/verifyMessage.html, client/app/src/components/account/signing-tab.controller.js
Fixes https://github.com/ArkEcosystem/ark-desktop/issues/580 and https://github.com/ArkEcosystem/ark-desktop/issues/581
[![Screenshot from Gyazo](https://gyazo.com/a7e43e40e70037bfc2de6a072ee11eb5/raw)](https://gyazo.com/a7e43e40e70037bfc2de6a072ee11eb5)
=> Fixes Verify Message bugs - Issues #580 and #581

package.json
- CVE-2018-1000136
- CVE-2018-1000118
=>  Upgrade Electron due security issues

main.js
Fixed issues discussed here: #576
=> Fixed cross-platform menu to be more consistent and bring back missing items

client/app/src/accounts/account.controller.js, client/app/src/components/layout/main-navbar.html
PR related to https://github.com/ArkEcosystem/ark-mobile/pull/148
To make it compatible.
=> Generate and import passphrase in all possible bip39 languages

client/app/src/components/account/account-card.controller.js, test/components/accounts/account-card.controller.js
Related to https://github.com/ArkEcosystem/ark-desktop/issues/589
=> Change the remove icon of the wallet menu to something more recognisable

client/app/src/services/time.service.js, package-lock.json, package.json
There is a problem with the certificate of https://tycho.usno.navy.mil/cgi-bin/time.pl.
This PR replaces that request with NTP.
=> Replace tycho with ntp

client/app/src/accounts/account.controller.js, client/app/src/accounts/transaction-builder.service.js, client/app/src/components/qr-scanner/qr-scanner.directive.js, client/app/src/services/network.service.js
Access to the webcam was tried more times than necessary, slowing down the app.
=> Fix webcam loop

client/app/src/accounts/account.controller.js, client/app/src/accounts/transaction-builder.service.js
Seems that https://github.com/ArkEcosystem/ark-js/pull/85 provoked a problem when signing transactions with the Ledger.
=> Fix the signing of transactions using the Ledger

client/app/src/components/account/exchange-tab.controller.js, client/app/src/components/account/templates/exchange-tab.html
Display a confirmation button after checking the terms. I also adjusted some details in the grid and text.
=> chore: add confirm button to changelly

client/app/src/services/transaction-sender.service.js
The URI is deserialized but the fields are not filled.
=> fix: populate the uri schema correctly

.github/CONTRIBUTING.md
Sets correct contributing link, closes #635.
=> chore: fix contributing link

package.json, yarn.lock
=> fix: mainnet peers

src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
Saves currency persistently, fixes #640
=> feat: save currency persistently when changed through sidemenu

src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
fixes #662, also see that issue for a link to test it
=> fix: validate fields when they get populated by aip13

src/renderer/components/Network/NetworkModal.vue, src/renderer/i18n/locales/en-US.js, src/renderer/store/modules/peer.js
There was little validation for the adding/modifying a network. This improves them all, but also adds peer validation to make sure the seed is a valid one before saving.
Relates to #673
=> fix: network validation

src/renderer/components/Transaction/TransactionTable.vue
Change for the fixes #675 , the full date is now displayed in the Transactions table.
=> fix : Modified to long format date for the Transactions Table

package.json, src/renderer/styles/_general.css
=> fix: custom scrollbar on linux

package.json, src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
And also disable it in development mode by default.
=> feat: set screenshot protection by environment variable

src/renderer/pages/Announcements.vue
sortBy replaced with orderBy
1. More readability
2. Decreased complexity (no need of reverse() )
=> Refactor: Fetching announcements

src/renderer/i18n/locales/en-US.js, src/renderer/store/modules/network.js
Fixes an issue where, if there's a seed that is no longer working, or an invalid one was added, it will result in a white screen on app load.
Resolves #673
=> fix: white screen on bad network seed

README.md
Fixes the release badge on the readme.
=> chore: fix release badge

src/renderer/components/App/AppSidemenu/AppSidemenu.vue
This adds a simple icon to the avatar to try to highlight that clicking it does something.
=> refactor: add avatar profile "more" icon

__tests__/unit/components/Input/InputFee.spec.js, src/renderer/components/Input/InputFee.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
The message about "not enough funds" was displayed always.
=> fix: check correctly if the balance is enough for creating the second signature

package.json, src/renderer/components/App/AppSidemenu/AppSidemenu.vue
Uses the `semver` package to determine if there is a new version available. Right now a false positive is displayed, since 2.0.0 (latest release) and 2.1.0 (package.json) are not equal, but the former is not higher than the latter.
=> refactor: use semver for release check

src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue, src/renderer/i18n/locales/en-US.js, src/renderer/models/profile.js, src/renderer/services/client.js, src/renderer/services/synchronizer/wallets.js, src/renderer/store/modules/session.js
There is now a new issue as a result of updating ledger wallets in the background. If there are a lot of ledger wallets, it slows down the app due to the amount of requests needed. This flag allows disabling the background update per profile.
=> feat: background update ledger flag

src/renderer/components/MarketChart/MarketChartHeader.vue
There is currently no visual feedback when hovering over the chart header buttons.
=> refactor: chart buttons hover background color

src/renderer/App.vue, src/renderer/i18n/locales/en-US.js, src/renderer/models/profile.js, src/renderer/pages/Wallet/WalletAll.vue, src/renderer/store/index.js, src/renderer/store/modules/ledger.js, src/renderer/store/modules/session.js
Gives the option of caching ledger wallets to speed up loading. This is off by default and the switch can be found on the WalletAll page when a ledger is plugged in. If the option is turned all, all cached ledger wallets for that profile are removed from the cache.
=> feat: cache ledger wallets

src/renderer/components/App/AppSidemenu/AppSidemenu.vue, src/renderer/components/Wallet/WalletDetails/WalletDetails.vue, src/renderer/styles/_table.css
The avatar dots are currently too big and break the navbar on smaller screens.
This PR adds a bit of responsiveness to the dots:
Further changes:
- removes whole search menu icon div
- hides delegate details if it has no rank
- adds cursor pointer on table headers
=> fix: responsive navbar avatar & ui tweaks

src/renderer/i18n/locales/en-US.js, src/renderer/pages/Wallet/WalletAll.vue
Adds a tooltip to the ledger caching option to give a little more detail
=> feat: ledger cache option tooltip

src/renderer/models/base.js
There's some errors which are hard to avoid efficiently with jsonValidate schema, for instance Delegate Registration has no recipient, but all transaction types are based off the TransactionModel, which has a strict schema where recipient is a string. Therefore, it might be acceptable to pretty-print the JSON schema used against the input, as well as the input itself.
I thought this might be a welcome change for debugging the schema.
=> fix: uninvuitive for jsonValidate() return value if (errors)

README.md
=> docs: add instructions to install via package managers

__tests__/unit/services/wallet.spec.js, src/renderer/pages/Wallet/WalletImport.vue
Adds tests to show usage of NFD with passphrases. Also adds a comment in `importWallet` to indicate why it's used there
=> test: normalizing passphrase with NFD option

src/renderer/i18n/locales/en-US.js, src/renderer/pages/Wallet/WalletImport.vue
add: Duplicate Address Validation
=> fix: duplicate address validation on `WalletImport`

src/renderer/pages/Profile/ProfileAll.vue
tooltip on All profiles page was unnecessary and annoying. It doesn't help user in any way neither does it look good neither does it improve user experience.
Remove :title of profile
=> Remove tooltip on ProfileAll

src/renderer/components/Input/InputField.vue, tailwind.js
#700 where input field border is too bright, this is because it uses the default light-theme color when it is supposed to use theme-line-separator color.
Add border-theme-line-separator to all input fields
=> fix: add border-theme-line-separator to input fields

src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue, src/renderer/i18n/locales/en-US.js
Solves https://github.com/ArkEcosystem/desktop-wallet/issues/813 and https://github.com/ArkEcosystem/desktop-wallet/issues/685
=> misc: rephrase "Network overview" to "My networks" to make the button clearer

package.json
=> chore: bump to 2.1.1

__tests__/unit/components/Transaction/TransactionModal.spec.js, src/renderer/components/Transaction/TransactionModal.vue, src/renderer/i18n/locales/en-US.js
Now I understand why people were complaining... All transactions were accepted regarding the tx fee because this was returning `true` when it should be returning `false` because of the error:
https://github.com/ArkEcosystem/desktop-wallet/blob/dc16bd3ba07c3299ba8aa0f2c64705ebc20cd75d/src/renderer/components/Transaction/TransactionModal.vue#L142
This PR fixes this and it's showing the users the exact error message returned from the core.
=> fix: transaction send response

src/renderer/components/Wallet/WalletSelection.vue
Fixes bug shown [here](https://github.com/ArkEcosystem/desktop-wallet/pull/814#issuecomment-449362294)
=> fix: ledger check in wallet selection when connected

src/renderer/components/Wallet/WalletButtons/WalletButtonCreate.vue, src/renderer/components/Wallet/WalletButtons/WalletButtonImport.vue, src/renderer/components/Wallet/WalletButtons/index.js, src/renderer/components/Wallet/index.js, src/renderer/pages/Dashboard.vue, src/renderer/pages/Wallet/WalletAll.vue
=> Dashboard: add icons above create/import wallet

src/main/index.js
Fixes Linux loading the `ark` URI.
Resolves #834
=> fix: `ark:` uri on linux

__tests__/unit/mixins/qr.spec.js
=> test: qr mixin

src/renderer/components/Wallet/WalletAddress.vue
Adds navigation to vote transactions, like the type 0 transactions already have
=> feat: add navigation to vote transactions

src/renderer/components/Transaction/TransactionShow.vue
The modal to show transaction information simply showed the address of sender / recipient instead of (e.g.) vote / unvote like the transaction table does. This PR adds that same behaviour to the modal:
=> feat: use WalletAddress in the transactionShow modal

src/renderer/i18n/locales/en-US.js, src/renderer/pages/Profile/ProfileAll.vue, src/renderer/pages/Profile/ProfileNew.vue
The new profile page is the only such page where the steps aren't numbered as of now.
=> refactor: numbered 'profile new' steps

src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
Fixes some mis-alignments in the sidebar component.
=> refactor: improves sidebar alignments

src/renderer/i18n/locales/en-US.js
As discussed in slack, it might be better to rename `approval` to `vote %`
=> chore: rename approval to vote %

config/networks/mainnet.json
Adds another one of Binance's wallets: https://explorer.ark.io/wallets/Aakg29vVhQhJ5nrsAHysTUqkTBVfmgBSXU
=> chore: add another Binance wallet

src/renderer/components/Wallet/WalletSelection.vue
=> fix: uri ledger issue with 1 non-ledger wallet

__tests__/unit/components/Modal/ModalConfirmation.spec.js, src/renderer/components/Modal/ModalConfirmation.vue
=> fix: confirm modal default portal target

.circleci/config.yml, package.json, yarn.lock
=> chore: add codecov

src/renderer/components/Transaction/TransactionModal.vue, src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue, src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
=> fix: handle unsuccessful unvote transaction

src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue, src/renderer/i18n/locales/en-US.js
=> fix: close vote modal on confirm

src/renderer/components/MarketChart/MarketChart.vue
=> fix: Provide chart tooltip when hovering on x-axis

package.json, yarn.lock
This is for a change to which API header is sent to determine v1 or v2. This is done for the sole reason that core is changing the header value, but we could only cater for the old vendor name or the new one, not both.
=> core: update @arkecosystem/client

__tests__/unit/pages/Wallet/WalletAll.spec.js, src/renderer/models/profile.js, src/renderer/pages/Contact/ContactAll.vue, src/renderer/pages/Wallet/WalletAll.vue, src/renderer/store/modules/session.js
The change to layout between grid and tabular wasn't persisting between reloads. This fixes this, along with some renaming as "layout" was too ambiguous.
=> fix: persist wallet layout

src/renderer/components/ListDivided/ListDividedItem.vue
https://github.com/ArkEcosystem/desktop-wallet/commit/b7856133833f8fbdb70a0790a3ff2df83d10d0b2 introduced changes to the `ListDividedItem` component which result in the transaction confirmation modal being misaligned:
=> fix: conditional alignment of items

src/renderer/pages/Wallet/WalletNew.vue
Solves https://github.com/ArkEcosystem/desktop-wallet/issues/944
=> fix: do not shake when generating new wallets

src/renderer/components/Modal/ModalLoader.vue, src/renderer/components/Transaction/TransactionModal.vue, src/renderer/i18n/locales/en-US.js, src/renderer/services/client.js
=> feat: loading screen when broadcasting to many peers

package.json
=> chore: bump to 2.2.1

src/renderer/pages/Contact/ContactAll.vue, src/renderer/pages/Wallet/WalletAll.vue
Fixes #1051 and cleans up the css a bit.
=> fix: make contacts container scrollable

src/renderer/components/Button/ButtonClipboard.vue
Should have been part of https://github.com/ArkEcosystem/desktop-wallet/pull/1053.
=> fix: add subject to clipboard button upon resetting tooltip

src/renderer/styles/_table.css
This PR was initially intended to fix a problem detected with the pagination on the transaction table.
Since the source of the bug is on core (https://github.com/ArkEcosystem/core/issues/2118), the only thing that has been changed is a tiny UX fix.
=> fix: use the cursor pointer on the pagination "rows per page" dropdown

src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue, src/renderer/i18n/locales/en-US.js, src/renderer/pages/Profile/ProfileEdition.vue, src/renderer/pages/Profile/ProfileNew.vue
This PR is part of the changes to revamp how we structure the settings.
=> feat: move "Chart on dashboard" setting to profile creation and edition

src/renderer/i18n/locales/en-US.js, src/renderer/pages/Wallet/WalletNew.vue
- Display the identicon and improve style in the confirmation step when creating a new wallet
By Oleg
=> refactor: display the identicon and improve style on confirmation of new wallet

src/renderer/store/modules/session.js
=> fix: change UI language when changing profile

package.json
=> chore: bump to 2.3.0

__tests__/unit/store/modules/ledger.spec.js, src/renderer/services/ledger-service.js, src/renderer/store/modules/ledger.js
This PR refactors Ledger-related code.
=> fix: do not store Ledger connection timer since it is not used

package.json
=> chore: bump to 2.3.1

__tests__/unit/services/synchronizer/wallets.spec.js, src/renderer/App.vue, src/renderer/services/synchronizer/wallets.js, src/renderer/store/modules/ledger.js
=> fix: ledger issues

package.json
=> chore: bump to 2.3.2

config/networks/mainnet.json
https://explorer.ark.io/wallets/AagJoLEnpXYkxYdYkmdDSNMLjjBkLJ6T67
=> chore: update ACF address

src/renderer/i18n/locales/it-IT.js
Small changes to improve italian translation.
=> misc: Italian translation update

package.json, src/renderer/services/client.js, yarn.lock
Changing how the transaction are signed was necessary.
=> chore: upgrade `@arkecosystem/crypto` to 2.2.2

src/renderer/components/Network/NetworkModal.vue
This relates directly for when adding a new network to the wallet.
I've also added an issue to improve tests for this particular modal: https://github.com/ArkEcosystem/desktop-wallet/issues/1163
=> fix: improve validation for epoch format

src/renderer/services/plugin-manager.js
The `AudioContext` will be useful for playing audio buffers. 
Functional example: https://github.com/luciorubeens/ark-desktop-sound-notifications
=> feat(plugins): include audio permission

src/renderer/components/Plugin/PluginEnableConfirmation.vue, src/renderer/components/Plugin/PluginTable.vue, src/renderer/components/Plugin/index.js, src/renderer/i18n/locales/en-US.js, src/renderer/pages/Plugins.vue
=> feat(plugins): ask for confirmation to enable plugins

src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue, src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue, src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue, src/renderer/components/Menu/MenuDropdown/MenuDropdownItem.vue, src/renderer/components/Menu/MenuNavigation/MenuNavigationItem.vue, src/renderer/components/Menu/MenuOptions/MenuOptionsItem.vue, src/renderer/components/Wallet/WalletSidebar/WalletSidebarFilters.vue, src/renderer/directives/click-outside.js
This PR is related to https://github.com/ArkEcosystem/desktop-wallet/pull/1175 and https://github.com/ArkEcosystem/desktop-wallet/pull/1174, which, were unrelated and worked successfully isolated, but, when combined, they were producing some small side effects.
Components that have been tested:
- Wallet selection (when sending transfers)
- Profile creation dropdowns
- Profile edition dropdowns
- Settings menu
- Settings menu currency dropdown
- Networks menu
- Networks menu peers dropdown
- Wallet sidebar filters
- Delegate search / selection
=> fix: the wallet selection dropdown and the wallet sidebar filters

src/renderer/services/plugin-manager.js
Currently only the context of the `mounted` method has been defined.
=> fix(plugins): define the context of all hooks

src/renderer/components/Wallet/WalletTransactions/WalletTransactions.vue
Solves https://github.com/ArkEcosystem/desktop-wallet/issues/1183
=> fix: do not fail when navigating to other page while loading transactions

src/renderer/components/Wallet/WalletDetails/WalletDetails.vue, src/renderer/services/plugin-manager.js, src/renderer/store/modules/plugin.js
Allow that developers could add tabs to the wallet section, like https://github.com/j-a-m-l/ark-desktop-wallet-stats
=> feat(plugins): allow adding new tabs to the wallet page

src/renderer/App.vue, src/renderer/components/App/AppSidemenu/AppSidemenu.vue, src/renderer/components/Input/InputGrid/InputGridItem.vue, src/renderer/components/Profile/ProfileAvatar.vue, src/renderer/components/Selection/mixin-selection-image.js, src/renderer/pages/Profile/ProfileNew.vue
Due to something changing, possibly when first merging develop to the plugins branch, the avatars stopped working. This fixes those issues.
**Note: this slows down the app startup time, so may need some ideas for this. It's because I've forced it to wait for plugins to load before progressing with the rest of the app. Not sure if caching causes it but avatars don't always show up in the plugin is loaded after the app.**
=> fix(plugins): avatar plugins not working correctly

config/networks/mainnet.json
=> Added Altilly Exchange to known wallets.

src/renderer/pages/Profile/ProfileAll.vue
=> fix: align the add profile placeholder

src/renderer/components/MarketChart/MarketChart.vue
It was displaying values such as "7:undefined PM".
=> fix: days on the X axis of the market chart

src/renderer/store/modules/network.js
When creating the initial profile the network has not yet been defined.
=> fix: fetch fees only if the network is available

__tests__/unit/store/modules/peer.spec.js, package.json, src/renderer/models/peer.js, src/renderer/services/client.js, src/renderer/store/modules/peer.js, yarn.lock
Status is no longer provided in peer lists, which causes issues when trying to connect to peers.
=> fix: peer management on v2.4+

src/renderer/components/Input/InputGrid/InputGrid.vue, src/renderer/components/Input/InputGrid/InputGridModal.vue
There were issues with the selection of plugin avatars. Originally it worked, because there was only one avatar to choose from. I've since added more to the plugin: https://github.com/alexbarnsley/desktop-wallet-avatar-plugin
=> fix(plugins): avatar plugin selection

src/renderer/components/Transaction/TransactionModal.vue
Some successful transactions were not detected as it.
=> fix: detect successful transactions correctly

src/renderer/components/Wallet/WalletExchange/WalletExchange.vue
=> chore: update changelly url

src/renderer/components/Plugin/PluginTable.vue, src/renderer/models/profile.js, src/renderer/pages/Plugins.vue, src/renderer/services/plugin-manager.js, src/renderer/store/modules/session.js
Fixes the sorting on the plugin table which was overwriting the sorting of the contacts.
=> fix: plugin table sorting

src/renderer/i18n/locales/it-IT.js
Update of the Italian translation, following the introduction of the plugin system. Other minor corrections.
=> misc: Italian language update

src/renderer/components/Wallet/WalletSidebar/WalletSidebarFilters.vue
Resolves #1264 
- [x ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)
=> feat: use the theme colours for the wallet filters instead of white

__tests__/unit/store/modules/peer.spec.js, package.json, yarn.lock
There is vulnerability on `axios` <= 0.18: https://nvd.nist.gov/vuln/detail/CVE-2019-10742#vulnCurrentDescriptionTitle
=> deps: upgrade `axios` (CVE-2019-10742)

src/renderer/components/Wallet/WalletExchange/WalletExchange.vue
Fixes the changelly widget issue about not being allowed on the domain. Resolves #1275 
=> fix: use webview  instead of iframe for changelly

src/renderer/components/Wallet/WalletButtons/WalletButtonLedgerSettings.vue
Fix Ledger Options button on built versions.
=> fix: ledger options on build

src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
Fixes #1290 and a minor css issue when loading ledgers.
=> fix: prioritize Ledger wallets on the wallet sidebar

package.json
=> chore: bump version to 2.5.0

src/renderer/components/App/AppSidemenu/AppSidemenu.vue, src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue, src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
Fixes an issue where re-clicking the sidebar button (e.g. settings) to close the popup doesn't work.
=> fix: sidebar popup button click to close

src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
=> refactor: add tooltip to wallet name

package.json
=> chore: bump to 2.5.1

src/renderer/components/Wallet/WalletExchange/WalletExchange.vue, src/renderer/pages/Wallet/WalletAll.vue
Allows the user to open the context menu of the wallet cards by right-clicking on them.
=> feat: toggle wallet dropdown on right mouse click

__tests__/unit/store/modules/ledger.spec.js, package.json, src/renderer/services/client.js, src/renderer/services/transaction.js, src/renderer/services/wallet.js, src/renderer/store/modules/ledger.js, src/renderer/workers/bip38-worker.js, yarn.lock
=> refactor: upgrade the crypto package to latest version

src/renderer/i18n/locales/en-US.js
=> chore: update current vote wording

__tests__/unit/components/Network/NetworkModal.spec.js, src/renderer/components/Network/NetworkModal.vue
Fixes a bug as a result of removing the v1 endpoint support
=> fix: populate network data

src/renderer/components/Input/InputCurrency.vue
I changed value to this.inputValue in methods isMoreThanMinimum() and isLessThanMaximum() to fix amount and fee invalid input warnings not showing and changed regex so the fields don't accept NaN values.
fixes #1334  
=> fix: Bugs related to amount and fee transaction inputs

src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue, src/renderer/i18n/locales/en-US.js, src/renderer/services/wallet.js
There currently is no check against existing delegate usernames on the delegate registration transaction form.
=> refactor: check if username exists in delegate registration form

src/renderer/components/Wallet/WalletHeading/WalletHeading.vue
=> fix: update wallet header on ledger disconnect

src/renderer/store/modules/network.js
=> fix: stop fee update using api version as timeout

config/index.js, src/renderer/services/plugin-manager.js, yarn.lock
Small generic changes: 
- Use a different path for loading plugins when the wallet is in development mode
- Can now get the current route ($route) from within a plugin
=> feat: plugin system improvements

src/renderer/services/ledger-service.js, src/renderer/store/modules/ledger.js
=> fix: ledger rejecting transaction

src/renderer/components/App/AppIntro/AppIntro.vue, src/renderer/components/App/AppIntro/AppIntroScreen.vue, src/renderer/i18n/locales/en-US.js, src/renderer/i18n/locales/it-IT.js, src/renderer/styles/_theme.css, tailwind.js
Fixes #1377.
Also adjusts the position of the Ark logo in the corner.
=> fix: add gradients and scrolling to intro pages

src/renderer/plugins/bignumber.js
Exporting wallets on mainnet not working due to multipliedBy being undefined: https://github.com/ArkEcosystem/desktop-wallet/issues/1390
=> fix: exporting wallets on mainnet not working due to multipliedBy being undefined

src/renderer/i18n/locales/it-IT.js
Italian language update - follows #1382 
=> misc: it-IT update - follows #1382 

__tests__/unit/components/utils/WebFrame.spec.js, src/renderer/components/utils/WebFrame.js
Allow same origin from sandbox. Also fix classes being passed into the iframe.
=> fix: webframe same origin

src/renderer/App.vue
=> fix: design height on large pages

src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue, src/renderer/components/Wallet/WalletDetails/WalletDetails.vue, src/renderer/components/Wallet/WalletSelectDelegate.vue
Returns the selected delegate instead of searching in the store, which is still being updated.
=> fix: details modal not showing to recently registered delegates

__tests__/unit/__fixtures__/store/profile.js, __tests__/unit/components/Input/InputFee.spec.js, __tests__/unit/services/client.spec.js, __tests__/unit/services/synchronizer/wallets.spec.js, __tests__/unit/store/modules/transaction.spec.js, src/renderer/App.vue, src/renderer/components/Input/InputFee.vue, src/renderer/components/Wallet/WalletDetails/WalletDetails.vue, src/renderer/services/client.js, src/renderer/services/synchronizer.js, src/renderer/services/synchronizer/wallets.js, src/renderer/store/modules/transaction.js
Check for unconfirmed votes in the synchronizer and whenever it looks for new transactions.
=>  fix: check unconfirmed votes when updating transactions

src/renderer/services/synchronizer/wallets.js
=> fix: new delegate registration transaction message

src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue, src/renderer/i18n/locales/en-US.js
=> fix: voting explanation delegate count

src/renderer/components/Input/InputFee.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue, src/renderer/components/Transaction/TransactionModal.vue
The new option to use the last fee is under the value.
=> fix: increase transaction modal width

src/renderer/components/Wallet/WalletExchange/WalletExchange.vue
The page opens a url via `target="_blank"`.
=> fix: allow the Changelly widget to open popups

.electron-vue/webpack.renderer.config.js, __tests__/unit/store/modules/peer.spec.js, package.json, src/renderer/components/Network/NetworkModal.vue, src/renderer/store/modules/peer.js, yarn.lock
=> fix: bridgechain peer issues

package.json, yarn.lock
=> chore: bump version to 2.6.1

package.json, yarn.lock
Solution found here: https://github.com/node-hid/node-hid/issues/321
Closes #1440  
=> fix: ledger device path empty in production

src/renderer/components/Wallet/WalletSignModal.vue
- Required network wif for signing messages
- Don't save failed message signings
Password signing is broken for bridgechains
:magic:
=> fix: wallet password message signing

.github/workflows/lint.yml, .github/workflows/test.yml
Run tests only on merges to master/develop and pushes to open PRs. This avoids duplicates push and pull request jobs.
=> ci: update workflow triggers

__tests__/unit/services/plugin-manager/sandbox/storage-sandbox.spec.js, src/renderer/services/plugin-manager/sandbox/storage-sandbox.js, src/renderer/store/modules/plugin.js
=> feat(plugins): global storage

__tests__/unit/services/plugin-manager/component/create-component.spec.js, src/renderer/services/plugin-manager/component/create-component.js
Parse the methods to be called directly or through events.
=> fix(plugins): fix context of methods

README.md
=> docs: stop translations

README.md
Replaces the outdated circle ci badge with a status badge reflecting the latest action run on the default branch and other minor readme tweaks.
=> chore: update status badge and other readme tweaks

package.json, yarn.lock
=> chore: update electron-builder

package.json
=> chore: bump version 2.7.0

.github/workflows/test.yml
=> chore: bump workflow version 2.7.0

src/renderer/App.vue, src/renderer/components/Modal/ModalWindow.vue
=> fix: refactor blur filter to handle portal registration

__tests__/unit/components/Wallet/WalletDelegates.spec.js, src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
Limits the delegate query to 100 and dynamically calculates the per page options.
=> fix: limit delegate query to 100 & dynamic per page options

.github/workflows/test.yml, package.json
=> chore: bump version to 2.8.0

CODEOWNERS
=> chore: remove juan as codeowner

src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
Update link to: https://guides.ark.dev/usage-guides/desktop-wallet-voting
=> chore: update doc link to vote for a delegate

src/renderer/pages/Profile/ProfileEdition.vue
=> fix: truncate profile name

.github/workflows/test.yml, package.json
=> chore: bump version to 2.8.1

.github/workflows/test.yml, src/main/index.js, src/main/plugin-manager.js
=> fix: plugin downloads

.github/workflows/publish-release.yml
Doesn't support windows right but will be added in a follow-up PR.
=> ci: upload production artifacts to VirusTotal

src/renderer/mixins/electron.js
Follow-up to #1711. This PR also adjusts the `electron_readFile` method.
=> fix: use showOpenDialog with promise instead of callback

src/renderer/components/Transaction/TransactionShow/TransactionShow.vue
=> fix: dashboard show transaction

__tests__/unit/components/Transaction/TransactionShow.spec.js
=> test: amount tooltip on transaction show modal

src/renderer/router/index.js
=> fix: warning when navigating to current route again

src/renderer/components/Transaction/TransactionMultiSignatureList.vue, src/renderer/store/modules/session.js
=> style: remove eslint warn messages

__tests__/unit/store/modules/ledger.spec.js, src/renderer/store/modules/ledger.js
=> fix: ledger error when checking version

src/renderer/SplashScreen.vue
With this change the splashscreen logo container becomes square.
=> chore: square splashscreen logo

src/main/index.js, src/main/menu.js
=> fix: splashscreen showing on main window hide

src/main/index.js, src/main/menu.js
=> fix: main window fullscreen state when closing and re-opening

src/renderer/components/Modal/ModalRename.vue, src/renderer/pages/Contact/ContactNew.vue
Fixes #1740 by fetching the wallet from the network when added as a contact. If it's a cold wallet, the contact is created the old way, with the addition of the balance property.
=> fix: fetch wallet when adding/creating as contact

src/renderer/components/Wallet/WalletGrid.vue
This PR adds alternative balances to the wallet/contact grid.
=> feat: show alternative balances in wallet grid

.github/workflows/draft-artifacts.yml, .github/workflows/test.yml, package.json, yarn.lock
=> chore: add staging to workflow

__tests__/unit/mixins/electron.spec.js, __tests__/unit/services/plugin-manager/sandbox/dialogs-sandbox.spec.js
=> test: add unit tests for dialogs sandbox and electron mixin

src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue, src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue, src/renderer/components/Menu/MenuDropdown/MenuDropdownItem.vue, src/renderer/components/Transaction/TransactionStatusIcon.vue
=> fix: dark theme tweaks

src/renderer/components/Wallet/WalletHeading/WalletHeadingSecondaryActions.vue
=> fix: access the vue-i18n property at the root

src/renderer/components/Transaction/TransactionTable/TransactionTableMultiSignature.vue
=> fix: multisig transaction type/group

.github/workflows/draft-artifacts.yml, .github/workflows/publish-release.yml, scripts/version-artifacts.sh
`npm version 2.9.0 --no-git-tag-version`
=> chore: bump version in all github configurations

src/renderer/i18n/locales/en-US.js
=> chore: add translation for DIALOGS permission

__tests__/unit/store/modules/delegate.spec.js, src/renderer/store/modules/delegate.js
=> fix: include last delegate page when fetching

__tests__/unit/components/PluginManager/PluginManagerGrid.spec.js, src/renderer/components/PluginManager/PluginManagerGrid.vue
=> fix: plugin grid sorting

src/renderer/components/PluginManager/PluginManagerModals/PluginImageModal.vue
=> feat: use the left and right arrows on the keyboard to switch between the plugin images

src/renderer/services/datetime.js
Adds the dayjs `quarterOfYear` plugin.
=> chore: add dayjs quarters plugin

src/renderer/components/Transaction/TransactionTable/TransactionTable.vue, src/renderer/components/Transaction/TransactionTable/TransactionTableMultiSignature.vue, src/renderer/styles/_table.css
=> refactor: disable columns from sorting

src/renderer/components/Modal/ModalConfirmation.vue
Adds a conditional to the container of the modals question and/or note, so it is hidden when neither prop is provided.
=> refactor: check for confirm modal title or note

__tests__/unit/services/plugin-manager.spec.js, src/renderer/components/Modal/ModalConfirmation.vue, src/renderer/services/plugin-manager.js
=> fix: plugin min version

.github/workflows/publish-release.yml
=> ci: create draft release workflow

src/main/index.dev.js
This PR must be merged after PR #1889.
=> refactor: update code to install vue-devtools

src/renderer/main.js, src/renderer/plugins/env.ts, src/types.d.ts
> Resolves https://github.com/ArkEcosystem/desktop-wallet/issues/1968
=> feat: bind `Environment` instance on boot as `Vue.$env`

package.json, src/app/components/Select/Select.tsx, src/app/components/Select/__tests__/Select.spec.tsx, src/app/components/Select/__tests__/__snapshots__/Select.spec.tsx.snap, src/index.tsx
=> test: add select component tests

package.json, src/app/components/StepIndicator/__tests__/StepIndicator.spec.tsx, src/app/components/StepIndicator/__tests__/__snapshots__/StepIndicator.spec.tsx.snap
Add step indicator specs and adjust coverage collection entrypoints
=> test: add step indicator specs

src/app/components/Alert/__tests__/Alert.spec.tsx, src/app/components/Alert/__tests__/__snapshots__/Alert.spec.tsx.snap, src/app/components/Button/__tests__/Button.spec.tsx, src/app/components/Button/__tests__/__snapshots__/Button.spec.tsx.snap, src/app/components/Card/CardControl.tsx, src/app/components/Card/__tests__/CardControl.spec.tsx, src/app/components/Card/__tests__/__snapshots__/CardControl.spec.tsx.snap
Increase coverage to 100% for:
- Alert
- Button
- Card Control
=> test: increase coverage

src/app/components/SvgIcon/SvgIcon.tsx, src/app/components/Tabs/Tabs.tsx, src/app/components/Tabs/__tests__/Tabs.spec.tsx, src/app/components/Tabs/__tests__/__snapshots__/Tabs.spec.tsx.snap
- Add todo comment on svg icon to fix issue later
- Increase Tabs coverage to 100%
=> tests: add tabs specs

src/app/components/Toggle/Toggle.stories.tsx, src/app/components/Toggle/Toggle.tsx, src/app/components/Toggle/__tests__/Toggle.spec.tsx, src/app/components/Toggle/__tests__/__snapshots__/Toggle.spec.tsx.snap
=> tests: add toggle specs

src/app/components/Input/Input.tsx, src/app/components/ListDivided/ListDividedItem.stories.tsx, src/app/components/ListDivided/__tests__/ListDivided.spec.tsx, src/app/components/NavBar/NavBar.tsx, src/domains/profile/components/ProfileCard/ProfileCard.tsx, src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/Welcome/Welcome.tsx, src/domains/wallets/pages/ImportWallet/ImportWallet.tsx, src/router/index.tsx
**Reference**: https://create-react-app.dev/docs/importing-a-component/#absolute-imports
=> chore: import modules using absolute paths

package.json, src/app/components/SvgIcon/SvgIcon.tsx, src/app/components/SvgIcon/__tests__/SvgIcon.spec.tsx, src/app/components/SvgIcon/__tests__/__snapshots__/SvgIcon.spec.tsx.snap, src/resources/assets/svg/index.ts, yarn.lock
-  Remove inline require
- Add an interface to expose SVG Icons
- Add test specs
=> refactor: improve svg icon

src/domains/profile/components/ProfileCard/ProfileCard.tsx, src/domains/profile/components/ProfileCard/__tests__/ProfileCard.spec.tsx, src/domains/profile/components/ProfileCard/__tests__/__snapshots__/ProfileCard.spec.tsx.snap
=> test: add profile card specs

src/app/components/SvgIcon/SvgIcon.tsx, src/app/components/SvgIcon/__tests__/__snapshots__/SvgIcon.spec.tsx.snap, src/domains/profile/components/ProfileCard/__tests__/__snapshots__/ProfileCard.spec.tsx.snap, src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
Pass given width and height props to `<svg>` element in `SvgIcon` component.
=> chore: apply svg dimensions

src/app/components/Divider/Divider.stories.tsx, src/app/components/Divider/Divider.tsx, src/app/components/Divider/__tests__/Divider.spec.tsx, src/app/components/Divider/__tests__/__snapshots__/Divider.spec.tsx.snap, src/app/components/Divider/index.ts, src/app/components/Divider/style.ts
A divider line to separate different contents / components.
**Example:**
=> feat: add `<Divider>` component

src/app/components/Alert/Alert.stories.tsx, src/app/components/Button/Button.stories.tsx, src/app/components/Card/Card.stories.tsx, src/app/components/Divider/Divider.stories.tsx, src/app/components/Form/Form.stories.tsx, src/app/components/Icon/Icon.stories.tsx, src/app/components/Input/Input.stories.tsx, src/app/components/Input/InputGroup.stories.tsx, src/app/components/ListDivided/ListDivided.stories.tsx, src/app/components/ListDivided/ListDividedItem.stories.tsx, src/app/components/NavBar/NavBar.stories.tsx, src/app/components/Select/Select.stories.tsx, src/app/components/Select/Select.tsx, src/app/components/Select/__tests__/Select.spec.tsx, src/app/components/Select/__tests__/__snapshots__/Select.spec.tsx.snap, src/app/components/SideBar/SideBar.stories.tsx, src/app/components/SideBar/SideBarItem/SideBarItem.stories.tsx, src/app/components/StepIndicator/StepIndicator.stories.tsx, src/app/components/Tabs/Tabs.stories.tsx, src/app/components/Textarea/Textarea.stories.tsx, src/app/components/Textarea/Textarea.tsx, src/app/components/Textarea/__tests__/Textarea.spec.tsx, src/app/components/Textarea/__tests__/__snapshots__/Textarea.spec.tsx.snap, src/app/components/Textarea/index.ts, src/app/components/Toggle/Toggle.stories.tsx, src/resources/assets/svg/chevron-down.svg, src/resources/assets/svg/index.ts, src/tailwind.config.js
Also update the category of stories.
=> refactor: `Select` and `Textarea` with validation

src/app/components/Circle/Circle.stories.tsx, src/app/components/Circle/Circle.tsx, src/app/components/Circle/__tests__/Circle.spec.tsx, src/app/components/Circle/__tests__/__snapshots__/Circle.spec.tsx.snap, src/app/components/Circle/index.ts, src/app/components/Circle/style.ts
General purpose `Circle` component to be used as:
* Avatar (with custom css)
* With custom icons (default slot), as seen in Wallet cards, transactions lists, network lists
* Empty/Blank (seen in Create Wallet cards)
=> feat: add circle component

src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__tests__/CreateProfile.spec.tsx, src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
=> fix: update create profile page

src/domains/profile/pages/Welcome/Welcome.tsx, src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap, src/resources/assets/svg/index.ts, src/resources/assets/svg/msq.svg
=> chore: add marketsquare icon

src/app/components/Label/Label.stories.tsx, src/app/components/Label/Label.tsx, src/app/components/Label/__tests__/Label.spec.tsx, src/app/components/Label/__tests__/__snapshots__/Label.spec.tsx.snap, src/app/components/Label/index.tsx, src/app/components/Label/style.tsx
=> feat: label component

src/app/components/Label/Label.tsx, src/app/components/Label/__tests__/__snapshots__/Label.spec.tsx.snap, src/app/components/Label/style.tsx
Fixes `Label` component styling (colors, shape)
=> chore: modify `Label` styling

src/__tests__/__snapshots__/index.spec.ts.snap, src/app/assets/svg/index.ts, src/app/assets/svg/voted.svg, src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.stories.tsx, src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.tsx, src/domains/transaction/components/TransferDetail/TransferDetail.stories.tsx, src/domains/transaction/components/TransferDetail/TransferDetail.tsx, src/domains/transaction/components/VoteDetail/VoteDetail.stories.tsx, src/domains/transaction/components/VoteDetail/VoteDetail.tsx, src/domains/transaction/components/VoteDetail/__tests__/VoteDetail.spec.tsx, src/domains/transaction/components/VoteDetail/__tests__/__snapshots__/VoteDetail.spec.tsx.snap, src/domains/transaction/components/VoteDetail/index.tsx, src/domains/transaction/i18n.tsx
=> feat: vote detail modal

src/app/components/TransactionListItem/TransactionListItem.tsx, src/app/components/TransactionListItem/__tests__/__snapshots__/TransactionListItem.test.tsx.snap, src/domains/dashboard/components/Transactions/Transactions.stories.tsx, src/domains/dashboard/components/Transactions/Transactions.tsx, src/domains/dashboard/components/Transactions/__tests__/Transactions.spec.tsx, src/domains/dashboard/components/Transactions/__tests__/__snapshots__/Transactions.spec.tsx.snap, src/domains/dashboard/components/Transactions/index.tsx, src/domains/dashboard/data.ts
Depends on https://github.com/ArkEcosystem/desktop-wallet/pull/2131
Add new `Transactions` list domain component in the 
dashboard page.
=> feat: add dashboard `Transactions` component

src/app/components/Slider/Slider.tsx, src/app/components/Slider/__tests__/__snapshots__/Slider.test.tsx.snap, src/app/components/Table/Table.styles.ts, src/app/components/Table/__tests__/__snapshots__/Table.test.tsx.snap, src/app/components/WalletListItem/WalletListItem.stories.tsx, src/domains/dashboard/components/FilterWallets/FilterWallets.tsx, src/domains/dashboard/components/FilterWallets/__tests__/__snapshots__/FilterWallets.test.tsx.snap, src/domains/dashboard/components/Transactions/__tests__/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/components/Wallets/__tests__/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/pages/Dashboard/Dashboard.stories.tsx, src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/dashboard/pages/Dashboard/__tests__/Dashboard.test.tsx, src/domains/dashboard/pages/Dashboard/__tests__/__snapshots__/Dashboard.test.tsx.snap, src/domains/dashboard/pages/Dashboard/index.tsx
Dashboard domain page component that includes `Wallets` and `Transactions` sections
=> feat: add `Dashboard` domain page

src/app/components/RadioButton/RadioButton.stories.tsx, src/app/components/RadioButton/RadioButton.tsx, src/app/components/RadioButton/__tests__/RadioButton.test.tsx, src/app/components/RadioButton/__tests__/__snapshots__/RadioButton.test.tsx.snap, src/app/components/RadioButton/index.ts, src/app/components/RadioButton/useRadioState.tsx
Add component to select predefined fees.
=> feat: add `RadioButton` component

src/domains/wallets/pages/CreateWallet/CreateWallet.tsx, src/domains/wallets/pages/CreateWallet/__tests__/__snapshots__/CreateWallet.test.tsx.snap
Strictly follow the design, as requested in the QA's review.
=> fix: display back button in 1st step of create wallet page

src/app/components/Checkbox/__tests__/Checkbox.test.tsx, src/app/components/Spinner/Spinner.styles.ts, src/app/components/Spinner/__tests__/Spinner.test.tsx
Updated `getColor()` function and added error boundary for tests.
=> refactor: spinner component

src/app/components/Notifications/Notifications.stories.tsx, src/app/components/Notifications/Notifications.test.tsx, src/app/components/Notifications/Notifications.tsx, src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap, src/app/components/Notifications/index.ts, src/app/components/Table/Table.tsx
Depends on https://github.com/ArkEcosystem/desktop-wallet/pull/2148
Notifications component to be used in `NavBar` as a dropdown
Lists 2 types of notifications: `Plugins` and `Transactions`
Usage:
```jsx
const plugins = [
{
logoUrl: "/static/media/ark-logo.bafd72bb.png",
logoClassName: "flex p-2 mr-4 rounded-lg bg-logo",
title: "ARK Explorer",
description: "- update v2.5.6",
action: {
label: "Update now",
value: "update",
},
},
];
const transactions = [
{
date: "17 Mar 2020 22:02:10",
avatarId: "test",
type: "receive",
address: "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
walletName: "My Wallet",
amount: "100 BTC",
fiat: "1,000,000 USD",
},
];
return (
<div>
<Notifications
pluginsHeader="Plugin 17 Feb, 2020"
plugins={plugins}
transactionsHeader="Transactions 17 Feb, 2020" …
```
=> feat: add `Notifications` component

src/domains/wallets/components/SignMessage/SignMessage.stories.tsx, src/domains/wallets/components/SignMessage/SignMessage.test.tsx, src/domains/wallets/components/SignMessage/SignMessage.tsx, src/domains/wallets/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
- Remove the list divided usage
- Improve spacings
- Adjust sizes
- Apply pattern to modal story
=> refactor: sign message modal (signed state)

src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmMultiPayment.vue
=> fix: full width on recipients list

src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.tsx, src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap, src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.tsx, src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.tsx, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap, src/domains/transaction/components/TransferDetail/TransferDetail.tsx, src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap, src/domains/transaction/components/VoteDetail/VoteDetail.tsx, src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
- Fixed positioning of the Amount icon
- Removed border of top row on Vote modal
=> refactor: details modals tweaks

src/__snapshots__/index.test.ts.snap, src/app/assets/svg/index.ts, src/app/assets/svg/ipfs.svg, src/domains/transaction/components/IpfsDetailModal/IpfsDetailModal.stories.tsx, src/domains/transaction/components/IpfsDetailModal/IpfsDetailModal.test.tsx, src/domains/transaction/components/IpfsDetailModal/IpfsDetailModal.tsx, src/domains/transaction/components/IpfsDetailModal/__snapshots__/IpfsDetailModal.test.tsx.snap, src/domains/transaction/components/IpfsDetailModal/index.tsx, src/domains/transaction/i18n.tsx
=> feat: ipfs details modal

package.json
=> chore: add html coverage reporter

src/app/components/Breadcrumbs/Breadcrumbs.stories.tsx, src/app/components/Breadcrumbs/Breadcrumbs.test.tsx, src/app/components/Breadcrumbs/Breadcrumbs.tsx, src/app/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
=> feat: add Breadcrumbs component

src/app/assets/svg/msq.svg
=> chore: simplify msq icon

.github/workflows/draft-artifacts.yml, .github/workflows/publish-release.yml, .github/workflows/test.yml, package.json
=> chore: bump version

src/app/components/Collapse/Collapse.stories.tsx, src/app/components/Collapse/Collapse.test.tsx, src/app/components/Collapse/Collapse.tsx, src/app/components/Collapse/__snapshots__/Collapse.test.tsx.snap, src/app/components/Collapse/index.ts, src/app/components/WalletListItem/WalletListItem.tsx, src/domains/wallets/components/WalletBottomSheetMenu/WalletBottomSheetMenu.stories.tsx, src/domains/wallets/components/WalletBottomSheetMenu/WalletBottomSheetMenu.test.tsx, src/domains/wallets/components/WalletBottomSheetMenu/WalletBottomSheetMenu.tsx, src/domains/wallets/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap, src/domains/wallets/components/WalletBottomSheetMenu/index.ts
Displays the list of wallets at the bottom of the page.
=> feat: add `Collapse` & `WalletBottomSheetMenu` component

src/__snapshots__/index.test.ts.snap, src/app/i18n/common/i18n.ts, src/app/i18n/helpers/index.ts, src/domains/settings/components/AdvancedMode/AdvancedMode.stories.tsx, src/domains/settings/components/AdvancedMode/AdvancedMode.test.tsx, src/domains/settings/components/AdvancedMode/AdvancedMode.tsx, src/domains/settings/components/AdvancedMode/__snapshots__/AdvancedMode.test.tsx.snap, src/domains/settings/components/AdvancedMode/index.ts, src/domains/settings/i18n.ts
=> feat: advanced mode disclaimer

src/__snapshots__/index.test.ts.snap, src/app/i18n/common/i18n.ts, src/domains/plugins/components/AddBlacklistPlugin/AddBlacklistPlugin.stories.tsx, src/domains/plugins/components/AddBlacklistPlugin/AddBlacklistPlugin.test.tsx, src/domains/plugins/components/AddBlacklistPlugin/AddBlacklistPlugin.tsx, src/domains/plugins/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap, src/domains/plugins/components/AddBlacklistPlugin/index.ts, src/domains/plugins/i18n.ts
=> feat: add blacklist plugin modal

src/domains/support/pages/Faq/Faq.stories.tsx, src/domains/support/pages/Faq/Faq.tsx, src/domains/support/pages/Faq/__snapshots__/Faq.test.tsx.snap, src/domains/support/pages/Main/Main.stories.tsx, src/domains/support/pages/Main/Main.tsx, src/domains/support/pages/Main/__snapshots__/Main.test.tsx.snap
Correct background color to neutral-100
=> fix: background color on support pages

src/domains/plugins/components/ReviewBox/ReviewBox.spec.tsx, src/domains/plugins/components/ReviewBox/ReviewBox.stories.tsx, src/domains/plugins/components/ReviewBox/ReviewBox.tsx, src/domains/plugins/components/ReviewBox/__snapshots__/ReviewBox.spec.tsx.snap, src/domains/plugins/components/ReviewBox/components/StarsCounters/StarsCounters.spec.tsx, src/domains/plugins/components/ReviewBox/components/StarsCounters/StarsCounters.stories.tsx, src/domains/plugins/components/ReviewBox/components/StarsCounters/StarsCounters.tsx, src/domains/plugins/components/ReviewBox/components/StarsCounters/__snapshots__/StarsCounters.spec.tsx.snap, src/domains/plugins/components/ReviewBox/components/StarsCounters/index.tsx, src/domains/plugins/components/ReviewBox/index.ts
- Adds the review section of the plugin details, the comments part it's gonna come separated as has their own complexity
=> feat(plugin-details): add review box component

src/styles/app.css, src/styles/coins.css
=> chore: add initial css styles for coins

src/domains/transaction/components/RecipientList/RecipientList.models.ts, src/domains/transaction/components/RecipientList/RecipientList.stories.tsx, src/domains/transaction/components/RecipientList/RecipientList.test.tsx, src/domains/transaction/components/RecipientList/RecipientList.tsx, src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap, src/domains/transaction/components/RecipientList/index.ts
Extract Recipient list as a separate components under domains/transaction.
Appears in the transaction flow, in 1st step (transaction-send form, editable with buttons) and read-only on transaction overview step.
=> feat: add `RecipientList` component

src/app/components/PercentageBar/PercentageBar.stories.tsx, src/app/components/PercentageBar/PercentageBar.test.tsx, src/app/components/PercentageBar/PercentageBar.tsx, src/app/components/PercentageBar/__snapshots__/PercentageBar.test.tsx.snap, src/app/components/PercentageBar/index.ts
Simple percentage bar to be used in Dashboard (Total portfolio).
Preview:
=> feat: add `PercentageBar` component

src/domains/plugins/components/AddBlacklistPlugin/AddBlacklistPlugin.tsx, src/domains/plugins/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap, src/domains/plugins/components/BestPlugins/BestPlugins.tsx, src/domains/plugins/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap, src/domains/plugins/components/BlacklistPlugins/BlacklistPlugins.tsx, src/domains/plugins/components/BlacklistPlugins/__snapshots__/BlacklistPlugins.test.tsx.snap, src/domains/plugins/components/FeaturedPlugins/FeaturedPlugins.tsx, src/domains/plugins/components/FeaturedPlugins/__snapshots__/FeaturedPlugins.test.tsx.snap
Fixed the width of the plugin logo, items centered on the columns and other tweaks for the components:
- `AddBlacklistPlugin`
- `BestPlugins`
- `BlacklistPlugins`
- `FeaturedPlugins`
=> fix: update plugins components

src/domains/network/components/NetworkCard/NetworkCard.stories.tsx, src/domains/network/components/NetworkCard/NetworkCard.test.tsx, src/domains/network/components/NetworkCard/NetworkCard.tsx, src/domains/network/components/NetworkCard/__snapshots__/NetworkCard.test.tsx.snap, src/domains/network/components/NetworkCard/index.ts, src/domains/network/data.ts
**Task:** https://trello.com/c/JafAGNDJ/54-my-votes
=> feat: add network card

src/app/components/LineChart/LineChart.stories.tsx, src/app/components/LineChart/LineChart.test.tsx, src/app/components/LineChart/LineChart.tsx, src/app/components/LineChart/__snapshots__/LineChart.test.tsx.snap, src/domains/dashboard/data.ts, src/domains/dashboard/pages/Dashboard/Dashboard.stories.tsx, src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx, src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Integrate Portfolio chart in dashboard.
Preview:
=> feat: integrate portfolio chart in `Dashboard`

src/domains/transaction/pages/TransactionSend/TransactionSend.tsx, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Adds the new Total Amount Box component to the Transaction overview step.
=> refactor: add `TotalAmountBox` in `TransactionSend` review step

src/domains/myvote/components/AddressList/AddressList.stories.tsx, src/domains/myvote/components/AddressList/AddressList.test.tsx, src/domains/myvote/components/AddressList/AddressList.tsx, src/domains/myvote/components/AddressList/__snapshots__/AddressList.test.tsx.snap, src/domains/myvote/components/AddressList/index.ts, src/domains/myvote/components/AddressListItem/AddressListItem.stories.tsx, src/domains/myvote/components/AddressListItem/AddressListItem.test.tsx, src/domains/myvote/components/AddressListItem/AddressListItem.tsx, src/domains/myvote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap, src/domains/myvote/components/AddressListItem/index.ts, src/domains/myvote/data.ts, src/domains/plugin/components/Comments/__snapshots__/Comments.test.tsx.snap, src/domains/plugin/components/Comments/components/Reply/__snapshots__/Reply.test.tsx.snap, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
=> feat: add address list to my votes page

src/app/components/SelectAsset/SelectAsset.stories.tsx, src/app/components/SelectAsset/SelectAsset.test.tsx, src/app/components/SelectAsset/SelectAsset.tsx, src/app/components/SelectAsset/__snapshots__/SelectAsset.test.tsx.snap, src/app/components/SelectAsset/index.ts, src/domains/plugin/components/Comments/__snapshots__/Comments.test.tsx.snap, src/domains/plugin/components/Comments/components/Reply/__snapshots__/Reply.test.tsx.snap, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
New Asset/Network selection component using autocomplete UX and typehead.
To be used in several forms for network/asset selection.
Preview:
=> feat: add `SelectAsset` component

src/app/components/Clipboard/Clipboard.stories.tsx, src/app/components/Clipboard/Clipboard.test.tsx, src/app/components/Clipboard/Clipboard.tsx, src/app/components/Clipboard/__snapshots__/Clipboard.test.tsx.snap, src/app/hooks/clipboard.ts, src/app/hooks/index.ts, src/app/hooks/use-clipboard.ts, src/domains/plugin/components/Comments/__snapshots__/Comments.test.tsx.snap, src/domains/plugin/components/Comments/components/Reply/__snapshots__/Reply.test.tsx.snap, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/transaction/pages/TransactionSendIPFS/__snapshots__/TransactionSendIPFS.spec.tsx.snap, src/domains/transaction/pages/VoteForDelegate/__snapshots__/VoteForDelegate.test.tsx.snap
Refactors the Clipboard component using the [Async Clipboard API](https://www.w3.org/TR/clipboard-apis/#async-clipboard-api) and adds the `useClipboard` hook.
=> feat: useClipboard hook

src/domains/plugin/components/Comments/__snapshots__/Comments.test.tsx.snap, src/domains/plugin/components/Comments/components/Reply/__snapshots__/Reply.test.tsx.snap, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap, src/domains/wallet/components/SearchWallet/SearchWallet.stories.tsx, src/domains/wallet/components/SearchWallet/SearchWallet.test.tsx, src/domains/wallet/components/SearchWallet/SearchWallet.tsx, src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap, src/domains/wallet/components/SearchWallet/index.ts, src/domains/wallet/components/SelectAccount/index.ts
Renames the `SelectAccount` component to `SearchWallet`.
=> chore: rename SelectAccount to SearchWallet

src/app/components/SelectAsset/SelectAsset.tsx, src/app/components/SelectAsset/__snapshots__/SelectAsset.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.stories.tsx, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/TransactionSend/TransactionSend.stories.tsx, src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Use the new Select Asset component in Transaction Send form and page.
=> feat: add `SelectAsset` in send transaction form

src/app/assets/svg/index.ts, src/app/assets/svg/placeholder.svg, src/app/components/NavigationBar/NavigationBar.stories.tsx, src/app/components/NavigationBar/NavigationBar.styles.ts, src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, src/app/components/Notifications/Notifications.stories.tsx, src/app/components/Notifications/Notifications.tsx, src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap, src/app/components/Notifications/models.ts
=> feat: add empty placeholder for `Notifications`

src/renderer/store/modules/peer/index.js
=> fix: stuck loading screen on fresh wallet

src/app/components/Notifications/Notifications.tsx, src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap, src/domains/plugin/components/Comments/__snapshots__/Comments.test.tsx.snap, src/domains/plugin/components/Comments/components/Reply/__snapshots__/Reply.test.tsx.snap, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap, src/domains/wallet/pages/WalletDetails/WalletDetails.stories.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.tsx, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
=> feat: add `WalletDetails` page

src/domains/plugin/pages/PluginManager/PluginManager.test.tsx, src/domains/transaction/components/LinkCollection/LinkCollection.tsx
Needs https://github.com/ArkEcosystem/desktop-wallet/pull/2295
Resolves all errors that occur when running tests.
=> fix: resolve all errors and warnings during tests

src/app/components/Button/Button.test.tsx, src/app/components/Button/__snapshots__/Button.test.tsx.snap, src/app/components/Input/InputGroup.test.tsx, src/app/components/Input/__snapshots__/InputGroup.test.tsx.snap, src/domains/contact/components/ContactForm/ContactForm.test.tsx, src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap, src/domains/contact/components/ContactListItem/ContactListItem.test.tsx, src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap, src/domains/transaction/components/LinkCollection/LinkCollection.test.tsx, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap, src/domains/transaction/components/LinkList/LinkList.test.tsx, src/domains/transaction/components/LinkList/__snapshots__/LinkList.test.tsx.snap, src/domains/transaction/pages/Registration/Registration.test.tsx, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.test.tsx, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
=> fix: test snapshot fragment usage

src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx, src/domains/transaction/pages/Registration/Registration.tsx, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/ResignRegistration/ResignRegistration.stories.tsx, src/domains/transaction/pages/ResignRegistration/ResignRegistration.test.tsx, src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx, src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap, src/domains/transaction/pages/ResignRegistration/index.ts, src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap, src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
=> feat: resign registration page

.storybook/main.js, .storybook/preview.js, package.json, yarn.lock
Adds the `storybook-addon-themes` package which allows selecting a theme in the storybook.
=> chore: add theme selection to stories

src/domains/transaction/components/SendTransactionForm/SendTransactionForm.styles.ts, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Minor fix for the send/recipient select lists in `TransactionSend` form . Correction of width and chevron icon removal.
Broke after recent changes.
=> chore: fix select ui in transaction send form

src/app/components/Avatar/Avatar.stories.tsx, src/app/components/Avatar/Avatar.test.tsx, src/app/components/Avatar/Avatar.tsx, src/app/components/Avatar/__snapshots__/Avatar.test.tsx.snap, src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap, src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap, src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap, src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap, src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap, src/domains/vote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap, src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap, src/domains/vote/components/DelegateListItem/__snapshots__/DelegateListItem.test.tsx.snap, src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap, src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap, src/domains/wallet/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap, src/domains/wallet/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Changing to svg instead of css to reflect changes in sdk.
=> refactor: update `Avatar` component to use svg

src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx, src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
Apply design UI guidelines on ResignRegistration modal page.
=> refactor: styleguide rules on `ResignRegistration`

src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.stories.tsx, src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx, src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
Apply design UI guidelines on SendVoteTransaction modal page.
=> refactor: styleguide rules on `SendVoteTransaction` page

src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.stories.tsx, src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx, src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
Apply design UI guidelines on Send IPFS Transaction  modal page.
=> refactor: styleguide rules on `SendIPFSTransaction` page

src/domains/transaction/pages/Registration/Registration.tsx, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
Depends on https://github.com/ArkEcosystem/desktop-wallet/pull/2323
Apply design UI guidelines on Registration modal page.
=> refactor: styleguide rules on `Registration`

src/domains/transaction/components/LinkCollection/LinkCollection.tsx, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap, src/domains/transaction/components/LinkList/LinkList.tsx, src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx, src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
Apply design UI guidelines on UpdateRegistration transaction modal page.
=> refactor: styleguide rules on `UpdateRegistration`

src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
=> fix: ark uri scheme

src/app/components/Breadcrumbs/Breadcrumbs.test.tsx, src/app/components/Breadcrumbs/Breadcrumbs.tsx, src/app/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap, src/app/components/Divider/Divider.styles.ts, src/app/components/Divider/Divider.tsx, src/app/components/Divider/__snapshots__/Divider.test.tsx.snap, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/plugin/components/PluginManagerControls/__snapshots__/PluginManagerControls.test.tsx.snap, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap, src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
- Add `ArrowBack` icon
- Add `Divider` component
=> refactor: breadcrumbs component ui adjustments

src/app/components/SearchBar/SearchBarOptions/SearchBarOptions.tsx, src/app/components/SearchBar/SearchBarOptions/__snapshots__/SearchBarOptions.test.tsx.snap, src/domains/help/components/ContactUs/ContactUs.tsx, src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap, src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
Apply minor styleguide UI changes on `ContactUs` and `SearchHelp` modals.
=> refactor: styleguide rules on help pages

src/domains/transaction/pages/Registration/Registration.tsx, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx, src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
=>  refactor: style guide padding on registration pages

src/app/components/SearchBar/SearchBar.tsx, src/app/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap, src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap, src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap, src/domains/plugin/components/InstallPlugin/InstallPlugin.tsx, src/domains/plugin/components/InstallPlugin/__snapshots__/InstallPlugin.test.tsx.snap, src/domains/transaction/components/SelectDelegate/__snapshots__/SelectDelegate.test.tsx.snap
Minor UI fixes on the `Searchbar` icon placement and `InstallPlugin` modal
=> refactor: apply ui guidelines on plugin domain modals

src/domains/setting/components/AdvancedMode/AdvancedMode.tsx, src/domains/setting/components/AdvancedMode/__snapshots__/AdvancedMode.test.tsx.snap, src/domains/setting/components/CustomPeers/CustomPeers.stories.tsx, src/domains/setting/components/CustomPeers/CustomPeers.tsx, src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap, src/domains/setting/components/PeerList/PeerList.stories.tsx, src/domains/setting/components/PeerList/PeerList.tsx, src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
* Apply design UI guidelines on `AdvanceMode` and `CustomPeers` modals
* Update Select Network field to `SelectAsset`
=> refactor: apply ui guidelines on `Setting` modals

src/domains/help/pages/Article/Article.tsx, src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap, src/domains/help/pages/Faq/Faq.tsx, src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap, src/domains/help/pages/Main/Main.tsx, src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
Minor font size adjustments on help pages.
=> fix: help pages ui adjustments

src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx, src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap, src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx, src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/transaction/pages/TransactionSend/TransactionSend.tsx, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/vote/components/SendVoteTransaction/SendVoteTransaction.stories.tsx, src/domains/vote/components/SendVoteTransaction/SendVoteTransaction.tsx, src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/wallet/pages/CreateWallet/CreateWallet.tsx, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap, src/domains/wallet/pages/ImportWallet/ImportWallet.tsx, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
=> refactor: add padding above steps

src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx, src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Remove `NavigationBar` shadow on top of `PluginManagerNavigationBar`
=> chore: correct z-index in `PluginManagerNavigationBar`

src/app/components/Header/Header.tsx, src/app/components/Header/__snapshots__/Header.test.tsx.snap, src/domains/contact/pages/Contacts/Contacts.tsx, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap, src/domains/help/pages/Faq/Faq.tsx, src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap, src/domains/help/pages/Main/Main.tsx, src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap, src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx, src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/vote/pages/Votes/Votes.tsx, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
Includes minor changes on padding and alignment on the header component along with the affected pages.
* Refactor `Header` component based on UI styleguide
Affected pages using the `Header`:
* Help pages
* Vote
* MyRegistrations
* Contact
=> refactor: apply header ui guidelines on pages

src/domains/exchange/pages/Exchange/Exchange.tsx, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
Use `Header` component on `Exchange` page to comply with UI guideline rules.
=> refactor: apply header ui guidelines on `Exchange` page

src/domains/wallet/components/VerifyMessage/VerifyMessage.tsx, src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
=> refactor: apply style guide to verify message

src/app/assets/svg/redirect.svg, src/app/components/Icon/Icon.tsx, src/app/components/Link/Link.stories.tsx, src/app/components/Link/Link.test.tsx, src/app/components/Link/Link.tsx, src/app/components/Link/__snapshots__/Link.test.tsx.snap, src/app/components/Link/index.ts, src/domains/profile/pages/MyRegistrations/components/RepositoryModal/__snapshots__/RepositoryModal.test.tsx.snap, src/domains/profile/pages/MyRegistrations/components/RepositoryModal/components/RepositoryLink/__snapshots__/RepositoryLink.test.tsx.snap
=> feat: add custom `Link` component

src/domains/contact/pages/Contacts/Contacts.tsx, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
=> chore: fix no contacts banner

src/app/components/Select/Select.stories.tsx, src/app/components/SelectDropdown/SelectDropdown.stories.tsx, src/app/components/SelectDropdown/SelectDropdown.test.tsx, src/app/components/SelectDropdown/SelectDropdown.tsx, src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap, src/app/components/SelectDropdown/styles.ts, src/domains/transaction/components/LinkCollection/LinkCollection.test.tsx, src/domains/transaction/components/LinkCollection/LinkCollection.tsx, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
Refactor `SelectDropdown` to replace native `Select` component in app.
* Apply UI guidelines,
* Refactor as form component with ARIA and form input events.
* Adjust existing integration n `LinkCollection` component
Preview:
Usage: 
```jsx
const options = [
{
label: "Option 1",
value: "1",
},
{
label: "Option 2",
value: "2",
},
{
label: "Option 3",
value: "3",
},
];
return (
<div>
<Select placeholder="Select option" options={options} />
<Select placeholder="Invalid" isInvalid options={options} />
<Select placeholder="Disabled" disabled options={options} />
<div className="mt-4">With default value</div>
<Select placeholder="Disabled" options={options} defaultValue="3" />
<div className="mt-4">With default value (disabled)</div>
<Select placeholder="Disabled" disabled options={options} …
```
=> refactor: ux and styleguide adjustments on `SelectDropdown`

src/app/components/Form/Form.stories.tsx, src/domains/help/components/ContactUs/ContactUs.tsx, src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap, src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/setting/pages/Settings/available-settings/General.tsx, src/domains/setting/pages/Settings/available-settings/Plugins.tsx, src/domains/transaction/pages/Registration/Registration.test.tsx, src/domains/transaction/pages/Registration/Registration.tsx, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
Depends on https://github.com/ArkEcosystem/desktop-wallet/pull/2368
Replace native `Select` list component with `SelectDropdown` in all pages:
* `ContactUs`
* `CreateProfile`
* `Registration`
* `Settings`
=> refactor: replace select list in pages

src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
UI fixes and styleguide adjustments on `CreateProfile` page
=> fix: `CreateProfile` ui adjustments

src/app/components/Header/HeaderSearchBar/HeaderSearchBar.test.tsx, src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx, src/app/components/Header/HeaderSearchBar/__snapshots__/HeaderSearchBar.test.tsx.snap, src/domains/contact/pages/Contacts/Contacts.tsx, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap, src/domains/plugin/pages/PluginManager/PluginManager.tsx, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
* Modify search input UI with absolute positioning.
* Optional `Search` label (defaults to `Search`)
* Fix header button spacing in `Contact` page
* Use `Header` component in `PluginManager` page
=> refactor: ui adjustments on `HeaderSearchBar`

src/app/components/SelectDropdown/SelectDropdown.tsx, src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap, src/app/components/SelectDropdown/styles.ts, src/domains/help/components/ContactUs/ContactUs.tsx, src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/setting/pages/Settings/available-settings/General.tsx, src/domains/transaction/components/LinkCollection/LinkCollection.tsx, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
* Use `useFormField` context to get `isInvalid` state of select 
* Increase width of select list in `LinkCollection` to fit dropdown content.
Invalid state preview in `ContactUs`:
LinkCollection preview:
=> chore: select list ux adjustments

src/domains/contact/pages/Contacts/Contacts.tsx, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap, src/domains/exchange/pages/Exchange/Exchange.tsx, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
Fix banner spacing in `Contacts` and `Exchange` pages
=> chore: banner alignment fix

src/domains/wallet/pages/ImportWallet/ImportWallet.stories.tsx, src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx, src/domains/wallet/pages/ImportWallet/ImportWallet.tsx, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
* Use `SelectAsset` component in `ImportWallet` page
* Apply styleguide rules on `ImportWallet` page
=> refactor: select asset in import wallet

src/app/i18n/common/i18n.ts, src/domains/contact/components/ContactListItem/ContactListItem.tsx
Adds tooltips to the icons shown in the contact lists "Account Type" column.
=> chore: add tooltips to ContactListItem

src/app/__snapshots__/index.test.tsx.snap, src/app/components/Header/Header.tsx, src/app/components/Header/__snapshots__/Header.test.tsx.snap, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap, src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap, src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap, src/domains/profile/pages/Welcome/Welcome.tsx, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap, src/styles/headings.css
Changes the font weight of `h1` to `bold` as specified in the style guide.
=> chore: adjust h1 font weight

src/app/components/Toggle/Toggle.tsx, src/app/components/Toggle/__snapshots__/Toggle.test.tsx.snap, src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap, src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
=> refactor: reduce `Toggle` switch size

src/app/components/Input/InputPassword.tsx, src/app/components/Input/__snapshots__/InputPassword.test.tsx.snap, src/domains/profile/components/ProfileCard/ProfileCard.tsx, src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap, src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap, src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap, src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap, src/domains/wallet/pages/ImportWallet/ImportWallet.stories.tsx, src/domains/wallet/pages/ImportWallet/ImportWallet.tsx, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
* Fix `InputPassword` eye overlapping focused border-2
* Correct steps width in `ImportWallet`
* Correct `ProfileCard` dropdown toggle icon color
=> chore: ui fixes

src/app/components/Button/Button.stories.tsx, src/app/components/Button/Button.tsx, src/types.d.ts
=> refactor: add `ButtonVariant` constraint

src/domains/vote/components/SendVoteTransaction/SendVoteTransaction.tsx, src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/vote/components/VoteList/VoteList.tsx, src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
Adjust fonts and spacing in `SendVoteTransaction` component that appears in Domains / Vote.
=> refactor: apply ui guidelines in `SendVoteTransaction`

src/app/components/TransactionDetail/TransactionDetail.tsx, src/domains/vote/components/SendVoteTransaction/SendVoteTransaction.tsx, src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
* Extend `TransactionDetail` label prop to accept any type (e.g jsx)
* Adjust Vote list UI
=> refactor: send vote tx ui adjustments

__tests__/unit/components/Transaction/TransactionForm/TransactionFormTransfer.spec.js, src/renderer/components/Input/InputFee.vue, src/renderer/components/Input/InputToggle/InputToggleChoice.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue, src/renderer/i18n/locales/en-US.js, src/renderer/styles/_theme.css, tailwind.js
=> refactor: transfer multipayment ux

.github/workflows/draft-artifacts.yml, .github/workflows/publish-release.yml, .github/workflows/test.yml, package.json
=> chore: version 2.9.3

src/domains/exchange/pages/Exchange/Exchange.tsx, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
Removes the duplicate exchange banner.
=> fix: remove duplicate exchange banner

src/app/components/Badge/Badge.styles.ts, src/app/components/Badge/__snapshots__/Badge.test.tsx.snap, src/app/components/FilterNetwork/__snapshots__/FilterNetwork.test.tsx.snap, src/app/components/Layout/__snapshots__/Layout.test.tsx.snap, src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap, src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
Fixes the `Badge` component so that it works also in Dark Mode. This still requires the Badge to be placed on a parent with the background color set to the theme background. Custom background color will require further changes, but there is no such badge yet.
=> fix: dynamic badge shadow

src/domains/news/components/AddAssets/AddAssets.stories.tsx, src/domains/news/components/AddAssets/AddAssets.test.tsx, src/domains/news/components/AddAssets/AddAssets.tsx, src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap, src/domains/news/components/AddAssets/index.tsx
=> feat: add `AddAssets` modal

src/domains/news/components/AddAssets/AddAssets.tsx, src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
Reduces the left margin of the last asset to match the design.
=> chore: adjust margin of last asset

src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap, src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap, src/domains/exchange/components/ExchangeCard/__snapshots__/ExchangeCard.test.tsx.snap, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap, src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap, src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap, src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/tailwind.config.js
Fixes shadow surroundings and colors. Used in components like `HeaderSearchBar`
=> chore: fix shadow in `xl`

src/app/components/LayoutControls/LayoutControls.tsx, src/app/components/LayoutControls/__snapshots__/LayoutControls.test.tsx.snap, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/plugin/components/PluginManagerControls/__snapshots__/PluginManagerControls.test.tsx.snap, src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx, src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap, src/domains/plugin/pages/PluginManager/PluginManager.stories.tsx, src/domains/plugin/pages/PluginManager/PluginManager.test.tsx, src/domains/plugin/pages/PluginManager/PluginManager.tsx, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/plugin/pages/PluginsCategory/PluginsCategory.tsx, src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
Simplify `PluginManager` page and ux after latest design updates:
* Remove modals for `Featured plugins` and `Top rated` plugins
* Replace `PluginManagerControls` with `LayoutControls` buttons
* Fix: open modal on `Install plugin` click in header
=> refactor: ui adjustments in `PluginManager`

cypress/integration/navbar-routing.spec.js, src/domains/news/pages/News/News.tsx, src/domains/news/pages/News/__snapshots__/News.test.tsx.snap, src/domains/news/pages/index.ts, src/domains/news/routing.ts, src/router/index.tsx
Depends on #2413 
Add news routing, fix page margins, adjust breadcrumb position
=> feat: add news routing

src/app/components/Notifications/Notifications.stories.tsx, src/app/components/SearchResource/SearchResource.tsx, src/app/components/TextArea/TextArea.tsx, src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.tsx, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.stories.tsx, src/domains/transaction/pages/Registration/Registration.tsx, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx, src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap, src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap, src/domains/vote/components/AddressListItem/AddressListItem.tsx, src/domains/vote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap, src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap, src/domains/vote/components/DelegateListItem/DelegateListItem.tsx, src/domains/vote/components/DelegateListItem/__snapshots__/DelegateListItem.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap, src/domains/wallet/components/ReceiveFunds/ReceiveFunds.tsx, src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
Updated some places in the code to remove warns from the Storybook.
=> fix: remove storybook warns

src/domains/transaction/components/AddRecipient/AddRecipient.stories.tsx, src/domains/transaction/components/AddRecipient/AddRecipient.styles.ts, src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx, src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap, src/domains/transaction/components/AddRecipient/index.ts, src/domains/transaction/components/RecipientList/RecipientList.models.ts, src/domains/transaction/components/RecipientList/RecipientList.styles.ts, src/domains/transaction/components/RecipientList/RecipientList.tsx, src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
* Create separate `AddRecipient` component based on new designs
* Modify affected `RecipientList` and `RecipientListItem` components
Preview:
Usage: 
```jsx
const recipients = [
{
address: "FJKDSALJFKASLJFKSDAJD333FKFKDSAJFKSAJFKLASJKDFJ",
walletName: "Recipient 1",
amount: "100",
assetSymbol: "ARK",
},
{
address: "AhFJKDSALJFKASLJFKSDEAJ333FKFKDSAJFKSAJFKLASJKDFJ",
walletName: "Recipient 2",
isMultisig: true,
amount: "100",
assetSymbol: "ARK",
},
];
<AddRecipient assetSymbol="ARK" maxAvailableAmount={80} availableAmount={0} recipients={recipients} />
```
=> feat: create `AddRecipient`

src/domains/transaction/components/AddRecipient/AddRecipient.stories.tsx, src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx, src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
* Integrate `SelectAddress` component in `AddRecipient`.
* UX includes modal opening to select recipients from contacts
* Adjust modal title and description to match context
Preview:
=> feat: add `SelectAddress` component in `AddRecipient`

src/app/components/DeleteResource/DeleteResource.stories.tsx, src/app/components/DeleteResource/DeleteResource.test.tsx, src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap
=> feat: add story for the `DeleteResource` component

src/app/components/SearchResource/SearchResource.stories.tsx, src/app/components/SearchResource/SearchResource.test.tsx, src/app/components/SearchResource/__snapshots__/SearchResource.test.tsx.snap
=> feat: add story and tests for the `SearchResource` component

src/domains/setting/components/PeerList/PeerList.tsx, src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap, src/domains/setting/pages/Settings/available-settings/Peer.tsx
=> chore: add networks to peer list

src/app/__snapshots__/App.test.tsx.snap, src/app/assets/svg/index.ts, src/app/assets/svg/questionmark.svg, src/domains/profile/components/SelectAddress/SelectAddress.tsx, src/domains/transaction/components/AddRecipient/AddRecipient.models.ts, src/domains/transaction/components/AddRecipient/AddRecipient.styles.ts, src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx, src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap, src/domains/transaction/components/RecipientList/RecipientList.tsx, src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.stories.tsx, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/TransactionSend/TransactionSend.stories.tsx, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Integrate `AddRecipients` form group in transaction-send form and page.
=> refactor: integrate `AddRecipient` in `SendTransaction`

src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx, src/domains/wallet/components/MnemonicVerification/MnemonicVerification.test.tsx, src/domains/wallet/components/MnemonicVerification/MnemonicVerification.tsx
Fix testing errors:
```bash
src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
console.error node_modules/react-dom/cjs/react-dom-test-utils.development.js:87
Warning: The callback passed to act(...) function must return undefined, or a Promise. You returned true
```
```bash
src/domains/wallet/components/MnemonicVerification/MnemonicVerification.test.tsx
console.error node_modules/react-dom/cjs/react-dom.development.js:88
Warning: Encountered two children with the same key, `7`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
in div (at MnemonicVerification.tsx:60)
in div (at Tabs.tsx:29)
in Tabs (at …
```
=> fix: test errors

src/app/components/Dropdown/Dropdown.tsx
Prevent event emission when a `Dropdown` option is clicked.
Prevents unwanted redirecting when clicking dropdown options inside `Links` (e.g `WalletCards` in dashboard)
=> fix: dropdown options events

src/domains/profile/components/SelectAddress/SelectAddress.tsx, src/domains/profile/components/SelectAddress/__snapshots__/SelectAddress.test.tsx.snap, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/Registration/Registration.stories.tsx, src/domains/transaction/pages/Registration/Registration.tsx, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
* Replace native select list for Address field with `SelectAddress` component
* Fix `AddressField` button to prevent unwanted form submissions
=> refactor: registration select address

src/app/components/Slider/Slider.tsx, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
Fix wallet card alignment when in 1 row in dashboard
=> fix: wallets slider ui adjustments

src/app/components/SearchBar/SearchBar.tsx, src/app/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap, src/app/components/SearchResource/__snapshots__/SearchResource.test.tsx.snap, src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap, src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap, src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap, src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
=> fix: correct `SearchBar` font size

src/app/components/ListDivided/ListDivided.tsx, src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
=> refactor: `CreateProfile` page ui adjustments

src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Adjust label size and type in `AddRecipient`
=> chore: fix typography in `AddRecipient` form group

src/domains/profile/components/SearchAddress/SearchAddress.stories.tsx, src/domains/profile/components/SearchAddress/SearchAddress.test.tsx, src/domains/profile/components/SearchAddress/SearchAddress.tsx, src/domains/profile/components/SearchAddress/__snapshots__/SearchAddress.test.tsx.snap, src/domains/profile/components/SearchAddress/index.ts, src/domains/profile/i18n.ts
Search Address modal to be used in Transaction/Registration forms.
Usage: 
```jsx
<SearchAddress
isOpen={true}
wallets={wallets}
onClose={action("onClose")}
onAction={console.log}
/>
```
=> feat: create `SearchAddress` modal

src/domains/profile/components/SelectAddress/SelectAddress.stories.tsx, src/domains/profile/components/SelectAddress/SelectAddress.test.tsx, src/domains/profile/components/SelectAddress/SelectAddress.tsx, src/domains/profile/components/SelectAddress/__snapshots__/SelectAddress.test.tsx.snap, src/domains/profile/components/SelectRecipient/SelectRecipient.test.tsx, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.stories.tsx, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/Registration/Registration.stories.tsx, src/domains/transaction/pages/Registration/Registration.tsx, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/TransactionSend/TransactionSend.stories.tsx, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Depends on https://github.com/ArkEcosystem/desktop-wallet/pull/2487
Use new `SearchAddress` modal component to select sender addresses in Transaction and Registration forms.
=> refactor: integrate sender modal in transaction forms

src/domains/transaction/components/LinkCollection/LinkCollection.stories.tsx, src/domains/transaction/components/LinkCollection/LinkCollection.tsx, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap, src/domains/transaction/components/LinkList/LinkList.tsx, src/domains/transaction/components/LinkList/__snapshots__/LinkList.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
Fixes the vertical alignment of the chevron in the `LinkCollection` and `LinkList` components.
=> refactor: vertically align chevron in LinkCollection and LinkList

src/domains/transaction/components/AddRecipient/AddRecipient.styles.ts, src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Small adjustments in the margins and paddings of the `AddRecipient` component to fit the designs.
=> refactor: fix spacing in AddRecipient component

src/app/components/SelectionBar/SelectionBar.tsx, src/app/components/SelectionBar/__snapshots__/SelectionBar.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap, src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap, src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap, src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
Fix selection bar UI (correct misalignment, remove shadows & fix size).
=> fix: `SelectionBar` ui adjustments

cypress/integration/wallet-details.spec.js, src/app/components/DeleteResource/DeleteResource.tsx, src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap, src/domains/contact/components/DeleteContact/__snapshots__/DeleteContact.test.tsx.snap, src/domains/wallet/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap, src/domains/wallet/components/WalletHeader/WalletHeader.stories.tsx, src/domains/wallet/components/WalletHeader/WalletHeader.test.tsx, src/domains/wallet/components/WalletHeader/WalletHeader.tsx, src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap, src/domains/wallet/pages/CreateWallet/CreateWallet.stories.tsx, src/domains/wallet/pages/ImportWallet/ImportWallet.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.tsx, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Task: https://trello.com/c/AxX0IGLN/107-implement-wallet-deleting
=> feat: implement wallet deleting

cypress/integration/wallet-create.spec.js, src/domains/wallet/components/MnemonicVerification/MnemonicVerification.tsx, src/domains/wallet/pages/CreateWallet/CreateWallet.stories.tsx, src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx, src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
=> fix: create wallet back and forth ux

src/app/components/DeleteResource/DeleteResource.tsx, src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap, src/app/i18n/common/i18n.ts, src/domains/contact/components/DeleteContact/DeleteContact.stories.tsx, src/domains/contact/components/DeleteContact/DeleteContact.test.tsx, src/domains/contact/components/DeleteContact/DeleteContact.tsx, src/domains/contact/components/DeleteContact/__snapshots__/DeleteContact.test.tsx.snap, src/domains/contact/pages/Contacts/Contacts.test.tsx, src/domains/contact/pages/Contacts/Contacts.tsx, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap, src/domains/wallet/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap
https://trello.com/c/ORhQrO9o/110-implement-contact-deleting
* Add implementation for contact deletion in `DeleteContact` standalone component
* Add functionality for contact deletion in `Contacts` page.
=> feat: implement contact deletion

src/domains/wallet/e2e/import-wallet-action.e2e.js
=> test(e2e): add tests to import a wallet using mnemonic or address

src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/data.ts, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/wallet/e2e/delete-wallet-action.e2e.js, src/domains/wallet/pages/WalletDetails/WalletDetails.stories.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.tsx, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Refactor wallet deletion functionality, add e2e tests for deletion.
https://trello.com/c/ORhQrO9o/110-implement-contact-deleting
=> refactor: wallet deletion improvements and tests

src/app/components/Table/Table.tsx, src/app/components/Table/__snapshots__/Table.test.tsx.snap, src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap, src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap, src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap, src/domains/plugin/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap, src/domains/plugin/components/BlacklistPlugins/__snapshots__/BlacklistPlugins.test.tsx.snap, src/domains/plugin/components/FeaturedPlugins/__snapshots__/FeaturedPlugins.test.tsx.snap, src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap, src/domains/profile/components/SearchAddress/__snapshots__/SearchAddress.test.tsx.snap, src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap, src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap, src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap, src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap, src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap, src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap, src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap, src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap, src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap, src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap, src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Use empty string when column className is not provided.
Removes 'undefined` class names.
=> chore: fix table classes

.storybook/main.js
- Remove unnecessary console log (forgot there, my bad xD)
=> chore(debug): remove lost console log

src/app/i18n/common/i18n.ts, src/domains/wallet/e2e/update-wallet-name-action.e2e.ts
Cover wallet labeling e2e test cases.
https://trello.com/c/eFH4R4wH/106-implement-wallet-labeling
=> test: update wallet name tests

src/domains/profile/components/DeleteProfile/DeleteProfile.test.tsx, src/domains/profile/components/DeleteProfile/DeleteProfile.tsx, src/domains/profile/components/DeleteProfile/__snapshots__/DeleteProfile.test.tsx.snap, src/domains/profile/e2e/delete-profile-action.e2e.ts, src/domains/profile/i18n.ts, src/domains/profile/pages/Welcome/Welcome.test.tsx, src/domains/profile/pages/Welcome/Welcome.tsx
Delete profile on Welcome page.
=> feat: implement profile deleting

src/app/components/WalletCard/WalletCard.tsx, src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap, src/domains/dashboard/components/Wallets/Wallets.tsx, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/data.ts, src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Adjusts the positioning and vertical alignment of the wallet card icons and fixes the wallet table on the dashboard.
=> refactor: adjust vertical alignment and wallet table fix on dashboard

src/domains/wallet/e2e/import-wallet-action.e2e.ts
This PR fixes the network mock.
=> test: fix NEO mock e2e tests

src/app/components/Form/SubForm.test.tsx, src/app/components/Form/SubForm.tsx, src/app/components/Form/__snapshots__/SubForm.test.tsx.snap, src/app/components/Form/index.tsx, src/domains/contact/components/ContactForm/ContactForm.tsx, src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap, src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap, src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap, src/domains/transaction/components/AddRecipient/AddRecipient.styles.ts, src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx, src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Adds a `SubForm` component to wrap/group form fields with a different background.
=> refactor: add sub form wrapper component

package.json, public/electron.js, src/electron/index.js
- Disable react devtools in e2e environment
=> chore: disable devtools in e2e

src/domains/wallet/components/UpdateWalletName/UpdateWalletName.tsx, src/domains/wallet/e2e/update-wallet-name-action.e2e.ts
Persist wallet name after form save.
Part of https://trello.com/c/eFH4R4wH/106-implement-wallet-labeling
=> fix: wallet labeling issues

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/format.yml, .github/workflows/test.yml
Update system repositories before installing any additional packages on linux.
=> ci: always update before installing new packages

src/domains/wallet/components/WalletRegistrations/WalletRegistrations.tsx, src/domains/wallet/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Fix Registrations icons alignment in WalletsDetails page (remove left offset)
=> chore: fix registrations icons

src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap, src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap, src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap, src/domains/network/data.ts, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
=> chore: temporarily remove eth network data

src/app/components/Form/Form.stories.tsx, src/app/components/Form/FormLabel.tsx, src/app/components/Form/__snapshots__/FormLabel.test.tsx.snap, src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap, src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap, src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap, src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap, src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap, src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/Registration/Registration.tsx, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap, src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap, src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap, src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap, src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
=> refactor: show required field icon by default

src/app/App.test.tsx, src/app/App.tsx, src/app/__snapshots__/App.test.tsx.snap, src/app/hooks/index.ts, src/app/hooks/network-status.test.tsx, src/app/hooks/network-status.ts, src/domains/splash/e2e/splash-screen.e2e.ts
Task: https://trello.com/c/epOKV1z0/177-implement-offline-splashscreen
=> feat: implement offline splashscreen

src/app/components/Input/InputAddress.test.tsx, src/app/components/Input/InputAddress.tsx, src/app/i18n/common/i18n.ts, src/domains/wallet/e2e/import-wallet-action.e2e.ts, src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx, src/domains/wallet/pages/ImportWallet/ImportWallet.tsx, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
=> feat: add validation for duplicate address

src/app/components/WalletCard/WalletCard.tsx, src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap, src/app/components/WalletListItem/WalletListItem.tsx, src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap, src/app/services/HttpClient.ts, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx, src/domains/transaction/pages/TransactionSend/TransactionSend.tsx, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap, src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
=> fix: transaction send functionality tests

src/utils/electron-utils.test.ts, src/utils/electron-utils.ts
Reference: https://www.electronjs.org/docs/api/shell#shell
=> feat: add electron util to open external links

src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap, src/app/components/SelectDropdown/styles.ts, src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
=> chore: fix `Dropdown` scrollbar

src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/TransactionSend/TransactionSend.tsx, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
=> refactor: generalise send transaction form component

src/domains/transaction/pages/TransactionSend/TransactionSend.tsx, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
https://app.clickup.com/t/78ueww
=> fix: extra padding for smartbridge field to avoid max hint overlap

src/domains/dashboard/components/Transactions/Transactions.tsx, src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/transaction/components/IpfsDetail/IpfsDetail.tsx, src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.stories.tsx, src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx, src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx, src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap, src/domains/transaction/components/VoteDetail/VoteDetail.test.tsx, src/domains/transaction/components/VoteDetail/VoteDetail.tsx, src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
- Refactor to add vote details real data from tx
- Start basic delegates sync
=> refactor: detail modal vote

src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/setting/pages/Settings/available-settings/General.tsx
https://app.clickup.com/t/7eu4ef
=> refactor: change avatar button color on hover

src/app/components/Input/InputAddress.tsx, src/app/components/Input/InputPassword.tsx, src/app/components/Input/__snapshots__/InputAddress.test.tsx.snap, src/app/components/Input/__snapshots__/InputPassword.test.tsx.snap, src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap, src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap, src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap, src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap, src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap, src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap, src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
https://app.clickup.com/t/7gq1aj
=> chore: remove background color from InputAddonEnd

src/domains/profile/components/SignIn/SignIn.test.tsx
=> test: await input change in sign in test

src/app/components/NavigationBar/NavigationBar.test.tsx, src/app/components/NavigationBar/NavigationBar.tsx, src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap, src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap, src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap, src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap, src/domains/news/pages/News/__snapshots__/News.test.tsx.snap, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap, src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap, src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap, src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
https://app.clickup.com/t/7jukqx
=> refactor: adjust navbar styles

src/app/components/Circle/Circle.styles.ts, src/app/components/Circle/Circle.tsx, src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.test.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientIcon.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRowRecipientIcon.test.tsx.snap, src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
https://app.clickup.com/t/7jukux
=> fix: dynamic Circle shadow color

src/domains/transaction/components/VoteDetail/VoteDetail.test.tsx, src/domains/transaction/components/VoteDetail/VoteDetail.tsx, src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
=> fix: `VoteDetails` test errors

src/domains/wallet/components/WalletHeader/WalletHeader.tsx, src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
https://app.clickup.com/t/7mqx43
=> chore: set balance/fiat font weight to semibold

src/app/App.tsx
https://app.clickup.com/t/7mr555
=> refactor: scroll restoration upon route change

src/app/__snapshots__/App.test.tsx.snap, src/app/components/Toggle/Toggle.tsx, src/app/components/Toggle/__snapshots__/Toggle.test.tsx.snap, src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap, src/domains/wallet/components/WalletHeader/WalletHeader.tsx, src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
https://app.clickup.com/t/7mqwdq
=> refactor: add baseColor prop to toggle

src/app/i18n/common/i18n.ts, src/domains/wallet/components/UpdateWalletName/UpdateWalletName.test.tsx, src/domains/wallet/components/UpdateWalletName/UpdateWalletName.tsx, src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap, src/domains/wallet/e2e/update-wallet-name-action.e2e.ts, src/domains/wallet/i18n.ts, src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.tsx, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
https://app.clickup.com/t/7mvu7g
=> fix: allow setting an empty wallet name

src/app/components/Dropdown/Dropdown.tsx, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/components/WalletsControls/WalletsControls.tsx, src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
https://app.clickup.com/t/7pq8a4
=> chore: adjust font sizes in dropdown and card control

src/app/components/SideBar/SideBarItem/SideBarItem.tsx, src/app/components/SideBar/SideBarItem/__snapshots__/SideBarItem.test.tsx.snap, src/app/components/SideBar/__snapshots__/SideBar.test.tsx.snap, src/domains/plugin/e2e/plugins-routing.e2e.ts, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
https://app.clickup.com/t/7pu546
=> style: add explicit height to SideBarItem

src/app/components/Badge/Badge.tsx, src/app/components/Dropdown/Dropdown.styles.ts, src/app/components/Dropdown/Dropdown.tsx, src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/plugin/e2e/plugins-routing.e2e.ts, src/types.d.ts
Adds a `Position` type declaration and slightly changes how a dropdowns content is nested.
=> refactor: add position type and nests dropdown content

src/domains/wallet/components/WalletHeader/WalletHeader.stories.tsx, src/domains/wallet/components/WalletHeader/WalletHeader.test.tsx, src/domains/wallet/components/WalletHeader/WalletHeader.tsx, src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap, src/domains/wallet/e2e/wallet-details.e2e.ts, src/domains/wallet/i18n.ts, src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.tsx, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap, src/utils/e2e-interfaces.ts
https://app.clickup.com/t/214c7k
=> feat: implement starring of wallets

src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx, src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap, src/domains/transaction/i18n.ts, src/domains/transaction/pages/Registration/Registration.tsx, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/ResignRegistration/ResignRegistration.models.ts, src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx, src/domains/transaction/pages/ResignRegistration/Step1.tsx, src/domains/transaction/pages/ResignRegistration/Step2.tsx, src/domains/transaction/pages/ResignRegistration/Step4.tsx, src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap, src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx, src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap, src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx, src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/transaction/pages/TransactionSend/TransactionSend.tsx, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
Use real `transaction` and `senderWallet` data on `TransactionSuccessful` component
=> refactor: consume tx data in `TransactionSuccessful` step

src/domains/transaction/e2e/multiple-transfer.e2e.ts
Task: https://app.clickup.com/t/7ewjv5
=> test: add e2e tests for multiple transfer

src/domains/transaction/e2e/single-transfer.e2e.ts
Task: https://app.clickup.com/t/7ewjv9
=> test: add e2e tests for single transfer

src/app/App.tsx, src/app/services/Scheduler.test.ts, src/app/services/Scheduler.ts
- Sync fees using the scheduler
- Refactor scheduler to a class-based module
- Fix jobs scheduling routine
- Improve scheduler logs
=> feat: sync fees using scheduler

src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap, src/domains/transaction/i18n.ts, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap, src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap, src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
=> chore: fix transaction success title typo

src/app/components/FilterNetwork/FilterNetwork.tsx, src/app/components/FilterNetwork/__snapshots__/FilterNetwork.test.tsx.snap, src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap, src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap, src/domains/news/components/NewsCard/NewsCard.tsx, src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap, src/domains/news/components/NewsOptions/NewsOptions.test.tsx, src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap, src/domains/news/data.ts, src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
Changes dummy data so the icons in the News components show up again thus fixing the failing e2e test.
=> fix: icons in news components

src/domains/vote/e2e/votes.e2e.ts
=> test: add e2e tests to send a vote transaction

src/app/i18n/common/i18n.ts, src/domains/news/components/NewsOptions/NewsOptions.tsx, src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap, src/domains/news/components/NewsOptions/components/SelectCategory/SelectCategory.stories.tsx, src/domains/news/data.ts, src/domains/news/e2e/filtering.e2e.ts, src/domains/news/pages/News/News.test.tsx, src/domains/news/pages/News/News.tsx, src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
https://app.clickup.com/t/8cue5r
=> refactor: add `Select All` button to news options

src/app/__snapshots__/App.test.tsx.snap, src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx, src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap, src/domains/transaction/components/EntityRegistrationForm/ReviewStep.tsx, src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap, src/domains/transaction/components/EntityResignationSteps/Step2/EntitySecondStep.tsx, src/domains/transaction/components/SecondSignatureRegistrationForm/Step4.tsx, src/domains/transaction/components/TotalAmountBox/TotalAmountBox.stories.tsx, src/domains/transaction/components/TotalAmountBox/TotalAmountBox.test.tsx, src/domains/transaction/components/TotalAmountBox/TotalAmountBox.tsx, src/domains/transaction/components/TotalAmountBox/__snapshots__/TotalAmountBox.test.tsx.snap, src/domains/transaction/i18n.ts, src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap, src/domains/transaction/pages/SendEntityResignation/SendEntityResignation.test.tsx, src/domains/transaction/pages/SendEntityResignation/Step2.tsx, src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap, src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap, src/domains/transaction/pages/SendIpfs/Step2.tsx, src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap, src/domains/transaction/pages/SendTransfer/Step2.tsx, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap, src/domains/transaction/pages/SendVote/Step2.tsx
https://app.clickup.com/t/8eq7hw
=> refactor: adjust styles of `TotalAmountBox` and remove hardcoded ticker

src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.tsx, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
https://app.clickup.com/t/7urmmd
=> feat: add tx modal to wallet details page

.github/workflows/draft-artifacts.yml, .github/workflows/publish-release.yml, .github/workflows/test.yml, package.json
=> release: 2.9.4

src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.tsx, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletRegistrations/WalletRegistrations.test.tsx, src/domains/wallet/pages/WalletDetails/components/WalletRegistrations/WalletRegistrations.tsx, src/domains/wallet/pages/WalletDetails/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.test.tsx, src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.tsx, src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
https://app.clickup.com/t/7rwahy
=> refactor: add vote and register buttons to wallet details

src/domains/vote/components/DelegateTable/DelegateTable.test.tsx, src/domains/vote/components/DelegateTable/DelegateTable.tsx, src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap, src/domains/vote/pages/Votes/Votes.tsx, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
=> feat: add pagination to the list of delegates

src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap, src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.test.tsx, src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap, src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap, src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.tsx, src/domains/transaction/components/SecondSignatureDetail/__snapshots__/SecondSignatureDetail.test.tsx.snap, src/domains/transaction/components/TransactionDetail/TransactionAmount/TransactionAmount.tsx, src/domains/transaction/components/TransactionDetail/TransactionRecipients/TransactionRecipients.test.tsx, src/domains/transaction/components/TransactionDetail/TransactionRecipients/TransactionRecipients.tsx, src/domains/transaction/components/TransactionDetail/TransactionRecipients/__snapshots__/TransactionRecipients.test.tsx.snap, src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap, src/domains/transaction/components/TransferDetail/TransferDetail.tsx, src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap, src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap, src/tests/fixtures/transactions/index.ts
Adjustments and fixes in `TransferDetail` modal.
=> refactor: adjustments and fixes in transfer details

src/domains/vote/pages/Votes/Votes.tsx, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
Fixes the network selection on the votes page.
=> refactor: fix network select in votes page

src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.test.tsx, src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.tsx, src/domains/transaction/components/SecondSignatureDetail/__snapshots__/SecondSignatureDetail.test.tsx.snap, src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
Adjustments and fixes in the `SecondSignatureDetail` modal.
=> refactor: adjustments and fixes in second signature details

src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.test.tsx, src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.tsx, src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap, src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
Adjustments and fixes in the `DelegateRegistrationDetail` modal.
=> refactor: adjustments and fixes in delegate registration details

src/domains/transaction/e2e/ipfs-transaction.e2e.ts, src/domains/transaction/e2e/single-transfer.e2e.ts, src/domains/transaction/e2e/transactions-routing.e2e.ts, src/domains/transaction/e2e/vote-transaction.e2e.ts
=> test: add e2e tests to vote transaction

src/domains/transaction/components/DelegateResignationDetail/DelegateResignationDetail.stories.tsx, src/domains/transaction/components/DelegateResignationDetail/DelegateResignationDetail.test.tsx, src/domains/transaction/components/DelegateResignationDetail/DelegateResignationDetail.tsx, src/domains/transaction/components/DelegateResignationDetail/__snapshots__/DelegateResignationDetail.test.tsx.snap, src/domains/transaction/components/DelegateResignationDetail/index.tsx, src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx, src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx, src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap, src/domains/transaction/i18n.ts
Adds the `DelegateResignationDetail` modal.
=> feat: add delegate resignation details

src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap, src/domains/transaction/components/DelegateResignationDetail/__snapshots__/DelegateResignationDetail.test.tsx.snap, src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
Fixes failing `ImportWallet` tests.
=> fix: adjust network to new format in jest mock

src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx, src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx, src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap, src/domains/transaction/components/DelegateRegistrationForm/steps/FormStep.tsx, src/domains/transaction/components/DelegateRegistrationForm/steps/ReviewStep.tsx, src/domains/transaction/components/DelegateRegistrationForm/steps/index.ts, src/domains/transaction/components/MultiSignatureDetail/Step1.tsx, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap, src/domains/transaction/components/TransactionDetail/TransactionDetail.styles.ts, src/domains/transaction/components/TransactionDetail/TransactionDetail.tsx, src/domains/transaction/components/TransactionDetail/__snapshots__/TransactionDetail.test.tsx.snap, src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap, src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx, src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.models.ts, src/domains/transaction/pages/SendEntityRegistration/Step3.tsx, src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap, src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap, src/domains/transaction/pages/SendIpfs/Step2.tsx, src/domains/transaction/pages/SendIpfs/Step4.tsx, src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap, src/domains/transaction/pages/SendTransfer/Step4.tsx, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap, src/domains/transaction/pages/SendVote/Step1.tsx, src/domains/transaction/pages/SendVote/Step2.tsx, src/domains/transaction/pages/SendVote/Step4.tsx, src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap, src/domains/wallet/pages/ImportWallet/Step3.tsx, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
https://app.clickup.com/t/8pqww6
=> refactor: adjustments to delegate registration form

src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.test.tsx, src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.tsx, src/domains/transaction/components/SecondSignatureRegistrationForm/Step1.tsx, src/domains/transaction/components/SecondSignatureRegistrationForm/Step2.tsx, src/domains/transaction/components/SecondSignatureRegistrationForm/Step3.tsx, src/domains/transaction/components/SecondSignatureRegistrationForm/Step4.tsx, src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
https://app.clickup.com/t/8pqx4u
=> refactor: adjustments to delegate second signature form

src/domains/dashboard/pages/Dashboard/Dashboard.tsx
When trying to import a Lisk address and return to the dashboard page, it will return the following error below:
=> fix: check if the extra styles of the network is not undefined

src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/news/components/BlockfolioAd/BlockfolioAd.tsx, src/domains/news/components/BlockfolioAd/__snapshots__/BlockfolioAd.test.tsx.snap, src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
=> fix: open external links to the blockfolio app

src/domains/network/components/SelectNetwork/SelectNetwork.test.tsx, src/domains/network/components/SelectNetwork/SelectNetwork.tsx, src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
https://app.clickup.com/t/78r70t
=> refactor: filter networks on input

src/app/components/Icon/Icon.test.tsx, src/app/components/Icon/Icon.tsx, src/app/components/Icon/__snapshots__/Icon.test.tsx.snap, src/app/components/NavigationBar/NavigationBar.test.tsx, src/app/components/NavigationBar/NavigationBar.tsx
Show the exchange symbol of the active profile in the navbar.
=> fix: show exchange currency in navbar

src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx, src/domains/wallet/pages/ImportWallet/ImportWallet.tsx, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap, src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.tsx, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap, src/utils/testing-library.tsx
User does not need to wait for extra data to import a wallet.
=> refactor: import wallet and sync data in background

src/app/components/Slider/Slider.tsx, src/app/components/Slider/__snapshots__/Slider.test.tsx.snap, src/domains/dashboard/components/Wallets/Wallets.test.tsx, src/domains/dashboard/components/Wallets/Wallets.tsx, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap, src/domains/plugin/components/PluginInfo/__snapshots__/PluginInfo.test.tsx.snap, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap, src/styles/base.css
https://app.clickup.com/t/8pt24r
=> fix: wallet order in dashboard wallet grid

src/domains/profile/e2e/create-profile-action.e2e.ts, src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
https://app.clickup.com/t/8wpafd
=> chore: set cryptocompare as default market provider

src/app/__snapshots__/App.test.tsx.snap, src/app/i18n/common/i18n.ts, src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/profile/pages/Welcome/Welcome.tsx, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
https://app.clickup.com/t/8wthej
=> refactor: disable msq buttons

src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx, src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx, src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap, src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.tsx, src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.models.ts, src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx, src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx, src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap, src/domains/transaction/routing.ts, src/tests/fixtures/registrations/entity-delegates.json
* Show entity delegate registrations in My Registrations page
* Perform `SendEntityUpdate` when a delegate has an entity registered
* Perform `SendEntityRegistration` when a delegate doesn't have an entity registered - starting from 2nd step
=> feat: implement delegate to entity update

src/domains/setting/i18n.ts, src/domains/setting/pages/Settings/available-settings/General.tsx
Task: https://app.clickup.com/t/8rrhyf
=> feat: add success toast to profile settings save

src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
=> refactor: add title to create profile page

src/domains/contact/components/ContactListItem/ContactListItem.tsx, src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap, src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
https://app.clickup.com/t/8yqxzc
=> fix: add border props as classnames

src/app/App.tsx, src/app/hooks/index.ts, src/app/hooks/use-reload-path.ts, src/domains/setting/pages/Settings/Settings.test.tsx, src/domains/setting/pages/Settings/Settings.tsx, src/router/RouterView.test.tsx, src/router/RouterView.tsx
https://app.clickup.com/t/9u5cnv
=> feat: reload settings route after saving

src/app/components/Slider/Slider.tsx, src/app/components/Slider/__snapshots__/Slider.test.tsx.snap, src/domains/dashboard/components/Wallets/Wallets.test.tsx, src/domains/dashboard/components/Wallets/Wallets.tsx, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/plugin/components/PluginInfo/__snapshots__/PluginInfo.test.tsx.snap, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
https://app.clickup.com/t/8pt24r
=> refactor: reduce wallet card count on dashboard

src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap, src/domains/transaction/components/EntityRegistrationForm/FormStep.tsx, src/domains/transaction/components/InputFee/InputFee.tsx, src/domains/transaction/components/InputFee/__snapshots__/InputFee.test.tsx.snap, src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx, src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
* Feed `SendEntityRegistration` steps with correct fees
* Set correct fees in `SendEntityUpdate` form
* Set correct fees in delegate -> entity registration form
=> fix: adjust fees data in entity registration forms

src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap, src/domains/setting/i18n.ts, src/domains/setting/pages/Settings/Settings.test.tsx, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/setting/pages/Settings/available-settings/General.tsx
=> fix: settings page add validation if the profile name already exists

src/domains/contact/components/CreateContact/CreateContact.test.tsx, src/domains/profile/i18n.ts, src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx, src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
=> fix: update create profile page and some tweaks

src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
https://app.clickup.com/t/8wtqc0
=> fix: dynamic flex class on dashboard sections

src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/utils/e2e-utils.ts
=> refactor: add missing mocks on e2e tests

src/app/__snapshots__/App.test.tsx.snap, src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap, src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowInfo.tsx, src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap, src/domains/wallet/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
=> fix: break words for long vendorfield in the tooltip

src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
=> test: update `SendIpfs` routes

src/domains/dashboard/components/FilterWallets/FilterWallets.tsx, src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx, src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.test.tsx
Fixes: https://app.clickup.com/t/8wpd6j & https://app.clickup.com/t/8wpetf
=> fix: save dashboard settings

src/domains/transaction/components/AddRecipient/AddRecipient.models.ts, src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx, src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap, src/domains/transaction/pages/SendTransfer/Step1.tsx
Task: https://app.clickup.com/t/2ezkb5
=> refactor: multipayment should be available only for supported networks

src/domains/transaction/components/MultiSignatureDetail/SummaryStep.tsx, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
Fixes the recipient display for in the detail modal of (pending) multisignature transfers.
=> fix: retrieve multisignature recipientId through get method

src/domains/dashboard/components/Wallets/Wallets.tsx, src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx, src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Task: https://app.clickup.com/t/2f1a9m
=> feat: persist the type of view (grid & list)

src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx, src/domains/transaction/components/EntityRegistrationForm/FormStep.tsx, src/domains/transaction/e2e/delegate-registration.e2e.ts, src/domains/transaction/i18n.ts, src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.models.ts, src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx, src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx, src/domains/transaction/pages/SendEntityRegistration/Step1.tsx, src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
Adds `Plugin` and `Business` registration types on `EntityRegistration`
=> feat: add missing aip36 registrations

src/app/components/WalletListItem/WalletListItem.tsx, src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx, src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRow.test.tsx.snap, src/domains/vote/components/AddressTable/__snapshots__/AddressTable.test.tsx.snap, src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Task: https://app.clickup.com/t/9gr67y
=> fix: resize wallet type icons in list view

src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/tests/fixtures/coins/ark/devnet/transactions/byAddress/D5sRKWckH4rE1hQ9eeMeHAepgyC3cvJtwb-1-30.json, src/tests/fixtures/coins/ark/devnet/transactions/byAddress/D8rr7B1d6TL6pf14LgMz4sKp1VBMs6YUYD-1-30.json, src/tests/fixtures/coins/ark/devnet/transactions/byAddress/DC8ghUdhS8w8d11K8cFQ37YsLBFhL3Dq2P-1-30.json, src/tests/fixtures/coins/ark/devnet/transactions/byAddress/DJXg9Vqg2tofRNrMAvMzhZTkegu8QyyNQq-1-30.json, src/utils/e2e-utils.ts
=> chore: increase dashboard transactions page limit

src/app/__snapshots__/App.test.tsx.snap, src/app/components/Card/Card.tsx, src/app/components/Card/__snapshots__/Card.test.tsx.snap, src/app/components/Card/__snapshots__/CardControl.test.tsx.snap, src/app/components/WalletCard/WalletCard.tsx, src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/exchange/components/ExchangeCard/__snapshots__/ExchangeCard.test.tsx.snap, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap, src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap, src/domains/news/pages/News/__snapshots__/News.test.tsx.snap, src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap, src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap, src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
Fixes the alignment of icons in cards.
=> fix: alignment of card icons

src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx, src/domains/vote/components/DelegateTable/DelegateRow/DelegateRow.tsx, src/domains/vote/components/DelegateTable/DelegateRow/__snapshots__/DelegateRow.test.tsx.snap, src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.tsx, src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
Removed the status icon background.
**Before:**
**After:**
=> fix: update the vote status icon

src/domains/transaction/components/TransactionTable/TransactionTable.tsx
Task: https://app.clickup.com/t/9rtnxr
=> feat: add sort functionality in the transaction history table

src/app/components/NavigationBar/NavigationBar.tsx, src/domains/wallet/components/ReceiveFunds/ReceiveFunds.stories.tsx, src/domains/wallet/components/ReceiveFunds/ReceiveFunds.test.tsx, src/domains/wallet/components/ReceiveFunds/ReceiveFunds.tsx, src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap, src/domains/wallet/components/SearchWallet/SearchWallet.models.ts, src/domains/wallet/components/SearchWallet/SearchWallet.tsx
=> refactor: update receive funds modal

src/domains/transaction/components/AddRecipient/AddRecipient.tsx
=> fix: remove zero below the amount input in multi payment mode

src/domains/profile/components/ResetProfile/ResetProfile.tsx, src/domains/profile/components/ResetProfile/__snapshots__/ResetProfile.test.tsx.snap
=> chore: resize `ResetProfile` modal

src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx, src/domains/wallet/pages/WalletDetails/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
=> fix: align the ledger icon when there is no name for the wallet

src/app/__snapshots__/App.test.tsx.snap, src/app/components/NavigationBar/NavigationBar.styles.ts, src/app/components/NavigationBar/NavigationBar.tsx, src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, src/app/components/Notifications/NotificationsDropdown.tsx, src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap, src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap, src/domains/news/pages/News/__snapshots__/News.test.tsx.snap, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap, src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap, src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap, src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap, src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap, src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Adjusts styles of the navbar for dark mode.
=> refactor: add styles for dark navbar

src/app/components/Notifications/NotificationTransactionItemSkeleton.tsx, src/app/components/Notifications/NotificationsDropdown.tsx, src/domains/news/pages/News/News.test.tsx
Updates the transaction notification skeleton.
=> refactor: update notification skeletons

src/domains/news/components/NewsCard/NewsCardSkeleton.tsx, src/domains/news/pages/News/News.test.tsx
=> refactor: update news skeletons

src/domains/transaction/components/TransactionDetail/TransactionNetwork/TransactionNetwork.tsx, src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.tsx
Task: https://app.clickup.com/t/9uy1fc
=> fix: change ARK Mainnet token to ARK

src/domains/wallet/i18n.ts, src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx, src/domains/wallet/pages/CreateWallet/CreateWallet.tsx, src/domains/wallet/pages/CreateWallet/Step4.tsx, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
https://app.clickup.com/t/7uvp1g
=> refactor: disallow duplicate wallet names on create

src/app/contexts/Ledger/hooks/scanner.state.ts, src/app/contexts/Ledger/hooks/scanner.test.tsx, src/app/contexts/Ledger/hooks/scanner.ts
https://app.clickup.com/t/2k74dz
=> fix: scan more ledger wallets after imported

src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap, src/app/components/Slider/Slider.tsx, src/app/components/Slider/__snapshots__/Slider.test.tsx.snap, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap, src/domains/plugin/components/PluginInfo/__snapshots__/PluginInfo.test.tsx.snap, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
=> fix: make slider dots clickable

__tests__/unit/services/client.spec.js, __tests__/unit/services/crypto/transaction-signer.spec.js, config/networks/devnet.json, config/networks/mainnet.json, src/renderer/services/crypto/transaction-signer.js, src/renderer/store/modules/network.js
=> refactor: update default API server

src/domains/dashboard/components/Wallets/Wallets.tsx, src/domains/dashboard/components/WalletsControls/WalletsControls.tsx, src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Task: https://app.clickup.com/t/a0wdjj
=> feat: add indicator of active filter to WalletControls component

src/domains/transaction/pages/SendVote/__snapshots__/LedgerReviewStep.test.tsx.snap, src/domains/vote/components/DelegateTable/DelegateTable.tsx, src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
Task: https://app.clickup.com/t/2n6n64
=> refactor: the colors of the bottom sheet votes must match the designer

src/app/components/LineChart/LineChart.tsx, src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/dashboard/pages/Dashboard/models.ts
=> refactor: run portfolio chart animation only once

src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap, src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap, src/domains/wallet/components/SearchWallet/SearchWallet.test.tsx, src/domains/wallet/components/SearchWallet/SearchWallet.tsx, src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
* Filter sender wallet by name or address
* Show empty screen when not found
* Prevent reset-search button submitting form
=> feat: implement sender search functionality

src/app/components/NavigationBar/NavigationBar.test.tsx, src/app/components/NavigationBar/NavigationBar.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
=> refactor: disable navbar send transfer button when no wallets

src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
Wait for the `WalletVote__empty` to appear.
=> test: wait for wallet vote to be truthy

src/domains/vote/components/DelegateTable/DelegateTable.tsx, src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap, src/domains/vote/pages/Votes/Votes.test.tsx, src/domains/vote/pages/Votes/Votes.tsx, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Task: https://app.clickup.com/t/88vmbx
=> feat: implement search functionality in my votes page

src/app/components/NavigationBar/NavigationBar.test.tsx, src/app/components/NavigationBar/NavigationBar.tsx
Task: https://app.clickup.com/t/actam2
=> chore: remove exit option from the profile dropdown

src/app/components/Toggle/Toggle.test.tsx, src/app/components/Toggle/Toggle.tsx, src/app/components/Toggle/__snapshots__/Toggle.test.tsx.snap, src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/setting/pages/Settings/available-settings/Peer.tsx, src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Adjustments to the `Toggle` component.
=> ui: adjust toggle styles

src/domains/splash/pages/Splash/Splash.tsx, src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
=> chore: prevent text selection on the splash screen

src/domains/transaction/components/EntityRegistrationForm/SummaryStep.tsx, src/domains/transaction/i18n.ts, src/domains/transaction/pages/SendEntityUpdate/SendEntityUpdate.test.tsx, src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
https://app.clickup.com/t/b0whnh
=> fix: display basic ipfs data in summary step

src/app/__snapshots__/App.test.tsx.snap, src/app/contexts/Configuration/Configuration.test.tsx, src/app/contexts/Configuration/__snapshots__/Configuration.test.tsx.snap, src/domains/dashboard/components/FilterWallets/FilterWallets.stories.tsx, src/domains/dashboard/components/FilterWallets/FilterWallets.test.tsx, src/domains/dashboard/components/FilterWallets/FilterWallets.tsx, src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap, src/domains/dashboard/components/FilterWallets/hooks.ts, src/domains/dashboard/components/FilterWallets/models.ts, src/domains/dashboard/components/WalletsControls/WalletsControls.stories.tsx, src/domains/dashboard/components/WalletsControls/WalletsControls.test.tsx, src/domains/dashboard/components/WalletsControls/WalletsControls.tsx, src/domains/dashboard/i18n.ts, src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/dashboard/pages/Dashboard/hooks/use-dashboard-config.ts, src/domains/dashboard/pages/Dashboard/models.ts
https://app.clickup.com/t/ayuc9k
=> refactor: remove chart from dashboard

src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap, src/app/components/SelectProfileImage/SelectProfileImage.tsx, src/app/components/SelectProfileImage/__snapshots__/SelectProfileImage.test.tsx.snap, src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
Fixes the styles of the profile image selection button.
=> refactor: adjust styles of profile image selection

src/app/__snapshots__/App.test.tsx.snap, src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap, src/app/components/SelectDropdown/styles.ts, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
https://app.clickup.com/t/c4z2qj
=> refactor: style adjustments to SelectDropdown

src/domains/transaction/pages/SendRegistration/SendRegistration.tsx, src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
https://app.clickup.com/t/c51dtm
=> refactor: SendRegistration crumbs

src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap, src/app/components/SelectDropdown/styles.ts, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
=> fix: dropdown smooth transition and cursor pointer

src/app/components/Link/Link.test.tsx, src/app/components/Link/Link.tsx, src/app/components/Link/__snapshots__/Link.test.tsx.snap, src/app/i18n/common/i18n.ts
https://app.clickup.com/t/c520h4
=> refactor: catch error thrown by openExternal

src/app/components/SelectionBar/SelectionBar.tsx, src/app/components/SelectionBar/__snapshots__/SelectionBar.test.tsx.snap, src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap, src/domains/transaction/components/InputFee/InputFee.tsx, src/domains/transaction/components/InputFee/__snapshots__/InputFee.test.tsx.snap, src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap, src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap, src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
https://app.clickup.com/t/c4zktc
=> refactor: style adjustments to InputFee and SelectionBar

config-overrides.js
https://app.clickup.com/t/7gr16k
=> build: fix module not found in production

src/app/__snapshots__/App.test.tsx.snap, src/app/i18n/common/i18n.ts, src/domains/profile/i18n.ts, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
https://app.clickup.com/t/cczyhh
=> chore: remove any mention of msq

CODEOWNERS
that way you'll actually have powers @samharperpittam
=> chore: add sam to codeowners

src/electron/index.js
https://app.clickup.com/t/c8uxbd
=> chore: add minimum window width

src/app/i18n/common/i18n.ts, src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap, src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap, src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap, src/domains/contact/i18n.ts, src/domains/plugin/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap, src/domains/plugin/i18n.ts, src/domains/transaction/i18n.ts, src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap, src/domains/wallet/i18n.ts
https://app.clickup.com/t/7gu9j4
=> chore: update titles to use title case

.github/workflows/format.yml
https://app.clickup.com/t/cd1ymk
=> chore: only rerun snapshots if formatting changed anything

src/electron/index.ts
https://app.clickup.com/t/ck2nau
=> chore: add minimum window height

config-overrides.js, src/electron/menu.js
https://app.clickup.com/t/ch3heb
=> fix: icon path in the about window

package.json, yarn.lock
Updates the `testcafe` and `testcafe-browser-provider-electron` packages.
=> chore: update testcafe dependencies

src/styles/scrollbars.css
https://app.clickup.com/t/cmxhr8
=> fix: set scrollbar height

src/app/hooks/use-updater.test.tsx, src/app/hooks/use-updater.ts
https://app.clickup.com/t/c6yh0p
=> fix: catch error during update check

src/app/components/SelectionBar/SelectionBar.tsx, src/app/components/SelectionBar/__snapshots__/SelectionBar.test.tsx.snap, src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap, src/domains/transaction/components/InputFee/__snapshots__/InputFee.test.tsx.snap, src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap, src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap, src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Somehow the changes made in https://github.com/ArkEcosystem/desktop-wallet/pull/3183 are gone 🤔 this PR re-adds those changes.
=> chore: re-add style changes to SelectionBar

src/app/components/Dropdown/Dropdown.tsx, src/domains/transaction/components/FilterTransactions/__snapshots__/FilterTransactions.test.tsx.snap, src/domains/wallet/i18n.ts, src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx
https://app.clickup.com/t/cpzack
=> chore: reorder wallet header menu

src/domains/dashboard/components/Transactions/Transactions.test.tsx, src/domains/dashboard/components/Transactions/Transactions.tsx
https://app.clickup.com/t/c4zdzu
=> fix: toggle transaction tab before fully loaded

src/app/i18n/common/i18n.ts, src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.tsx, src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap, src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx, src/domains/transaction/pages/SendIpfs/SendIpfs.tsx, src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap, src/domains/transaction/pages/SendRegistration/SendRegistration.tsx, src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx, src/domains/transaction/pages/SendTransfer/SendTransfer.tsx, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap, src/domains/transaction/pages/SendVote/SendVote.tsx, src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
https://app.clickup.com/t/7evdhb
=> chore: remove copy and download buttons

src/app/hooks/use-profile-synchronizer.test.tsx, src/app/hooks/use-profile-synchronizer.ts, src/app/hooks/use-synchronizer.test.tsx, src/app/hooks/use-synchronizer.ts
=> fix: clear profile sync jobs when inactive

src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx, src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRow.test.tsx.snap, src/domains/vote/components/AddressTable/AddressTable.tsx, src/domains/vote/components/AddressTable/__snapshots__/AddressTable.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
=> refactor: remove msq reference from `Votes`

src/domains/vote/components/DelegateTable/DelegateRow/DelegateRow.tsx, src/domains/vote/components/DelegateTable/DelegateRow/__snapshots__/DelegateRow.test.tsx.snap, src/domains/vote/components/DelegateTable/DelegateTable.tsx, src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
=> refactor: update delegate overview table

src/app/components/Link/Link.test.tsx, src/app/components/Link/Link.tsx, src/app/components/Link/__snapshots__/Link.test.tsx.snap, src/app/components/NavigationBar/NavigationBar.test.tsx, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.tsx, src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap, src/electron/index.ts, src/plugins/context/PluginManagerProvider.test.tsx, src/plugins/context/PluginManagerProvider.tsx, src/utils/electron-utils.test.ts, src/utils/electron-utils.ts
https://app.clickup.com/t/ck27ag
=> fix: move `openExternal` to main process

src/app/components/Dropdown/Dropdown.styles.ts, src/app/components/Dropdown/Dropdown.tsx, src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap, src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap, src/domains/dashboard/components/FilterWallets/FilterWallets.tsx, src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap, src/domains/transaction/components/FilterTransactions/__snapshots__/FilterTransactions.test.tsx.snap, src/domains/vote/components/VotesFilter/__snapshots__/VotesFilter.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
https://app.clickup.com/t/cwwm35
=> refactor: set dropdown background based on options

src/app/components/WalletCard/WalletCard.test.tsx, src/app/components/WalletCard/WalletCard.tsx, src/app/components/WalletCard/WalletCardSkeleton.tsx, src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap, src/app/components/WalletCard/index.ts, src/domains/dashboard/components/Wallets/Wallets.test.tsx, src/domains/dashboard/components/Wallets/Wallets.tsx, src/domains/dashboard/components/Wallets/WalletsGrid.tsx, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/components/Wallets/models.ts, src/domains/dashboard/pages/Dashboard/Dashboard.tsx
https://user-images.githubusercontent.com/6547002/105434381-c0b81180-5c5b-11eb-9409-c70b2ce439b4.mov
=> feat: show wallet card skeletons while loading

src/app/__snapshots__/App.test.tsx.snap, src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/profile/pages/Welcome/Welcome.tsx, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap, src/domains/transaction/components/EntityDetail/__snapshots__/EntityDetail.test.tsx.snap, src/domains/transaction/components/LegacyMagistrateDetail/__snapshots__/LegacyMagistrateDetail.test.tsx.snap, src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureRegistrationDetail.test.tsx.snap, src/domains/transaction/components/SecondSignatureDetail/__snapshots__/SecondSignatureDetail.test.tsx.snap, src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap, src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
=> fix: show profile creation button in `Welcome` with no profiles

src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.tsx
https://app.clickup.com/t/d119dq
=> refactor: use isMultisignature method on transaction

src/domains/wallet/e2e/common.ts
=> chore: use i18n in e2e common file

package.json, src/domains/dashboard/components/FilterWallets/hooks.test.tsx, src/domains/dashboard/components/FilterWallets/hooks.ts, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
https://app.clickup.com/t/dax8kk
=> fix: do not activate filter button when changing view type

src/domains/wallet/components/SignMessage/SignMessage.tsx, src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
=> fix: correct avatar in sign message modal

src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.test.tsx, src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.tsx
-   [x] Abort previous request when changing mode/tab
-   [x] Respect selected transaction mode (all, sent, received) when running background sync job
=> fix: adjust wallet transactions sync and filtering

src/domains/plugin/components/PluginCard/PluginCard.tsx, src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap, src/domains/plugin/components/PluginGrid/PluginGrid.test.tsx, src/domains/plugin/components/PluginGrid/PluginGrid.tsx, src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap, src/domains/plugin/pages/PluginManager/PluginManager.tsx, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/plugin/pages/PluginsCategory/PluginsCategory.test.tsx, src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
https://app.clickup.com/t/df10aq
=> refactor: adjust actions menu in plugin cards

src/app/components/NavigationBar/NavigationBar.tsx, src/app/i18n/common/i18n.ts, src/domains/wallet/components/SearchWallet/SearchWallet.test.tsx, src/domains/wallet/components/SearchWallet/SearchWallet.tsx, src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
Remove hardcoded `BTC` as the default exchange currency and use the one from profile settings in `SearchWallets`
=> fix: use default exchange currency from profile setting in `SearchWallet`

src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/i18n.ts, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
Changing text on the Settings page
Was created a new text for descriptions
Removed the old text and put the new one
=> fix: title and descriptions on the Settings page

src/domains/transaction/e2e/common.ts, src/domains/transaction/i18n.ts, src/domains/transaction/pages/SendDelegateResignation/FormStep.tsx, src/domains/transaction/pages/SendDelegateResignation/ReviewStep.tsx, src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.models.ts, src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.tsx, src/domains/transaction/pages/SendDelegateResignation/SummaryStep.tsx, src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
https://app.clickup.com/t/dax5n0
=> fix: delegate resignation fee handling and validation

src/app/__snapshots__/App.test.tsx.snap, src/domains/profile/e2e/create-profile-action.e2e.ts, src/domains/profile/e2e/create-profile-routing.e2e.ts, src/domains/profile/e2e/delete-profile-action.e2e.ts, src/domains/profile/pages/Welcome/Welcome.test.tsx, src/domains/profile/pages/Welcome/Welcome.tsx, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
https://app.clickup.com/t/d53c74
=> refactor: use card for create button on welcome screen to match profiles

src/domains/dashboard/components/FilterWallets/hooks.ts, src/domains/dashboard/components/Transactions/Transactions.test.tsx, src/domains/dashboard/components/Transactions/Transactions.tsx, src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/dashboard/pages/Dashboard/hooks/use-dashboard-config.test.tsx, src/domains/dashboard/pages/Dashboard/hooks/use-dashboard-config.ts, src/utils/e2e-utils.ts
Update transactions table when changing wallet filters in dashboard
=> fix: filter dashboard transactions by selected wallets

src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
https://app.clickup.com/t/e33qtq
=> fix: pass correct wallet instance to unconfirmed transaction method

src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
https://app.clickup.com/t/e33p1v
=> fix: use correct wallet instance when building path to go back to

src/domains/wallet/components/MnemonicVerification/MnemonicVerificationOptions.tsx
https://app.clickup.com/t/c52fy1
=> fix: do not re-evaluate mnemonic verification options

src/app/hooks/use-validation.ts, src/domains/setting/pages/Settings/Settings.test.tsx, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/setting/pages/Settings/available-settings/General.tsx, src/domains/setting/validations/Settings.ts, src/domains/setting/validations/index.ts
https://app.clickup.com/t/e0y2jg
=>  fix: add uniqueness check to profile name validation

src/domains/transaction/components/InputFee/InputFee.tsx
=> chore: remove obsolete todo about default fee prop in `InputFee`

package.json, src/utils/e2e-utils.ts, yarn.lock
https://app.clickup.com/t/eh1dub
=> deps: update testcafe

src/app/components/NavigationBar/NavigationBar.tsx
https://app.clickup.com/t/at0pgc
=> fix: close search wallet modal before assigning selected wallet

src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Additional fixes after https://github.com/ArkEcosystem/desktop-wallet/pull/3350
=> fix: resolve errors in `SendTransfer` tests

src/app/components/Table/Table.tsx, src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionTable.test.tsx, src/domains/transaction/components/TransactionTable/TransactionTable.tsx, src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
-   [x] Add `initialState` prop in `Table` component. See `react-table` API https://react-table.tanstack.com/docs/api/useTable
-   [x] Add default sorting in transaction tables, by date (descending order)
=> feat: add initial state in `Table`

src/domains/network/components/SelectNetwork/SelectNetwork.tsx
=> refactor: adjust disabled state in `SelectNetwork` options

.github/workflows/test.yml, scripts/generate-test-workflow.js, src/domains/contact/__snapshots__/routing.test.tsx.snap, src/domains/contact/routing.test.tsx
…ve being coverd for 100
Changed test.yml and generate-test-workflow for src/domains/contact
=> test: increase `src/domains/contact` coverage to 100% 

.github/workflows/test.yml, scripts/generate-test-workflow.js
…ashboard
Checked coverage for src/domains/dashboard
Changed test.yml for src/domains/dashboard directory to 100%
=> test: increase `src/domains/dashboard` coverage to 100%

.github/workflows/test.yml, scripts/generate-test-workflow.js, src/domains/exchange/routing.test.tsx
Covered the src/domains/exchange to 100%
Added the unit test for routing 
=> test: increase `src/domains/exchange` coverage to 100%

.github/workflows/test.yml, scripts/generate-test-workflow.js, src/domains/news/routing.test.tsx
Covered the src/domains/news to 100%
Added the unit test for routing
=> test: increase `src/domains/news` coverage to 100%

src/app/App.tsx
https://app.clickup.com/t/en416d
=> fix: parse process.env.REACT_APP_IS_E2E

src/app/components/Table/TableRow.test.tsx, src/app/components/Table/__snapshots__/TableRow.test.tsx.snap
https://app.clickup.com/t/en67uy
=> test: get rid of error in TableRow tests

.github/workflows/test.yml, scripts/generate-test-workflow.js, src/domains/profile/routing.test.tsx
Covered src/domains/profile to 100%
Added the unit test for routing and changed test.yml and generate-test-workflow.js for src/domains/profile to 100
=> test: increase `src/domains/profile` coverage to 100%

src/domains/transaction/components/TransactionTable/TransactionTable.tsx
https://app.clickup.com/t/epycpj
=> refactor: set explicit id on date column

.github/workflows/test.yml, scripts/generate-test-workflow.js, src/domains/setting/routing.test.tsx
Covered src/domains/setting to 100%
Added unit test for the routing, changed test.yml and generate-test-workflow to 100 for src/domains/setting
=> test: increase `src/domains/setting` coverage to 100%

src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.test.tsx, src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.tsx
https://app.clickup.com/t/eq5nxh
=> feat: add fee warning to delegate resignation form

src/domains/transaction/pages/SendRegistration/SendRegistration.test.tsx, src/domains/transaction/pages/SendRegistration/SendRegistration.tsx
https://app.clickup.com/t/eq5nxh
=> feat: add fee warning to registration form

src/domains/transaction/pages/SendVote/SendVote.test.tsx, src/domains/transaction/pages/SendVote/SendVote.tsx
https://app.clickup.com/t/eq5nxh
=> feat: add fee warning to vote form

src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx, src/domains/transaction/pages/SendIpfs/SendIpfs.tsx
https://app.clickup.com/t/eq5nxh
=> feat: add fee warning to ipfs form

src/app/contexts/Ledger/hooks/__snapshots__/scanner.test.tsx.snap, src/app/contexts/Ledger/hooks/scanner.test.tsx
Removed tests with the same identifier. Rewrite the test, that ran with loop errors
Added one more test for the dispatch failed and rewrote logic for toggleSelect test
=> fix: loop errors in scanner.test.tsx

.github/workflows/test.yml, scripts/generate-test-workflow.js, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx, src/domains/transaction/routing.test.tsx, src/domains/transaction/utils.test.ts, src/domains/transaction/validations/Common.test.tsx, src/domains/transaction/validations/SendTransfer.test.tsx
Covered src/domains/transaction to 100%
Added missed tests
=> test: increase `src/domains/transaction` coverage to 100%

.github/workflows/test.yml, scripts/generate-test-workflow.js, src/domains/vote/routing.test.tsx
Covered src/domains/vote to 100%
Added one more test case for the routing. Changed test.yml and generate-test-workflow.js for src/domains/vote to 100
=> test: increase `src/domains/vote` coverage to 100% 

src/app/components/Button/Button.styles.ts, src/app/components/Button/__snapshots__/Button.test.tsx.snap, src/app/components/DeleteResource/DeleteResource.tsx, src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap, src/app/components/SelectProfileImage/__snapshots__/SelectProfileImage.test.tsx.snap, src/domains/contact/components/ContactForm/ContactForm.tsx, src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap, src/domains/contact/components/DeleteContact/__snapshots__/DeleteContact.test.tsx.snap, src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap, src/domains/plugin/components/PluginUninstallConfirmation/PluginUninstallConfirmation.tsx, src/domains/plugin/components/PluginUninstallConfirmation/__snapshots__/PluginUninstallConfirmation.test.tsx.snap, src/domains/profile/components/DeleteProfile/__snapshots__/DeleteProfile.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/components/DeletePeer/__snapshots__/DeletePeer.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap, src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap, src/domains/transaction/components/RecipientList/RecipientList.tsx, src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap, src/domains/wallet/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap
https://app.clickup.com/t/ev0f9j
=>  refactor: use danger variant buttons for destructive actions

src/domains/plugin/pages/PluginView/PluginView.test.tsx, src/domains/plugin/pages/PluginView/PluginView.tsx, src/domains/plugin/pages/PluginView/__snapshots__/PluginView.test.tsx.snap
https://app.clickup.com/t/egza84
=> refactor: display only title in the plugin view page

src/app/components/Notifications/__snapshots__/NotificationTransactionItem.test.tsx.snap, src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap, src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap, src/app/components/Table/TableRow.styles.ts, src/app/components/WalletListItem/WalletListItem.test.tsx, src/app/components/WalletListItem/WalletListItem.tsx, src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap, src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/components/Wallets/__snapshots__/WalletsList.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.tsx, src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionCompactRow.test.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionCompactRow.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.test.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx, src/domains/transaction/components/TransactionTable/UnconfirmedTransactionTable/UnconfirmedTransactionRow.tsx, src/domains/transaction/components/TransactionTable/UnconfirmedTransactionTable/UnconfirmedTransactionTable.test.tsx, src/domains/transaction/components/TransactionTable/UnconfirmedTransactionTable/__snapshots__/UnconfirmedTransactionTable.test.tsx.snap, src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap, src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx, src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
https://app.clickup.com/t/ev6pj1
=> chore: adjust dark mode table hover color

README.md
Typo in List of commands (README.md)
`
yarn build:wind` should be `yarn build:win`
=> chore: update readme build command for windows

src/domains/plugin/components/PluginCard/PluginCard.tsx, src/domains/plugin/components/PluginGrid/PluginGrid.test.tsx, src/domains/plugin/components/PluginList/PluginList.test.tsx, src/domains/plugin/components/PluginListItem/PluginListItem.test.tsx, src/domains/plugin/components/PluginListItem/PluginListItem.tsx, src/domains/plugin/pages/PluginManager/PluginManager.test.tsx, src/domains/plugin/pages/PluginsCategory/PluginsCategory.test.tsx
https://app.clickup.com/t/f16ku1
=> refactor: re-order plugin actions in cards and list

src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.tsx, src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.tsx
https://app.clickup.com/t/d924zb
=> refactor: wait for profile synchronization to vote

src/domains/exchange/components/AddExchange/AddExchange.tsx, src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap
=> refactor: adjust columns in `AddExchange` table

src/app/i18n/common/i18n.ts, src/domains/setting/pages/Settings/Settings.test.tsx, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/setting/pages/Settings/available-settings/Password.tsx, src/domains/setting/validations/Settings.ts
=> fix: adjust password settings validations

src/domains/exchange/components/AddExchange/AddExchange.test.tsx, src/domains/exchange/components/AddExchange/AddExchange.tsx, src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap, src/domains/exchange/i18n.ts, src/domains/exchange/pages/Exchange/Exchange.test.tsx
https://app.clickup.com/t/f35dz0
=> refactor: split name and author and fix logo in add exchange table

src/domains/plugin/components/PluginHeader/PluginHeader.test.tsx, src/domains/plugin/components/PluginHeader/PluginHeader.tsx, src/domains/plugin/pages/PluginDetails/PluginDetails.test.tsx
https://app.clickup.com/t/f16ku1
=> refactor: re-order plugin actions in header

src/domains/plugin/pages/PluginManager/PluginManager.tsx
=> fix: sync filtered packages with search query in `PluginManager`

src/app/contexts/Ledger/hooks/__snapshots__/scanner.test.tsx.snap, src/app/contexts/Ledger/hooks/scanner.test.tsx, src/app/contexts/Ledger/hooks/scanner.ts, src/domains/wallet/pages/ImportWallet/Ledger/LedgerScanStep.tsx
https://app.clickup.com/t/dewp88
=> refactor: abort ledger scanner

src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
=> chore: update dashboard snapshot

src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx, src/domains/wallet/pages/WalletDetails/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
https://app.clickup.com/t/f53j8t
=> fix: remove border from wallet header

src/app/components/Input/InputCounter.test.tsx, src/app/components/Input/InputCounter.tsx, src/app/components/Input/__snapshots__/InputCounter.test.tsx.snap, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap, src/domains/transaction/pages/SendTransfer/FormStep.tsx, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap, src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFundsForm.test.tsx.snap
https://app.clickup.com/t/e307gt
=> fix: adjust vendor field input style

src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap, src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx, src/domains/transaction/pages/SendIpfs/SendIpfs.tsx, src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
https://app.clickup.com/t/f70wvp
=> refactor: allow going back from IPFS transaction form

src/domains/dashboard/e2e/navbar-routing.e2e.ts
https://app.clickup.com/t/d117pj
=> test: adjust navbar e2e test

src/domains/transaction/components/MultiSignatureRegistrationForm/MultiSignatureRegistrationForm.tsx, src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
https://app.clickup.com/t/djw9ak
=> fix: add forgotten call to get translation

src/plugins/core/configuration/plugin-configuration.ts
https://app.clickup.com/t/ff0j3u
=> fix: return only unique permissions

src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap, src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap, src/domains/network/components/NetworkOption/NetworkOption.tsx, src/domains/network/components/SelectNetwork/SelectNetwork.tsx, src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap, src/domains/setting/components/CreatePeer/__snapshots__/CreatePeer.test.tsx.snap, src/domains/setting/components/PeerForm/__snapshots__/PeerForm.test.tsx.snap, src/domains/setting/components/UpdatePeer/__snapshots__/UpdatePeer.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap, src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerTabs.test.tsx.snap, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
https://app.clickup.com/t/fez3w0
=> refactor: add dark mode styles to selected network option

.github/workflows/draft-artifacts.yml, .github/workflows/publish-release.yml, .github/workflows/test.yml, README.md, __tests__/unit/__utils__/setup.js, __tests__/unit/components/Transaction/TransactionForm/TransactionFormVote.spec.js, __tests__/unit/services/client.spec.js, __tests__/unit/services/crypto/transaction-signer.spec.js, config/networks/devnet.json, config/networks/mainnet.json, package.json, src/renderer/components/Passphrase/PassphraseInput.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue, src/renderer/components/Transaction/TransactionModal.vue, src/renderer/components/Wallet/WalletAddress.vue, src/renderer/models/network.js, src/renderer/services/client.js, src/renderer/services/crypto/transaction-signer.js, src/renderer/services/wallet.js, src/renderer/store/modules/network.js, src/renderer/store/modules/wallet.js, yarn.lock
=> chore: merge 2.0 to staging

src/domains/wallet/pages/CreateWallet/CreateWallet.tsx, src/domains/wallet/pages/CreateWallet/Step1.tsx
https://app.clickup.com/t/ff3g6b
=> refactor: show loading state during wallet creation

src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
https://app.clickup.com/t/ff3f68
=> chore: use `Header` component in create profile
