client/app/src/shapeshift/lib/shapeshift-api.js
According to docs: The typeof operator returns type information as a string. There are six possible values that typeof returns: "number," "string," "boolean," "object," "function," and "undefined.".
In the code - the comparission is done with 'String'  not 'string'. If data is object, new String('123'), then already first if gets executed, as typeof returns 'object'
=> Possible comparison bug?

README.md, package.json
Fixes a typo in the Linux deb synopsis. Screenshots adding some eye-candy.
=> fixing typo in deb synopsis and improving documentation

client/app/index.html, client/app/src/accounts/view/showTransaction.html
Show total fiat/bitcoin balance for all accounts on the homepage.
=> Total balance

client/app/assets/app.css, client/app/src/accounts/AccountController.js, client/app/src/accounts/view/createAccount.html, po/bg-BG.po
I read few posts that people just copy/paste the passphrase to create their account but forget to store the passphrase and therefore can't do anything with the received ARK in that wallet, from a delegate or somebody else. I believe this is a better and safer approach of creating the account, you can't just copy/paste the passphrase. This is also how Ledger Nano S works.
=> Safer account creation

client/app/src/network/NetworkService.js
The price API doesn't return the BTC price in satoshi showing confusing prices sometimes:
0.000121582 BTC
0.00012 BTC
etc.
=> BTC price in satoshi

client/app/src/accounts/AccountService.js
Some delegates like to advertise their username with uppercases and therefore it is not accepted. This will fix it.
=> Delegate username case sensitivity

client/app/assets/app.css
I get a vertical scrollbar when sending ARK and have a second passphrase even though my resolution is 2560x1600.
=> Send ark scrollbar

client/app/src/accounts/AccountController.js, client/app/src/accounts/view/manageNetwork.html
I've improved the "Manage Networks" functions.
If you add a new network, you don't need to re-render the full page, instead it is now adding just a new tab without even reload the modal. 
Also #126 is implemented. You now have the possibility to delete your own added networks. here is also no re-rendering needed as it updates "live"
=> Network Management Improvements

client/app/assets/app.css, client/app/index.html, client/app/src/accounts/view/addDelegate.html
Hello,
This commit includes two group of things: 
**I've refactored the menus a bit to include some icons**
**Current**
**Proposed**
---
**Current**
**Proposed**
Also fixed an issue with auto focusing and angular (see last screenshot "QUIT" is by default selected)
--> I've noticed that the "Vote delegate" dialog uses an anti-pattern in material-design guidelines. Particoularly the actions on the dialog are in the wrong order and not using the md classes: see difference:
***Current*** 
***Proposed***
=> Added some icons and css + fixed dialog wrong buttons positioning

package.json
Fixes macOS build issues.
macOS >= 10.12.0 would not ```npm run start``` after ```npm install```.
Throwing error: 
```bash
> ArkClient@1.3.0 start /Users/.../github/ark-desktop
> electron main.js
App threw an error during load
Error: Module version mismatch. Expected 50, got 53.
at Error (native)
at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
at Object.Module._extensions..node (module.js:583:18)
at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
at Module.load (module.js:473:32)
at tryModuleLoad (module.js:432:12)
at Function.Module._load (module.js:424:3)
at Module.require (module.js:483:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/Users/.../github/ark-desktop/node_modules/node-hid/nodehid.js:9:15)
```
After …
=> Remove deprecated 'electron-prebuilt'

client/app/src/accounts/AccountController.js
- added validateTransaction method to support the createSecondPassphrase method.  This method originally did not show the dialog to allow user to see the fee associated with this creation process and would blindly charge the user.
- there were some inconsistencies in createSecondPassphrase with the interchangeable use of 'account' and 'selectedAccount'.  This has been made consistent in this method to reflect the same use across other methods in the controller.
=> added validateTransaction method support for createSecondPassphrase 

client/app/index.html
Fix for #61. Sending ARK to yourself now shows up as grey instead of red.
Also fix for #259. Total now shows amount sent and amount received (ex. "-1.1 + 1") so that you can see how much you sent and got back.
=> Sending ARK to yourself now shows up as grey, not red

client/app/index.html
Fix for #204. The horizontal scrollbar at the bottom of the transactions list is now always visible when the main window is not wide enough.
=> Horizontal Scrollbar in Transactions list now visible w/o scrolling down

client/app/index.html
Was looking at issue number #244 and noticed that transactions wasn't translating so I fixed that. 
Looks like the issue with the word income and expend is that there are no translations in translations.js so those would need to be added?
Wondering where we could verify translations before adding those keys and their translations to each language! Or how to best to proceed to get those translations and then I'll add 'em!
=> Fixes transaction not translating next to income/expend issue #244

client/app/index.html
For the refresh button on the home page next to my accounts, when you click it now there isn't any response 
For user experience reasons I believe it'd be better that the icon, when clicked, gives some response back to the user, even if the amounts don't update. 
Not sure if I need to create an open issue for this, but the idea is simple and I think this would lead to a better UX.
=> Pressing refresh button now gives user a response

README.md, main.js, package.json
This PR adds something that I find very useful:
the `npm run-script live-reload` command will listen to changes in the project tree and will reload the Electron app.
=> Add live reload to Electron workflow

client/app/src/accounts/account.controller.js
This is the previous behaviour when starting (or restarting) the app:
Now it shouldn't occur.
=> Avoid showing several "toasts" while the app connects to the network

client/app/assets/app.css, client/app/index.html, client/app/src/accounts/account.controller.js
Before:
After:
I've discovered that there are 2 missing translations:
- Currency
- Play song when receive funds?
=> Improve settings menu UX

client/app/src/accounts/account.controller.js
Noticed that Spanish wasn't added as a language choice, and it's fully completed here 
http://osjc1wl.oneskyapp.com/collaboration/project?id=95031
Now you can select Spanish, the translations work from what I saw. 
I put it under Greek since the code for that is el: and I noticed that the languages was in alphabetical order but English.
=> add spanish as a language choice

client/app/index.html
Currently if you hover over the send button and edit contact button it doesn't show any text, but the export account does. This fixes it so the word send and edit contact will show over the hovers of the icons.
=> now when you hover over the icons in wallet page, will show text

client/app/src/accounts/account.controller.js, client/app/src/components/addressbook/addressbook.controller.js, ledger-worker.js
Hey guys, I noticed that we don't have strict-mode set for all services/controllers. Now we will be able to handle some errors in `account.controller`.
Cheers.
=> Add 'use strict' into all services/controllers

client/app/src/accounts/account.service.js, client/app/src/components/addressbook/addressbook.controller.js
These changes avoid using the same contact name several times. It also avoids creating contacts that have the same name or address than any user address.
BTW: these errors don't seem to be translated.
=> Avoid duplicated contacts or contacts that are the same that user addresses

client/app/src/components/qrScanner/qrScanner.html
Hi. I noticed that in the qr code directive, the AccountController is not in scope.
Now it will follow the selected theme.
=> Fix theme on qr code dialog

client/app/src/accounts/account.controller.js
Previously, if a currency was not set, the currency option in the settings menu would be blank even though the currency defaulted to BTC. The currency still defaults to BTC, but it will now show in the settings menu that the currency is BTC. It also makes sense to make BTC first in the list as it's more universal than USD (which was first in the list).
=> Set BTC to default currency and first in currencies list

client/app/index.html
Buttons in the Application Menu now fill the width of the menu, like the Settings Menu.
=> Fix Application Menu to match Settings Menu

client/app/index.html, client/app/src/accounts/account.controller.js, client/app/src/accounts/account.service.js
This covers 2 issues:
- Could not rename a virtual folder at all. The option did nothing.
- Prevents adding the same foldername twice, showing a message to that effect.
=> Fixes for virtual folders

client/app/index.html
This is to fix initial add of contact. If you guys could test please, that'd be great!
Edit: to clarify, the issue is when a contact is first added to the client. Removing and re-adding doesn't work. Complete reset of data is required to replicate the issue (prior to my changes). After resetting the data, click on the "Add Contact" button in the left sidebar and add a new contact. It won't appear until a reload
=> Use single AddressBookController for account view

client/app/src/accounts/account.controller.js, client/app/src/accounts/account.service.js
This fixes an issue with not being connected to a network, when importing or creating an account it just does nothing with no feedback at all. I've implemented a toast notification when clicking "Import Account" or "Create Account" - see below. Feel free to test the before and after of not being connected to a network to see the issue I'm referring to.
=> Stop Import/Create account if no network

.travis.yml
The Travis build was always failing because it was missing libusb-1.0-0-dev
=> Added libusb to Travis addons

main.js
Because Electron doesn't have content protection on Linux, I think the screenshot protection settings button should be disabled on Linux. Users shouldn't be given an option that they may think provides some security if the option actually does nothing, it's misleading.
Resolves #336
=> Disable screenshot protection setting if the platform is linux

client/app/index.html
Tooltip shows the actual number once well confirmed. This is the way the new explorer displays confirmations, so I updated this to match.
=> Show 'Well Confirmed' once the number of confirmations is greater than 50.

client/app/index.html
Now when you hover over the address it'll say Copy address or the public key
=> added copy address or copy public key when you hover over that

client/app/assets/app.css, client/app/src/accounts/account.controller.js, client/app/src/accounts/view/manageBackground.html
Allow the user to upload custom backgrounds. Resolves #320
=> Custom Backgrounds

ledger-worker.js, main.js
An issue was reported on [reddit](https://www.reddit.com/r/ArkEcosystem/comments/77tjkj/uninstalled_ark_client_taking_over_computer/) saying that instances of Ark were still running after the client was closed. I found that the ledger-worker was not being closed when ArkClient was closed, so ledger-worker.js and main.js were still running.
I fixed it by calling process.exit() in ledger-worker when it receives a quit message. All parts of the client now exit completely when the window is closed.
=> Exit ledger-worker process on quit signal

CONTRIBUTING.md, package.json, test/components/addressbook/addressbook.controller.js, test/e2e/commands.js, test/e2e/hooks.js, test/e2e/scenarios/accessibility.js, test/e2e/scenarios/client.js, test/e2e/scenarios/create-account.js, test/e2e/scenarios/create-network.js, test/e2e/scenarios/select-network.js, test/e2e/scenarios/settings-menu.js, test/e2e/user_data.js, test/karma.conf.js, test/services/network.service.js
This PR adds StandardJS (#323) with the configuration for this project.
I've adapted the code under the `test` folder to that code style too. The rest of the code should be done incrementally because it is composed of a lot of different parts.
=> Add StandardJS (closes #323)

client/app/index.html
The tooltip does not translate correctly because the translation tag does not work with properties inside
=> Fix translate tag on public key tooltip

client/app/src/accounts/account.controller.js, client/app/src/accounts/view/sendArk.html
When sending Ark, the list of addresses/names that popup now shows your accounts and contacts, not just contacts. They are also sorted by account label / contact name.
Partially addresses #368
=> Add accounts to list of addresses to send Ark to

client/app/src/services/network.service.js
This is to improve the initial connection to the network. More recently, there's been a lot of connect/disconnect activity. It now looks for the best peers based on highest Block Height, and lowest Delay.
@luciorubeens I couldn't use orderBy - it just didn't work (silently failing). Instead, I did this. I also didn't store in the serviceProvider as suggested, so i check on the first index of getGoodPeer and sort then, once.
Feedback welcome!
=> Sort peers & fix bug with filtered peer status

Gruntfile.js, LedgerArk.js, client/app/app.js, client/app/config/config.js, client/app/index.js, client/app/plugins/sample/plugin.js, client/app/src/accounts/account-transactions.controller.js, client/app/src/accounts/account.controller.js, client/app/src/accounts/account.service.js, client/app/src/addons/pluginLoader.addon.js, client/app/src/components/addressbook/addressbook.controller.js, client/app/src/components/qrScanner/qrScanner.controller.js, client/app/src/components/qrScanner/qrScanner.directive.js, client/app/src/components/shapeshift/ShapeshiftService.js, client/app/src/directives/backgroundStyle.directive.js, client/app/src/directives/copyToClipboard.directive.js, client/app/src/directives/validAmount.directive.js, client/app/src/filters/filters.js, client/app/src/init.js, client/app/src/services/changer.service.js, client/app/src/services/config.service.js, client/app/src/services/ledger.service.js, client/app/src/services/network.service.js, client/app/src/services/storage.service.js, client/app/src/services/time.service.js, client/app/src/services/toast.service.js, ledger-worker.js, main.js, package.json, utils.js
Hi, i formatted the code using the standardjs, this is a lot of changes but I just removed the spaces, the semicolons and other minor changes. So do not worry about merging this or validating each line.. Cheers!
=> [Lint] Format code

client/app/src/accounts/account.controller.js
Updated so the languages are in alphabetical order. Fixes issue #393.
=> languages now alphabetical fixes #393

client/app/assets/app.css, client/app/src/accounts/account.controller.js, client/app/src/services/toast.service.js
HI! This fixes issue #399 + minor theming tweaks
=> Theming#399

client/app/src/components/addressbook/addressbook.controller.js
Dialog doesn't close once contact is added. Beautiful one-liner 👌 
Edit: No longer a one-liner (thanks @boldninja)
=> Fix Add Contact

client/app/src/components/account/templates/offchain-tab.html, client/app/src/components/dashboard/market-box.html, client/app/src/components/layout/main-navbar.html
Noticed in some places that we weren't utilizing the filters when possible, went ahead and fixed it in a few html files.
=> Use filters amountToCurrency and formatCurrency

client/app/assets/app.css, client/app/src/accounts/account.controller.js, client/app/src/components/account/templates/account-card.html, client/app/src/components/dashboard/account-box.html, client/app/src/filters/filters.js
I noticed that when you click the refresh button no _progress_ and no _feedback_ is provided.
I added an animation to the refresh button when a refresh is being done (which most often you can't even see because it's too fast - but you never know.. ;) ) and added feedback (toast) when the refresh is done.
The whole thing looks like this (note: I added a manually timeout of 3000ms for demo purposes):
I also disabled "button-spamming" which basically means when a request is already executing clicking the button again will not do another request.
I have 3 questions:
- What do you think in general? ;)
- In the error case should the user get a specific error message or is my implementation enough?
- Concering translations: Is it correct that I just pass them as a normal string to the toast …
=> Provide feedback when user refreshes account

client/app/assets/app.css, client/app/src/components/account/templates/offchain-tab.html, client/app/src/components/account/templates/transaction-tab.html
I noticed that the actual Ark values (total) are not selectable because they are "disabled buttons".
This really bugged me since all other values in this table are selectable and the value is in my opinion one of the most important things and should definitely be selectable.
So what I did the following:
Changed them all to `span`'s, gave them the button style and removed (with a second class) the styles which made the text not selectable.
The before and after look was the exact same for me :)
Let me know what you think!
Note that this is my first commit here and I'm not sure if my apporach is good :)
BTW: There may be other places in code where this should be done, but I thought before I look for them I wanted to get feedback on this.
=> Make Ark values in transaction tab selectable

.gitignore, client/app/config/config.js, client/app/src/accounts/account.controller.js, client/app/src/accounts/account.service.js
Some people on the subreddit were mentioning there wasn't any popup or information about how creating a second passphrase costs ark. This toast warning message should popup and warn them how much it'll cost!
=> Add confirmation to warn user of the cost of second passphrase

client/app/src/components/dashboard/market-box.html, client/app/src/components/layout/main-navbar.html
Toggling BTC using the button wouldn't update the market box to show BTC. We want to store the original/current currency for the toggle though, so we can't just overwrite currency to be btc. 
Updated so the filters pass in isBitcoinToggle.
=> noticed toggling btc didn't change market to btc values

client/app/src/accounts/account-transactions.controller.js
Thanks to Thomgru for the suggestion in #457
=> doesn't scroll to top of transactions on refresh fixes #457

client/app/src/components/account/account-card.controller.js, client/app/src/components/account/templates/send-transaction-dialog.html, client/app/src/components/qr-scanner/qr-scanner.directive.js
Problem was that `ng-model` is not supported on `md-autocomplete`.
To work around this we have to set the `selectAddress` property which is used on the `md-autocomplete`. However we cannot really set the field directly from the qr scanner directive (because it a "contact").
My solution was to introduce a callback-function parameter (which I personally find nicer anyway, instead of having to relay on, that the object path `send.data` exists).
Please note that I'm not very good with angular 1 - and it may very be possible that there is a better fix for this. I'm always open for feedback :)
fixes: #454
=> Fix that qr scanner doesn't work correctly for 'To' field

client/app/index.html, client/app/src/accounts/view/createDelegate.html, client/app/src/accounts/view/createSecondPassphrase.html, client/app/src/accounts/view/importAccount.html, client/app/src/accounts/view/signMessage.html, client/app/src/accounts/view/timestampDocument.html, client/app/src/accounts/view/vote.html, client/app/src/components/account/templates/send-transaction-dialog.html, client/app/src/components/passphrase-field/passphrase-field.controller.js, client/app/src/components/passphrase-field/passphrase-field.html, client/app/src/components/qr-scanner/qr-scanner.directive.js
While doing "a little" testing for my other PR I saw that the input (password) field of the passphrases is different depending on where you are:
- sometimes you can toggle "view password" (eye icon)
- sometimes there is a qr-scanner symbol
Also the same code was duplicated throughout the solution.
I extracted the logic into an own component and used this in the whole app.
Now everytime the user has to input the first or the second passphrase.
The field with the visibility togglet button and the qrcode scanner is displayed.
While doing that I one question came up:
- Somehow the `md-required` class was not set automatically anymore on the label (because it's an own component now). So I did this manually. I don't understand why it is not set anymore and I wonder if I'm doing something …
=> Unify passphrase input in the whole app

LedgerArk.js, client/app/app.js, client/app/src/accounts/account.controller.js, client/app/src/accounts/account.service.js, client/app/src/components/addressbook/addressbook.controller.js, client/app/src/services/config.service.js, client/app/src/services/ledger.service.js, client/app/src/services/network.service.js, main.js, test/e2e/hooks.js, test/e2e/scenarios/accessibility.js, test/e2e/scenarios/client.js, test/e2e/scenarios/create-account.js, test/e2e/scenarios/create-network.js, test/e2e/scenarios/select-network.js, test/e2e/scenarios/settings-menu.js, test/e2e/user_data.js
The problem was that when we `require`d a file (e.g. `arkjs`), we did so with relative paths and forward slashes (`/`). 
Funny enough when you execute `npm start` it worked on windows, but the unit tests did not.
You always got something like this:
```
Electron 1.7.9 (Node 7.9.0) AccountController "before each" hook for "returns the user accounts only" FAILED
Error: Cannot find module 'E:devgitark-desktop  est/../client/app\../../package.json'
at Module._resolveFilename (module.js:470:15)
at Function.Module._resolveFilename (E:\dev\git\ark-desktop\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
at Function.Module._load (module.js:418:25)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at window.require …
```
=> Unit tests now work on windows

client/app/src/components/dashboard/network-box.html
Currently clicking on MAINNET or the peer ip address calls a function. I added the tooltip so that people know exactly what is going to happen before it occurs.
=> added tooltips to peer buttons

client/app/src/accounts/account.controller.js, client/app/src/components/account/templates/account-card.html, client/app/src/components/account/templates/signing-tab.html, client/app/src/directives/copy-to-clipboard.directive.js
Previously what happened was ng-click -> called copyToClipBoard which always showed a successful toast message.
Passed in the toastService into the copy directive, so now what happens is the toast service will show the correct response. 
Partially inspired by a reddit post where the user stated that it would say copied to clipboard but then would not be able to past it.
=> Moved toastService into copy directive

client/app/assets/app.css
Very small change, not necessary at all, but it was bothering me to have that error, so I decided to fix it. 
Fixes Electron Helper[14028:538660] Couldn't set selectedTextBackgroundColor from default ()
error that you get at startup
=> fixes couldn't set selectedTextBackgroundColor

test/components/addressbook/addressbook.controller.js
Posting this here even though it isn't done because I wanted to get some feedback to see if I was doing it right! 
@j-a-m-l  @perryhoffman (saw your unit tests from earlier)
=> Add Unit Tests for Adding Contacts

client/app/src/components/account/templates/transaction-tab.html
A minor thing I saw when testing:
If you send yourself something (which obviously apart from the darknet nobody does) the transaction explorer showed it like this:
However this is wrong, since you did not magically get `+3` ark and only lost the fee cost.
Correct would either be to show only the fee as a negative value or - and that's what I've done - show it like this:
I wonder if the background-color shouldn't be "negative" (`default-red-200`)?
=> Fix wrong display of amount in transaction list (if sender==receiver)

client/app/index.html, client/app/src/accounts/account.controller.js, client/app/src/accounts/account.service.js, client/app/src/accounts/transaction-builder.service.js, client/app/src/components/account/account-card.controller.js, client/app/src/components/addressbook/addressbook.controller.js, client/app/src/services/utility.service.js, test/accounts/account.controller.js, test/components/accounts/account-card.controller.js, test/components/addressbook/addressbook.controller.js, test/karma.conf.js, test/services/transaction-builder.service.js, test/services/utility.service.js
So I decided to tackle this guy! Took me quite a while to figure out the main problem :)
Main problem was:
In the desktop we already used the method `getFees` to get fees from the network, however we then used `arkjs` to create our transactions. `arkjs`  always uses the default values for all fees of all transaction types (see here for an example: https://github.com/ArkEcosystem/ark-js/blob/0b8d460a54657b24703e0b7fe59cf2067e00491b/lib/transactions/vote.js#L30 ) and we did never overwrite them.
So basically if a network had different fees for a transaction type, we ignored it and just used the default value...
Secon problem:
When clicking "Send all" in the send dialog, we used a hardcoded fee type, instead of the one from the network (however this is just a ui bug).
**NOTE:**
I will …
=> Fix multiple bugs with fees & refactor

client/app/src/accounts/account.controller.js, client/app/src/accounts/account.service.js, client/app/src/accounts/export-account.controller.js, client/app/src/accounts/transaction-builder.service.js, client/app/src/components/account/account-card.controller.js, client/app/src/components/addressbook/addressbook.controller.js, client/app/src/components/dashboard/account-box.controller.js, client/app/src/constants/constants.js, client/app/src/directives/valid-amount.directive.js, client/app/src/filters/filters.js, client/app/src/services/utility.service.js, test/accounts/account.controller.js, test/accounts/account.service.js, test/components/accounts/account-card.controller.js, test/components/addressbook/addressbook.controller.js, test/components/dashboard/account-box.controller.js, test/karma.conf.js, test/services/transaction-builder.service.js, test/services/utility.service.js
- Fixes harcoded 'Ark' and 'Ѧ' values (only seen by accident)
- Move all Arktoshi calculations to `utilityService` and use the service everywhere
- Remove `networkService` dependency from `utilityService`
- Introduce constant for ark launch date
- Move all ark relative date calculations to utility service
- Improve all tests (instead of having to define `ARKTOSHI_UNIT` everytime, just inject our constants and use them if needed)
=> Move utility functions to utility services, minor bug fixes

client/app/src/components/account/account-card.controller.js, client/app/src/components/account/templates/account-menu.html, client/app/src/components/account/templates/send-transaction-dialog.html
Currently the address is displayed, but it would be more human-friendly showing the label of that address too.
=> Show the label of the account on the menu and the sending ARK dialog

client/app/src/accounts/account.controller.js, client/app/src/accounts/view/importAccount.html
People all the time mistyped their passphrase when importing account and then panic when see an empty wallet. This PR should fix this:
- after clicking IMPORT I'm checking if the passphrase is a valid BIP39 mnemonic, if not, toast an error message: "Not valid 12 words passphrase! Please check all words and spaces."
- added a switch "custom passphrase", so you still can import with custom passphrase
=> Validate passphrase when importing account

client/app/src/components/account/votes-tab/templates/vote.dialog.html, client/app/src/components/account/votes-tab/vote.dialog.controller.js
I wonder why does the  method `accountService.getPassphrases` even exist? It's a little confusing, because apparently it just get's the passphrase from the store, but we (hopefully) never store them anyway.
Ok just checked:
There are methods for saving the passphrases, but they are not used anymore.
Wonder if we should remove these methods altogether (in a separate PR maybe)
@perryhoffman Maybe you have any feedback on this, since you know this voting-area well ;)
fixes: #526 
fixes: #525
=> Fixes voting with second passphrase enabled

client/app/src/accounts/account-transactions.controller.js
Happens when you create / import a new account which has no transactions.
=> Fix bug 'Cannot set property 'scrollTop' of undefined'

client/app/assets/app.css, client/app/index.html, client/app/src/accounts/account.controller.js, client/app/src/components/addressbook/addressbook.controller.js, client/app/src/components/dashboard/account-box.controller.js, client/app/src/components/dashboard/account-box.html, client/app/src/components/dashboard/dashboard.controller.js, client/app/src/components/dashboard/templates/dashboard.html, client/app/src/services/utility.service.js, test/components/dashboard/account-box.controller.js
In the current version of the client it's not possible to...
- ... create a contact (read only account) WITHOUT having to import a generate a "real account" first (ok that's a lie, you can do it via the menu, but you don't see the contact anywhere after that)
- ... go directly to a contact (read only account) (you have to select a "real account" first and can only then select a contact on the left side)
This really ~~hurts my feelings~~ bothers me when I want to install the wallet and only add read-only accounts (for example on an "unsafe computer").
I'd like to implement this and gave this some thoughts on how to integrate it smoothly in the UI.
I don't think adding another box would be a good idea, since the space is, both in the horiztonal and in the vertical, not enough.
The only good …
=> Make it possible to access contacts / Read-Only accounts from Dashboard

client/app/index.html, client/app/src/accounts/account.controller.js, client/app/src/components/account/account-card.controller.js, client/package-lock.json, client/package.json, main.js, package-lock.json, package.json
Edit: It will not work on Linux because we can't upgrade the [Electron to version 1.8.1](https://github.com/electron/electron/pull/10670) since the [`node-hid` does not support it yet](https://github.com/node-hid/node-hid/issues/233).
=> Add support to Ark URI scheme [AIP-13]

client/app/src/accounts/account-transactions.controller.js, client/app/src/accounts/account.controller.js, client/app/src/accounts/view/validateTransactionDialog.html, client/app/src/components/account/templates/main-sidenav.html, client/app/src/components/account/templates/send-transaction-dialog.html, client/app/src/components/dashboard/account-box.html, client/app/src/services/transaction-sender.service.js, test/accounts/account.controller.js, test/accounts/account.service.js, test/services/transaction-sender.service.js
This does the following:
- On type in address field now also works for wallet labels (did only work for contacts before)
- Form cannot be sent if address is empty
- Known addresses (contacts & wallet labels) are now always resolved and displayed below the field (it always bothered me, that you selected a contact, but didn't know which one it was after you did so, because only the address was displayed). I'm not yet sure if it's optimal from a UX standpoint:
- Contacts & wallets can now be resolved without explicitly clicking on it in the dropdown (this only works if you type it 100% correctly, also it only works if the contact is non-ambiguous). Also while you're still typing the `Invalid Address` error is not shown if you're typing the name of a contact.
- If the contact is ambiguous for …
=> Resolve contacts in send form & optimizations

client/app/src/components/account/templates/main-sidenav.html
The commit fixes that the contact information icon is not shown if the selected account is the contact itself, since it was very confusing.
----
Also I'd like to start a small discussion to this:
I never really understood the information here. Actually I thought they were wrong and started to fix them before I realized what they are.
For those who don't know:
- Income
- Transactions which were sent FROM the contact TO the currently selected account (in my case from `delphin` to `Delphin` (sorry for the similar names :P )
- Expense
- Transactions which were sent TO the contact FROM the currently selected account (`Delphin` to `delphin`)
I wonder if it would help if we would just change:
- `Income` => `Received From`
- `Expense` => `Sent To`
Though I'm not sure if this would make it …
=> Improve Contact information

client/app/src/accounts/account.controller.js, client/app/src/services/network.service.js
The error is only shown if the transaction to the peer fails.
If any further broadcasts fail we show nothing.
I wonder if we should do something in this case?
Log somewhere (console :P)
@doublehelix24 If you want you can test it and give feedback :)
fixes: #518
=> Show error messages when a transaction fails

client/app/src/services/transaction-sender.service.js
If you paste an address directly in the address field it was an object `{address: <address>}`.
If you then clicked send this resulted in an exception:
```
dependencies.min.js:1 TypeError: $scope.data.toAddress.trim is not a function
at Scope.$scope.submit.tab [as submit] (transaction-sender.service.js:100)
at fn (eval at compile (dependencies.min.js:1), <anonymous>:4:202)
at callback (dependencies.min.js:1)
at Scope.$eval (dependencies.min.js:1)
at Scope.$apply (dependencies.min.js:1)
at HTMLButtonElement.<anonymous> (dependencies.min.js:1)
at defaultHandlerWrapper (dependencies.min.js:1)
at HTMLButtonElement.eventHandler (dependencies.min.js:1)
```
Should probably be reviewed by @j-a-m-l . Since he "introduced" this, maybe it has a meaning or got forgotten while refactoring?
=> Fix that toAdress was sometimes an object

client/app/src/accounts/account.controller.js, client/app/src/accounts/view/manageNetwork.html, client/app/src/components/layout/main-navbar.html, client/app/src/services/network.service.js
This PR solves various things:
- don't add network directly after create was pressed
- an angularjs error which was displayed because `$scope.apply()` was called
- only the "active network" is saved, when save was pressed (before all networks were saved). Imho both approaches are not optimal but I find it more user friendly this way
- fix that position of settings menu changed, when there was no `currency` menu item:
Fixes: #549
=> Save network not directly after create was pressed

main.js, package.json
Find it a good input and it annoyed me anyhow that the protection was always enabled while developing, so I used this opportunity to disable it by default when developing.
Since having this disabled is a quite special / technical requirement, I did it via an argument which has to be passed to the client. This way no one can accidentally disable the screenshot protection on his machine.
Resolves: #540
=> Make screenshot protection configurable

client/app/src/components/account/templates/transaction-tab.html
Show tooltips when the text is elided.
=> Add transactionId, senderId and recipientId tooltips

client/app/src/accounts/account.controller.js, client/app/src/components/loading-dialog/loadingDialog.html, client/app/src/services/dialog.service.js
- implement it so that it can also be used in other places
To test:
- go to the `network.service.js` file.
- replace `return window.location.reload()` with `setTimeout(() => return window.location.reload(), 10000)` in the method `switchNetwork`.
fixes: #560
=> Add loading indicator when switching network

client/app/src/services/network.service.js, client/package-lock.json, client/package.json
Implemented as follows:
- The mainnet (ark) and the devnet (dark) networks are now created with the values from `ark-js`. 
- Because of this the `peerseed` of the mainnet (`http://5.39.9.240:4001` => `http://node1.arknet.cloud:4001` ) and the peerseed of the devnet  (`http://167.114.29.55:4002` => `104.238.165.129:4002` ) are now different!
-   I did not come up with these values myself, they are the same as we use in `ark-ts`
- ~I used the `pubKeyHash` as the `version`. I'm not sure if this correct :P For `Ark` it appears to be the same value, but for `DARK` it changed from `30` to `0x52`. Sorry if this is wrong, I think I don't even fully understand what the difference between these values is (if there is any). But it's not the same, I think it wold be good to add the version to the …
=> Make ark client work if main peerseed is down on fresh-install

client/app/src/accounts/transaction-builder.service.js
This is in conjunction with https://github.com/ArkEcosystem/ark-js/pull/53 whereby the fees can be customised on bridgechains. With the desktop wallet, we already fetch the fee from the network, but we're now passing those fees into the create transaction methods to correctly build a transaction object.
@luciorubeens @j-a-m-l if you could take a look and have a quick test, that would be great! Thanks
=> Fee override from the network

client/app/src/accounts/account.controller.js, client/app/src/accounts/view/manageNetwork.html, client/app/src/accounts/view/switchNetworkDialog.html, client/app/src/directives/background-style.directive.js, client/app/src/services/network.service.js
Also fixes a bug related to the background.
```
dependencies.min.js:1 TypeError: Cannot read property 'match' of undefined
at scope.$watch (background-style.directive.js:40)
at Scope.$digest (dependencies.min.js:1)
at Scope.$apply (dependencies.min.js:1)
at dependencies.min.js:1
at Object.invoke (dependencies.min.js:1)
at doBootstrap (dependencies.min.js:1)
at bootstrap (dependencies.min.js:1)
at angularInit (dependencies.min.js:1)
at dependencies.min.js:1
at HTMLDocument.trigger (dependencies.min.js:1)
```
Fixes: #565
=> Switch the network if removing the active network

main.js
With #558 happened some changes in the menu.
On windows (can't speak for other systems) there is now a bug that the `Reload` command doesn't work anymore via keyboard - this PR fixes this.
However I also saw that some commands which were previously there are now missing, I don't know if they were omitted or changed on purpose, so I didn't change anything yet:
- `About ArkClient` became `About Electron` 
- pretty sure this is wrong and should be changed back right?
- `Maximize` is missing
- `Full Screen` is missing
- `Quit` was removed from `Application` and is now instead called `Close` beneath `Window`
- I personally liked `Quit` more below application (or both)
@gabrielbull  @alexbarnsley
=> Fix broken reload command on Windows

client/app/src/accounts/account.service.js
alexbarnsley requested that I send this PR.
When attempting to register a delegate, there were cases where the regex name validation would flag a valid name as invalid.  This appeared to be tied to multiple calls to the regext.test(....) function with the "g" option enabled on the regex.  Removing the "g" option appears to fix the issue.  Javscript is not my first language but it appears that this type of behavior is not uncommon when using the "g" option due to some sort of state preservation between calls.
Repo Steps:
1. Open the register delegate dialog
2. Click in the username edit box and type in a valid username
3. Press the tab key twice to move focus to the pass phrase edit box. (Note:  The tabs may not be strictly necessary but I observed consistent results with this)
4. Enter …
=> Remove global flag on regex validation of delegate name.

client/app/src/services/neo-api.service.js, client/app/src/services/transaction-sender.service.js
On the send transaction dialog, it's more common than expected that addresses are flagged as NEO.
The problem was that our current implementation was expecting that the NEO API endpoint returned a different response when NEO addresses have transactions. Instead it was asking about the unclaimed GAS.
=> Warn about NEO addresses only when they have transactions

src/renderer/components/Wallet/WalletRenameModal.vue
It wasn't possible to remove the name of a wallet, as you would get an error saying that `''` was already taken as a wallet name. This PR makes it possible to rename a wallet to `''` again so it reverts to the original address (or delegate / contact name).
=> feat: make it possible to remove the set name of a wallet

src/renderer/components/Transaction/TransactionShow.vue
Sender incorrectly pointed to recipient in explorer, fixes #657
=> fix: use sender instead of recipient for sender links

src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
Disables the "Send all" toggle when there are not enough funds available to cover amount + fees. Proposed by @zillion in response to #652
=> feat: disable send all button when funds are too low to send all

src/renderer/components/Input/InputCurrency.vue
You couldn't input 0.0000001 as it would be turned into 1e-7:
Now it's fixed and possible to input the correct amount:
=> fix: make it possible to input small numbers into the input field

src/renderer/mixins/wallet.js
This fixes an issue where it checked for a ledger wallet only if the local database didn't have a record. This caused issues if the ledger wallet was added as a contact, for example. Meaning when a ledger wallet was plugged in and viewed, the wallet thought it was a contact, resulting in the inability to send transactions.
Resolves #634
=> fix: get ledger wallet first from route

__tests__/unit/services/synchronizer/wallets.spec.js, config/index.js, src/renderer/components/Transaction/TransactionTable.vue, src/renderer/components/Wallet/WalletTransactions/WalletTransactions.vue, src/renderer/i18n/locales/en-US.js, src/renderer/services/synchronizer/wallets.js, src/renderer/store/index.js, src/renderer/store/modules/transaction.js
(ignore the branch name - i'm considering this a feature instead of a fix)
The app now has a hardcoded 45 minute value for how long it takes for transactions to expire. This is set in core, and there's no endpoint that provides this value. I thought about adding a network modal field, but I didn't want it to confuse users when adding custom networks. It can be added in the future if it causes issues.
To sum up, an unconfirmed transaction is stored in the local database. This remains until the transaction is processed and received, or the 45 minute period ends. At this point it is removed from the local database. If a wallet is in view with a transaction that expires, it will get a ~strikethrough~ and remain the unconfirmed grey.
Resolves #644
=> feat: persist unconfirmed transactions

src/renderer/pages/Wallet/WalletImport.vue, src/renderer/pages/Wallet/WalletNew.vue, src/renderer/services/wallet.js
Show the public key also for wallets that are not on the blockchain yet, fixes #648 
This only works for importing an address by passphrase, or when generating a new one. In case of just an address we cannot determine the public key, so that one will be updated automatically when the wallets sends its first transaction.
=> feat: show public key of newly created address in wallet

src/renderer/components/Modal/ModalQrCodeScanner.vue
Adds a workaround to have the camera stream loaded before closing the component, which could result in the camera staying on as it was unable to properly close the stream. I've opened an issue in the repo of the QR scanner component we use, but so far the workaround proposed there did not solve it.
Testing it can be done as follows:
- Without the fix: go to the send screen and press the QR code and immediately close the modal (e.g. by clicking outside of it). The camera should turn (you can see this if you have a camera light indicator) on slightly after the modal is closed, but won't turn off unless you reload the wallet.
- With fix: go to the send screen and press the QR code and immediately start clicking outside (keep clicking) to close the modal as soon as the `isLoading` property is …
=> fix: add workaround to have camera stream loaded before closing

__tests__/unit/pages/Profile/ProfileAll.spec.js, __tests__/unit/pages/Wallet/WalletAll.spec.js, __tests__/unit/store/modules/profile.spec.js, src/renderer/pages/Profile/ProfileAll.vue, src/renderer/pages/Wallet/WalletAll.vue, src/renderer/store/modules/profile.js
This PR includes the balance of the Ledger wallets on the wallets page and the profiles page. On the profiles page it only includes the balance of the wallets of the current network.
Resolves https://github.com/ArkEcosystem/desktop-wallet/issues/632.
=> fix: include the Ledger wallets when computing the total balance

src/renderer/App.vue, src/renderer/components/App/AppSidemenu/AppSidemenu.vue, src/renderer/pages/Wallet/WalletAll.vue
This PR separate the logo in the sidebar and also refactor to fix the overflow.
=> refactor: separate logo in the sidebar

src/renderer/components/Button/ButtonReload.vue
Disables the reload button when `isRefreshing` is `true`.
=> fix: disable reload button while refreshing

src/renderer/pages/Contact/ContactAll.vue, src/renderer/pages/Wallet/WalletAll.vue
Wallets / contacts faded when you hovered over them, but if you moved away they would immediately go back to their original which looks odd. So this PR adds a fade transition when the item is no longer hovered (don't mind the missing colors in the before gif):
Before:
After:
=> fix: fading out of wallet / contact

src/renderer/components/MarketChart/MarketChart.vue
Fix: Market Chart loading twice each time you change the period.
Whenever we changed period, renderChart() was being called twice. As a result chart appears to be rendering two times everytime you change the period.
Firstly, changePeriod function was triggering renderChart, later the watch function period triggers renderChart since period was changed.
Watched property 'period' has been removed.
Since changePeriod will be used on whenever period is changed, therefore period watch can be safely removed.
This removes the above described bug and at the same time reduces a watched property.
=> Bug:Fix  loading of chart two times

.circleci/config.yml, README.md, package.json
Basically, this would be useful when executing E2E tests without changing the files of `src`.
=> chore: add a new version  (`test:e2e:build`) of the script to run E2E tests

src/renderer/components/Wallet/WalletRenameModal.vue
When changing the name of a ledger wallet, it was saving the name of the wallet before the name was updated. E.g. renaming a wallet from "Ledger 1" to "Business Ledger" would save "Ledger 1". This is the wrong order.
=> fix: ledger wallet rename saving old name

.eslintrc.js, src/renderer/components/App/AppIntroScreen.vue, src/renderer/components/App/AppWelcome.vue, src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
The `<i18n>` does not work when written in PascalCase (`<I18n>`) as required by the current lint rules. This PR adds the i18n tag to the eslint ignore rules.
=> fix: add i18n to eslint ignore

src/renderer/App.vue, src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
#671 introduced a way to disable screenshot protection on launch, but it was set in the appsidemenu. This means that it got only triggered after the sidemenu got openend, which resulted in still not being able to take screenshots in dev mode when you hadn't touched the sidemenu yet. This PR moves it towards the `App.vue` file so it gets set immediately upon launch.
=> fix: set screenshot protection upon app launch instead of sidebar

.circleci/config.yml
Removes the yarn installation step from CircleCI, since yarn comes with the *-browsers images by default and the updated version isn't being used in the subsequent steps anyway.
=> chore: remove yarn installation from circleci

src/renderer/pages/Wallet/WalletShow.vue
If viewing a wallet on the ledger and the ledger disconnects, the wallet page disappears. This fix takes the user to the wallet list in this scenario.
=> fix: go to wallet list on ledger disconnect

src/renderer/components/Button/ButtonClipboard.vue, src/renderer/components/Transaction/TransactionTable.vue
As I've explained in a comment, this is probably related to https://github.com/LinusBorg/portal-vue/issues/159. I'll be watching that issue to provide a definitive solution.
=> fix: do not throw an Error when closing `TransactionShow`

src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
While registering for 2nd passphrase.
Follow these steps to reproduce the bug:
-If you generate a 2nd passphrase
-Then tap next
-Then verify the passphrase (by entering 3,6,9 th words)
-Tap Back
-Generate a new 2nd passphrase
-Tap next
-You will be able to continue without entering correct passphrase
This has been fixed by using the rest function from the generateNewPassphrase function.
=> Bugfix : Validation after after regenerating 2nd passphrase

src/renderer/components/Input/InputSwitch.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
The text of "Send All" was not correctly displayed:
I've tried the changes on the import wallet page and the sidemenu settings, and it looks OK on both.
=> fix: do not show "Send All" in 2 lines on transfer modal

src/renderer/components/App/AppSidemenu/AppSidemenuImportantNotification.vue
The version notification tooltip is not displayed correctly.
Setting the `boundariesElement` of the tooltip to `body` fixes this issue.
=> fix: version notification tooltip boundaries

src/renderer/App.vue
On smaller resolutions the blur effect is applied only to the main section, but not to the navbar, which is a sibling element. This PR adds the blur class on both elements.
=> fix: apply blur also to navbar

src/renderer/components/Network/NetworkModal.vue
#680 introduced validation for adding a network, but that made it impossible to add a new network since all fields were checked in the validation (instead of the 3 that were on screen). This PR improves the validation rules so the rest of the fields are only checked when necessary.
Resolves #769 
Also fixes an issue where the input would show a message that the value is required whenever the input field became dirty (even though there was a value in it). This has now been changed to only trigger if it's required + the input field is empty.
=> fix: resolve validation issues making it impossible to add a network

src/renderer/components/Wallet/WalletHeading/WalletHeading.vue
#759 introduced resetting the wallet buttons when the wallet was changed, but this was done by watching the `currentWallet` property for changes. This property "changes" every x seconds due to refreshing, which would result in buttons being reset while the wallet itself did not change. As a sideeffect, this would also close the second signature or delegate registration modals if those were open, making it difficult to work with those transaction type. This PR adds a check to only reset the buttons when the wallet actually changed.
=> fix: only reset buttons when the curretWallet has changed

src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
`this.currentWallet` was not defined when the `WalletSidebar` was used in the dashboard, which resulted in a js error and the wallets no longer loading in that sidebar.
=> fix: check if currentwallet is defined before checking for contact

src/renderer/components/Wallet/WalletHeading/WalletHeading.vue, src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
#771 doesn't set the activeWallet, which means if you switch to a second wallet the fix is voided. This is fixed in this PR and refactored a little bit, so as to store the id of the wallet only and not the whole object.
The other change I've implemented here is to watch for changes in the currentWallet's publicKey in the `WalletSidebar` in order to check whether the wallet has one. If the wallet has no publicKey, it can cause a bug where the heading doesn't get reset.
1. The wallet heading reset is still misbehaving
- Before
- After
2. The publicKey bug mentioned above (imported wallet with address only)
- Before
- After
=> fix: showPublicKey bug with address import

src/renderer/components/Wallet/WalletSignVerify/WalletSignVerify.vue
While on the sign/verify tab, switching wallets would not update the list of signed messages.
=> fix: get signed messages of current wallet

src/renderer/components/Wallet/WalletHeading/WalletHeading.vue
As originally done in #780, storing the whole wallet object is unnecessary since only the ID is used for the comparison check. This also aligns with the same check introduced in #787.
=> refactor: store only the id of the active wallet

__tests__/unit/services/wallet.spec.js, src/renderer/pages/Wallet/WalletImport.vue, src/renderer/services/client.js, src/renderer/services/wallet.js
Also fix the issue with Korean passphrases when sending transactions / signing messages.
Please test again by trying to send some transactions, including one with a second signature. Don't forget to set your bip39 language to Korean when creating a new wallet to test it
=> fix: also decompose passphrases for tx and signing

src/renderer/components/MarketChart/MarketChart.vue
Was a TODO: add loader to Market chart, it works when loading the tab initially and when switching between timespans or tabs.
=> feat: market chart loader

src/renderer/components/Transaction/TransactionModal.vue
Resolves #774 
Transactions that were not a transfer did not have a recipientId, which resulted in the `storeTransaction` function setting a property to undefined which made the unconfirmed transaction not appear. This PR sets the sender as recipient if recipientId is undefined, which makes the unconfirmed tx show up again:
=> fix: show unconfirmed tx for type > 0

__tests__/unit/components/Transaction/TransactionModal.spec.js, src/renderer/components/Transaction/TransactionModal.vue, src/renderer/components/Wallet/WalletSelection.vue, src/renderer/i18n/locales/en-US.js
This PR fixes 1 problem introduced on https://github.com/ArkEcosystem/desktop-wallet/pull/820, which ignores that the API response could include other errors.
Apart from that, it displays a warning when the transaction is only broadcasted.
=> fix: capture any error when sending transactions and warn about broadcasting

src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue, src/renderer/pages/Wallet/WalletNew.vue
Properly split Japanese passphrases so this no longer happens:
=> fix: split japanese passphrases correctly

src/renderer/store/modules/network.js, src/renderer/store/modules/session.js
Networks got reloaded when you switched profiles, which reset any custom changes you made to it. This PR currently removes that behaviour, but I'm unsure what the use of fetching new network data was, so proposing two additional changes instead of simply removing it:
1. we could call the `updateNetworkConfig` function the first time the app loads and we load the default networks from the config file (this is only done once).
2. we could add a "refresh" button to the network modal in which you can see your network configs, which would overwrite any changes you made by fetching the latest config from a network peer. By doing it this way you will see the new settings and can adjust them to your liking, instead of having this happen in the background.
What do you think of the above solutions?
=> fix: do not update network config as it overwrites network changes

__tests__/unit/components/MarketChart/MarketChart.spec.js, src/renderer/components/MarketChart/MarketChart.vue
Use the market ticker instead of the token to fetch the chart data, as that is what it was supposed to be used for I guess 🤔 It also adds a check if the response from cryptoCompare contains the right data, as the `datasets` property was not there if an incorrect ticker / token was used.
=> fix: use ticker instead of token for market chart

src/renderer/components/Transaction/TransactionShow.vue, src/renderer/components/Transaction/TransactionTable.vue, src/renderer/components/Wallet/WalletAddress.vue, src/renderer/i18n/locales/en-US.js
Partially solves #767 and replaces #822.
This sets the tooltip container to `.TransactionTable` and adds a property to `WalletAddress`, which allows to set a custom tooltip container.
@j-a-m-l & @JeremiGendron can you confirm this works for you?
=> fix: set tooltip container on transaction table

src/renderer/components/Menu/MenuOptions/MenuOptions.vue
Due to additions to the settings menu, the arrow was no longer at the right position
=> fix: correctly position settings arrow

src/renderer/components/Wallet/WalletButtons/WalletButtonCreate.vue, src/renderer/components/Wallet/WalletButtons/WalletButtonImport.vue
Instead of having two separate router links this PR refactors the wallet create / import buttons to have only one router link instead, increasing the clickable area and thus enhancing the UX of these components.
=> refactor: unite router links of create/import buttons

src/renderer/components/ListDivided/ListDividedItem.vue, src/renderer/components/Transaction/TransactionShow.vue, src/renderer/components/Transaction/TransactionTable.vue, src/renderer/components/Wallet/WalletAddress.vue
Aligns the icons in the transaction show modal and fixes the wallet addresses being truncated twice on the dashboard:
=> fix: various tx table and modal UI improvements

src/renderer/components/Menu/MenuOptions/MenuOptions.vue
As reported by @dated , the arrows for the settings get aligned from the top, while it can have a different amount of options between profiles. To counter this, we can align them from the bottom.
=> fix: align settings arrow from the bottom

src/renderer/components/Network/NetworkSelectionModal.vue
Resolves #864 
Wraps network names even if they have no spaces, and also truncates them if they are longer than a certain amount so the networks will not take up more than 3 rows of text in the modal.
=> fix: network modal name wrapping

config/index.js
It was previously the british pound's symbol in config/index.js
Fixes #875
=> fix(config): Change HKD symbol to HK$

src/renderer/components/Network/NetworkModal.vue, src/renderer/store/modules/network.js
When entering a new network, it will now check if the given name already exists. Previously this would throw an error in the console upon adding the network.
=> feat: add validation of network name when adding a new network

src/renderer/components/utils/merge-table-transactions.js, src/renderer/pages/Contact/ContactAll.vue, src/renderer/services/synchronizer/wallets.js
- replace sortBy with orderBy in findLatestTransaction:
replacement for https://github.com/ArkEcosystem/desktop-wallet/pull/832, uses `orderBy` so complexity should stay at O(logn) instead
- replace sortBy with orderBy in merge-table-transactions.js:
uses `orderBy` instead of `sortBy` so reversing the list is unnecessary
- replace orderBy with sortBy ContactAll.vue:
since contacts with the same name are not allowed, ordering by address as well is unnecessary
=> perf: sortBy / orderBy

src/renderer/components/Network/NetworkModal.vue
The `remove` button should be available even if a field is invalid, since you want to remove it anyway. The `save` button had an issue as a name was seen as "duplicate" in the form as there was an existing network with that name when you tried to edit it. This PR adds an extra check to ensure that the same name is allowed if we're currently editing that network.
=> fix: network modal button disabling

src/renderer/components/Announcements/AnnouncementsPost.vue, src/renderer/components/Input/InputPassword.vue
Change the password-show/hide svg links to passphrase-x because
it renders correctly.
The Read more links now are only clickable on the Read more text.
Fixes: #871 #831
=> fix(misc): Password visibility and Read more links

src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue, src/renderer/components/Menu/MenuDropdown/MenuDropdownHandler.vue
#897 inverted the dropdown arrow since that was needed for the peer modal, but it was changed for every dropdown. This PR changes the arrow only for the peer modal where it was needed
=> fix: only invert dropdown arrow for peer screen

__tests__/unit/mixins/currency.spec.js, __tests__/unit/mixins/formatter.spec.js, __tests__/unit/pages/Profile/ProfileAll.spec.js, src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue, src/renderer/mixins/currency.js
Changes the error showing the minimum allowed amount for a transfer to a fraction number instead of `arktoshi1.00`. Reasoning is that it's easier to compare `0.000000001` to the allowed `0.00000001` than `arktoshi1.00`:
It also adds a space between crypto and amount to make it more readable:
=> fix: input amount minimum

src/renderer/components/Input/InputCurrency.vue
The alternative currency amount is not being set to 0 when there is no input.
@ItsANameToo this seems to work as originally intended, i am unable to reproduce the same bugs as in #882. Can you confirm?
=> fix: update alternative currency when no input

src/renderer/components/Transaction/TransactionModal.vue
A bug was introduced when adding/upgrading the URI system whereby every transfer transaction would be sent to a new peer. This checks to make sure the wallet being sent from is on a different network to the current profile.
=> fix: send transfer transaction to current peer

src/renderer/App.vue, src/renderer/services/synchronizer/ledger.js, src/renderer/store/modules/ledger.js
In order to save on duplicate requests, the ledger store deals with refreshing wallet information. However the problem was that it was only refreshing the last wallet because it was basing it on the cache.
=> fix: refresh all ledger wallets, not just cache

__tests__/unit/__mocks__/@arkecosystem/ledger-transport.js, __tests__/unit/services/ledger-service.spec.js, __tests__/unit/store/modules/ledger.spec.js, src/renderer/services/ledger-service.js, src/renderer/store/modules/ledger.js
This includes some refactor as the ledger transport layer returns both public key and address together. It also reduces a ledger call when reloading wallets, hopefully speeding it up marginally.
=> refactor: get ledger address & public key together

src/renderer/components/App/AppIntroScreen.vue, src/renderer/components/App/mobile/AppIntroScreenMobile.vue, src/renderer/i18n/locales/en-US.js
```
fix(intro): Your Duty (8, 9, 10)
fix(intro): Your Responsibility (11)
fix(intro): Your Turn (12)
fix(intro): Reformat Your responsibility to fit more text
```
Implement suggestions from justin on intro screen texts.
Ref: #891
=> refactor: intro screens text content

src/renderer/components/Wallet/WalletDetails/WalletDetails.vue, src/renderer/i18n/locales/en-US.js
The vote banner in the delegates tab shows the unvote button even if the wallet is not owned by the user, i.e. it has not been imported as such. This PR hides the button and changes the text from `You` to `This wallet`.
Owned:
Not owned:
=> fix: change delegate voting banner if wallet is not owned

__tests__/unit/store/modules/network.spec.js, src/renderer/App.vue, src/renderer/i18n/locales/en-US.js, src/renderer/store/modules/network.js
I seemed to have an intermittent issue where all my custom networks were disappearing. This I believe was caused by 2 separate things. "Loading" the network data too early, before vuex was ready. And also the local `getter` was trying to access the root (`getters['network/all']`).
In case this has caused issues in other wallets, I've added a temporary fix to make sure `all` has all of the custom networks on load.
=> fix: load all networks correctly

src/renderer/components/Wallet/WalletHeading/WalletHeadingPrimaryActions.vue
When navigating to 1 wallet, or switching from 1 to other, the orange dot that warns about that the wallet is not voting, is displayed even when the wallet is voting while fetching data.
That was very annoying, and this PR changes the behaviour and it doesn't show it until checking on the server that the wallet is not voting.
=> fix: do not display the not-voting icon before knowing if the wallet is voting

src/renderer/components/Wallet/WalletAddress.vue
=> fix: tooltip position of truncated address

src/renderer/components/Input/InputCurrency.vue
The "Advanced" option of the fee slider displays the wrong message when the introduced value is 10 times bigger than the default maximum fee.
=> fix: display the right error message on the fee slider

src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue, src/renderer/styles/_theme.css, tailwind.js
Changes the wallet heading font color to be the same in dark and light mode, since the heading doesn't change colors between themes and the text is very hard to read in dark mode:
before:
=> improvement: make wallet heading name more visible in dark mode

src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
When switching from a wallet with balance to a wallet with zero balance, the desktop wallet will still show the balance(s) from the previous wallet, because of `(balance || lazyBalance || 0)`.
=> fix: correctly handle zero balance on wallet heading info

src/renderer/pages/Wallet/WalletNew.vue, src/renderer/styles/_theme.css
This PR increases the UI/UX of the wallet selection on the new wallet page by:
- making the whole list element clickable instead of only the address, thus increasing the clickable area
- reducing the opacity as well of unselected wallets instead of only changing the color of the address
[the transition delays are caused by my 🥔]
=> refactor: new wallet selection styles and ui

src/renderer/components/Button/ButtonClipboard.vue, src/renderer/styles/_tooltip.css
Adds tooltip colors and a delay to the tooltip hiding.
=> refactor: success/error colors and delay on clipboard button tooltip

src/renderer/components/Input/InputGrid/InputGridModal.vue
There was a problem when trying to select a profile avatar on the profile creation and edition pages: when clicking the avatars where displayed, but not inside a modal window.
The root cause was that the `ModalWindow` component wasn't correctly detected.
=> fix: importing of profile avatar selection modal component

src/renderer/components/Wallet/WalletTable.vue, src/renderer/pages/Contact/ContactAll.vue, src/renderer/pages/Wallet/WalletAll.vue
As pointed out by @alexbarnsley it is more intuitive to have an increasing opacity upon focus on the identicons.
=> misc: invert identicon hover behaviour

src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue, src/renderer/i18n/locales/en-US.js
Adds an animation to the sidebar upon expanding or collapsing and fixes the "white border issue" caused by the transition on the bottom border. I deemed the fading out and in necessary since there is no proper way to transition the flex-direction property.
=> feat: add sidebar animation

__tests__/unit/components/Profile/ProfileRemovalConfirmation.spec.js, src/renderer/components/Input/InputGrid/InputGridItem.vue, src/renderer/components/Profile/ProfileRemovalConfirmation.vue, src/renderer/pages/Profile/ProfileAll.vue, src/renderer/store/modules/session.js
This PR fixes several problems that occur when removing a profile. Some of them are visible on the console after clicking on Remove, while others occur after that, when the user is redirected to the profile creation (if no other profile is available) or when the user start again the application without profiles.
=> fix: errors during and after removing profiles

src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue, src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
Currently there are several problem when voting with the Ledger:
- `TransactionFormVote` throws an `Error`, although the process works successfully
- The "Unvote" button at the bottom of the delegate tab is missing
=> fix: show the "Unvote" action at the bottom of the delegate tab when using the Ledger

src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue, src/renderer/pages/Wallet/WalletShow.vue
Keeping the button to expand/collapse at the top would allow seeing (expanding) the balance of the last wallets without having to go to the top to expand the sidebar.
=> feat: keep the expand button at the top

src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
=> fix: docs filepath

src/renderer/components/Dashboard/DashboardTransactions.vue, src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
Two little fixes:
1. the loading animation of the dashboard transactions currently shows indefinitely when there are no wallets
2. when there are no wallets the wallet placeholder in the sidebar shows while loading the ledger
=> fix: dashboard transaction loading and sidebar placeholder

src/renderer/components/Transaction/TransactionForm/TransactionForm.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue, src/renderer/components/Transaction/TransactionModal.vue, src/renderer/components/Wallet/WalletAddress.vue, src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
=> feat: allow navigating to delegate addresses on the vote delegate modal

__tests__/unit/pages/Profile/ProfileAll.spec.js, config/index.js, src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue, src/renderer/components/Contact/ContactRemovalConfirmation.vue, src/renderer/components/Modal/ModalConfirmation.vue, src/renderer/components/Profile/ProfileLeavingConfirmation.vue, src/renderer/components/Profile/ProfileRemovalConfirmation.vue, src/renderer/components/Profile/index.js, src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue, src/renderer/components/Wallet/WalletRemovalConfirmation.vue, src/renderer/i18n/locales/en-US.js, src/renderer/pages/Profile/ProfileAll.vue, src/renderer/pages/Profile/ProfileEdition.vue
Resolves https://github.com/ArkEcosystem/desktop-wallet/issues/1018.
Users could:
a) Close the modal and continue on the profile edition
b) Ignore the modified settings and navigate to the expected route
c) Save the modified settings and navigate to the expected route
Apart from that, it fixes that, the order on the profiles page is altered after updating a profile.
=> feat: ask users, when leaving the profile edition without having saved it, if they want to do it

config/networks/mainnet.json
The address changed, so this PR, adds the new one, but it keeps the former too.
=> misc: configure the new Ark Shield address

src/renderer/i18n/locales/en-US.js, src/renderer/mixins/formatter.js, src/renderer/pages/Profile/ProfileEdition.vue, src/renderer/pages/Profile/ProfileNew.vue, src/renderer/store/modules/session.js
That setting was on the profile edition, but not on the profile creation
=> feat: add the time format setting to the profile creation

__tests__/unit/components/Wallet/WalletAddress.spec.js, __tests__/unit/components/Wallet/WalletSidebar.spec.js, src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue, src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue, src/renderer/components/Menu/MenuOptions/MenuOptionsItem.vue, src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue, src/renderer/components/Wallet/WalletSidebar/WalletSidebarFilters.vue, src/renderer/components/Wallet/WalletSidebar/WalletSidebarFiltersSearchInput.vue, src/renderer/directives/click-outside.js, src/renderer/i18n/locales/en-US.js, src/renderer/store/modules/wallet.js, src/renderer/styles/_theme.css, tailwind.js
This PR:
- Refactors several theme styles
- Refactors the sidebar to use reactiveness
- Implements the filters and sorting feature on the wallet sidebar
=> feat: include a menu to filter and sort the wallets of the sidebar

src/renderer/components/Network/NetworkModal.vue, src/renderer/services/crypto-compare.js, src/renderer/store/modules/market.js
Resolves https://github.com/ArkEcosystem/desktop-wallet/issues/1046
=> feat: infer the market ticker of custom networks by checking CryptoCompare

src/renderer/store/modules/session.js
This change reduces the time to load initially the session about 2 seconds and switching profiles is reduced about 1 second. Your mileage may vary.
=> refactor: speed session load up by using 1 mutation instead of dispatching lots of actions

.electron-vue/webpack.renderer.config.js
In the production version is showing the developer note:
=> fix: compile portal-vue to not display developer note in production

__tests__/unit/components/Wallet/WalletHeadingInfo.spec.js, src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
This is intended as a different fix for #1057, thus replacing #1071. The reason is that in #1071 an API call is fired to fetch the wallet regardless of wether it is available in the store or not.
A stored wallet/contact has a `profileId` assigned to it, unowned wallets do not (empty string). Based on this property we can decide wether to fetch the wallet through the API or from the store.
=> fix: get balance for unowned wallets

README.md
=> docs: fix typos on translation instructions

.lintstagedrc, package.json
Adds the `git add` command to the lint-staged config, to include linted files in commits.
=> chore: stage linted files before commit

__tests__/unit/components/Dashboard/DashboardTransactions.spec.js, __tests__/unit/store/modules/transaction.spec.js, src/renderer/components/Dashboard/DashboardTransactions.vue, src/renderer/components/Wallet/WalletTransactions/WalletTransactions.vue, src/renderer/pages/Dashboard.vue, src/renderer/pages/Wallet/WalletAll.vue, src/renderer/services/synchronizer.js, src/renderer/services/synchronizer/wallets.js, src/renderer/store/modules/transaction.js
This is the first PR of a series that would revamp the entire application to allow caching transactions, improving its performance and enhancing the code.
In this PR:
- Allow trigger actions of the synchronizer directly
- Changed the dashboard to not synch the contacts, now that they are not displayed (currently contacts are included as wallets, so this change wouldn't be effective until more changes)
- The dashboard doesn't fetch transactions now. This makes the initial load of its transaction slower because the synchronizer fetches the wallet first, so there is a small delay. This would be addressed on the next PR,
=> refactor: revamp how transactions are loaded on the dashboard

src/renderer/components/Wallet/WalletTable.vue, src/renderer/models/wallet.js, src/renderer/pages/Contact/ContactAll.vue, src/renderer/pages/Wallet/WalletAll.vue
=> fix: show voted delegates in wallet table

__tests__/unit/services/synchronizer/wallets.spec.js, src/renderer/services/synchronizer/wallets.js
This is another step towards a faster app.
In this case, requesting the wallet data and transactions in parallel should save those 1 or 2 seconds, at minimum, of getting first the wallet data. This is not really perceptible on the first load because it's too slow yet, but it would be saved every time that the wallet or transactions are checked.
=> refactor: request wallets data and transactions in parallel during synchronization

src/renderer/components/MarketChart/MarketChartHeader.vue, src/renderer/i18n/locales/en-US.js, src/renderer/pages/Dashboard.vue
Since some users may disable the chart for performance reasons, as a trading attitude/technique, etc. showing the price might be helpful for them.
The price is requested periodically unless is disabled on the network configuration, so displaying the price doesn't involve additional requests.
=> feat: display the ticker price on the dashboard, even when the chart is disabled

__tests__/unit/components/MarketChart/MarketChart.spec.js, src/renderer/components/MarketChart/MarketChart.vue, src/renderer/mixins/formatter.js
When adding the time format setting, the market chart was not adapted.
=> fix: use the configured time format on the market chart

__tests__/unit/services/client.spec.js, src/renderer/services/client.js, src/renderer/store/modules/peer.js
Using the new endpoints that allow searching multiple wallets or transactions at the same time wasn't correctly triggered on the first load and when changing peers.
Apart from that, I've refactored the client service to make it easier using the new features that are being added to the API, and I've refactor slightly the tests to make them more readable.
=> fix: request multiple wallets or transactions at once when the API allows it

__tests__/unit/__utils__/setup.js, __tests__/unit/mixins/currency.spec.js, src/renderer/mixins/currency.js
Related to https://github.com/ArkEcosystem/desktop-wallet/pull/1075
=> fix: how cryptocurrencies are formatted when localized and displaying with symbols

src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
This is a measure to avoid that users forget that they have activated some filters and start wondering where are their wallets.
=> feat: highlight the wallet sidebar filters button when they are active

__tests__/unit/components/Wallet/WalletSidebar.spec.js, src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
The case of addresses wouldn't be ignored.
=> feat: ignore the case of the query when filtering by name of wallets, contacts, Ledgers, known wallets or delegates

src/renderer/components/Button/ButtonReload.vue, src/renderer/pages/Wallet/WalletNew.vue
- Improve the design when hovering the new address
- Change checkmark flag
- Update refresh address button
=> refactor: improve address list style when creating a new wallet

__tests__/unit/components/Input/InputFee.spec.js, __tests__/unit/services/synchronizer.spec.js, src/renderer/components/Input/InputFee.vue, src/renderer/services/client.js, src/renderer/services/synchronizer.js, src/renderer/store/index.js, src/renderer/store/modules/network.js, src/renderer/store/modules/peer.js, src/renderer/store/modules/session.js, src/renderer/store/modules/transaction.js
These changes avoid making requests at the beginning to fetch the fee statistics of every network, and then, periodically to have them updated.
Now, only the current network is checked, but just in the case that `InputFee` component is active, because they are only used there.
This also improves the `Synchronizer` service, so, from now on, we could disable completely some actions until needed.
=> refactor: synch dynamic fees only when `InputFee` is active

.circleci/config.yml
This PR changes the Node version to avoid some bugs that are blocking some PRs.
This should be later replaced by upgrading dependencies and restoring the version to `11`.
=> chore: change Node version to 11.10.1 to avoid problems on CI

src/renderer/components/Dashboard/DashboardTransactions.vue
The loader is being displayed even if there are no wallets.
=> fix: don't display loading on the dashboard if there are no wallets

src/renderer/components/Profile/ProfileAvatar.vue, src/renderer/pages/Profile/ProfileAll.vue
It was weird that image avatars used 1 kind of cursor, to show that they are clickable, but letter avatars not.
=> fix: show the pointer cursor on letter avatars

src/renderer/components/Input/InputLanguage.vue
Selecting a language was ignored:
- It didn't change the UI when the language changed
- It didn't create the profile with the selected language
=> fix: language selection on profile creation

src/renderer/App.vue, src/renderer/router/index.js
This PR caches the pages that have been visited that are not tied to the current profile and they don't change when switching profiles (announcements, networks, profiles).
=> perf: cache rendered pages that are not tied to the current session profile

src/renderer/components/Dashboard/DashboardTransactions.vue, src/renderer/components/Transaction/TransactionTable.vue
If another language is chosen, the 
> No transactions have been found. The latest transactions will be displayed here.
messages translations are not working.
Adds:
`:no-data-message="$t('TABLE.NO_TRANSACTIONS')"` 
in:
1. `src/renderer/components/Dashboard/DashboardTransactions.vue` 
2. `src/renderer/components/Transaction/TransactionTable.vue`
- [x ] Bugfix (non-breaking change which fixes an issue)
=> fix: enable the translation of empty transaction table message

__tests__/unit/services/synchronizer/wallets.spec.js, src/renderer/services/synchronizer/wallets.js, src/renderer/store/modules/ledger.js, src/renderer/store/modules/wallet.js
This PR revamps the `wallet` action of the Synchronizer service to save the fetched data of each wallet in 1 Vuex commit on the `wallet` store and 1 commit on the `ledger` store.
This has reduced the processing time from ~3000-6500ms to 500-2500ms, and it makes the UI less laggy.
=> perf: save regular and Ledger wallets at once instead of dispatching multiple Vuex actions

__tests__/unit/components/Input/InputFee.spec.js, src/renderer/components/Input/InputFee.vue
If fee statistics from a network are empty, an error occurrs with the InputFee component which resulted in the component failing to load. This was noticed when using v2.3 of the wallet with newly deployed chains.
=> fix: static fee default if fee statistics empty

src/renderer/components/Transaction/TransactionShow.vue
Block ID is going to change to sha256, so in some cases, it will be too long to display it on the transaction show modal.
=> feat: truncate the transaction block ID on the transaction show modal if necessary

src/renderer/App.vue, src/renderer/pages/Contact/ContactAll.vue, src/renderer/pages/Profile/ProfileNew.vue, src/renderer/pages/Wallet/WalletAll.vue, src/renderer/pages/Wallet/WalletNew.vue
Cache all the pages that don't depend on parameters on the URL by using a trick:
Since, in those cases, the URL is the same, it's possible to keep alive the component, because 1 component name is bound to 1 route name.
In cases, such as the wallet page, that property doesn't hold, so, it's not possible to use this mechanism.
=> perf: cache all the pages that do not use a parametrized URL

__tests__/unit/store/modules/ledger.spec.js, src/renderer/pages/Wallet/WalletAll.vue, src/renderer/store/modules/ledger.js
#1124 introduced a bug because the endpoint to search for multiple addresses does not return cold wallets in the response.
=> fix: do not override the state when updating wallets at once

src/renderer/components/ListDivided/ListDividedItem.vue, src/renderer/pages/Profile/ProfileEdition.vue
The profile edition page allows to change the value for the market chart display even if no market is available, for instance on devnet.
=> fix: disable market chart setting if market not enabled

__tests__/unit/__utils__/setup.js, __tests__/unit/components/Menu/MenuStep.spec.js, src/renderer/components/Collapse/CollapseAccordion.vue, src/renderer/components/Menu/MenuNavigation/MenuNavigation.vue, src/renderer/components/Menu/MenuStep/MenuStep.vue, src/renderer/components/Transaction/TransactionShow.vue, src/renderer/components/Wallet/WalletTable.vue, src/renderer/mixins/collections.js
Additional changes to #1129 which can either be merged into that branch or I'll rebase this PR if #1129 gets merged first.
This PR adds a clipboard button for the block id and adds a condition to the clipboard button of the transaction id, so there is no right margin when the explorer link is missing.
=> fix: add margin only when confirmations truthy & chores

.gitignore
=> chore: git-ignore `plugins` folder

src/renderer/components/Input/InputSelect.vue, src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue, src/renderer/components/Menu/MenuDropdown/MenuDropdownHandler.vue
Some dropdowns were not working since the upgrade of dependencies. The component that was affected was used on:
- Welcome screen: choose app language
- New profile: all dropdowns
- Send transfer: select address from wallets and contacts
=> fix: `InputSelect` dropdowns

__tests__/unit/services/client.spec.js, src/renderer/services/client.js
Resolves an issue with non-ARK chains, where the fee greater than ARK's static fees resulted in not being able to send transactions.
=> fix: other network fees when higher than ARK static fees

src/renderer/directives/click-outside.js
The menus on the main sidebar (settings and peers/networks) weren't working since the upgrade of dependencies.
=> fix: main sidebar menus (settings and peers/networks)

src/renderer/services/transaction.js
The latest version of the crypto package does not allow to get struct without a signature and a sender: https://github.com/ArkEcosystem/core/blob/master/packages/crypto/src/builder/transactions/transaction.ts#L178-L180
=> fix: do not use getStruct in ledger transactions

package.json, src/renderer/services/plugin-manager.js, yarn.lock
Make sure the plugin directories exist so the user doesn't have to figure out how to create them (e.g. Windows)
=> feat: ensure plugins directory exists

src/renderer/models/profile.js
- The `avatar` property in the profile model was merging the specifications of two types;
- Used the JSON Schema directive `anyOf` to set the specs separately.
=> fix: profile model validation to use letter avatar

src/renderer/components/Input/InputGrid/InputGrid.vue, src/renderer/components/Input/InputGrid/InputGridItem.vue, src/renderer/components/Selection/SelectionAvatar.vue, src/renderer/i18n/locales/en-US.js, src/renderer/i18n/locales/it-IT.js, src/renderer/pages/Profile/ProfileEdition.vue, src/renderer/pages/Profile/ProfileNew.vue
On profile creation or edition, letter avatars were broken when switching from one language to another.
=> fix: do not break letter avatars when switching languages

src/renderer/components/Profile/ProfileAvatar.vue, src/renderer/models/profile.js, src/renderer/pages/Profile/ProfileEdition.vue, src/renderer/pages/Profile/ProfileNew.vue, src/renderer/store/migrations/2.4.0 - fix letter avatars.js
Profile edition wasn't working correctly: profiles with letter avatars were enabling the "save" button even when no modification was done.
The root cause was that some profiles were created or modified incorrectly. This PR fixes that and migrates older profiles to keep the right scheme.
To generate profile with problematic avatars, they could be created on `develop` and `next` branches.
=> fix: value of letter avatar on profile creation

__tests__/unit/services/wallet.spec.js, src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmDelegateRegistration.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue, src/renderer/i18n/locales/en-US.js, src/renderer/services/wallet.js
The current `@arkecosystem/crypto` package (2.2.2) has removed the username validator, which was breaking the delegate registration process.
Following @faustbrian suggestion, instead of upgrading that package, since it'is  going to be modified until `core` 2.6, I've, instead, implemented the validation on the wallet.
Additionally, the confirmation screen has been fixed to display the sender label correctly.
=> fix: username validation when registering a new delegate

src/renderer/components/MarketChart/MarketChart.vue, src/renderer/components/utils/LineChart.js, src/renderer/pages/Dashboard.vue
The market chart wasn't properly enabled or disabled when the related setting was changed on the profile edition.
=> fix: show the market chart when enabling it on the profile

__tests__/unit/store/modules/peer.spec.js, config/networks/devnet.json, config/networks/mainnet.json, src/renderer/components/Network/NetworkModal.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue, src/renderer/models/network.js, src/renderer/services/client.js
Update the maximum length admitted on the vendor field when the network provides a new value.
=> feat: sync the `vendorField` maximum length from the network

src/renderer/App.vue, src/renderer/components/MarketChart/MarketChart.vue, src/renderer/mixins/session.js
If the theme is being used, but the user removes the code of the plugin, it uses the default theme instead.
=> fix(plugins): use light theme if plugin is removed before disabling

src/renderer/pages/Profile/ProfileNew.vue
Plugin permissions depend on profile, so that theme wouldn't be available right after the creation.
=> fix(plugins): do not allow choosing a plugin theme during profile creation

src/renderer/pages/Wallet/WalletNew.vue
When hovering over the shown addresses in the `Create Wallet` page there is a slight vertical displacement of the containers.
=> fix: stop hover from displacing address container

config/index.js, src/renderer/i18n/locales/en-US.js, src/renderer/pages/Plugins.vue
That button, currently, opens the browser to navigate to https://github.com/ark-ecosystem-desktop-plugins
=> feat(plugins): add a button to discover more plugins on an external URL

config/index.js, src/renderer/i18n/locales/en-US.js, src/renderer/pages/Plugins.vue, src/renderer/services/plugin-manager.js
Add a button to open the folder which contains the installed plugins
=> feat(plugins): button to open the plugin installation folder

src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue, src/renderer/services/client.js
- Signing transactions with encrypted wallets are not working;
- The crypto package requires a second parameter to compare if the wif provided is compatible with the current network.
Reference: https://github.com/ArkEcosystem/core/blob/master/packages/crypto/src/builder/transactions/transaction.ts#L110
=> fix: provides the network wif to sign transactions

src/renderer/services/plugin-manager.js
- Change the rootPath;
- When rendering the component, the component data no longer belongs to the context scope.
=> fix(plugins): render components in production

src/renderer/i18n/locales/en-US.js, src/renderer/pages/Plugins.vue
This button would reload the application. In the future it could be changed to reload the plugins solely.
=> feat(plugins): button to reload plugins

src/renderer/services/client.js
There is functionality in the crypto library that checks that the vendor field length is within the current milestone's value. This is with 2.3.22 of the crypto library. The desktop wallet currently uses 2.2.2, which hardcodes a 64 character limit, but neither work because of the lack of config.
Because the forms already do the validation of the length, we now simply set the vendor field value when building the transaction object.
=> fix: vendorField transaction assignment

src/renderer/components/App/AppSidemenu/AppSidemenuPlugins.vue
The arrow of the items menu that allow navigating to plugin pages wasn't correctly positioned. This fix changes that, so in case there are only a few items the arrow points to the correct icon and, in case, there lots of them too, although it wouldn't be in the exact same position (the same issue is applicable to the other menus).
=> fix(plugins): position of the arrow of the plugin items menu

src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue, src/renderer/i18n/locales/en-US.js
Adds a helper text to the vendorField input showing how many chars/bytes can be still entered.
=> feat: show remaining bytes in vendorfield helper text

src/renderer/components/App/AppSidemenu/AppSidemenu.vue, src/renderer/components/App/AppSidemenu/AppSidemenuPluginConfirmation.vue, src/renderer/components/Modal/ModalConfirmation.vue, src/renderer/i18n/locales/en-US.js, src/renderer/models/profile.js
When the user tries to navigate to the plugins section, a modal would surge with a warning. If the user decides to enable them, that modal doesn't appear again.
=> feat(plugins): warn about using the plugin system

src/renderer/components/Transaction/TransactionAmount.vue, src/renderer/components/Transaction/TransactionShow.vue, src/renderer/components/Transaction/TransactionStatusIcon.vue, src/renderer/components/Transaction/TransactionTable.vue
=> refactor: add the status icon and plus/minus sign in the transaction viewer

src/renderer/pages/Wallet/WalletNew.vue
The wallet creation page throws several errors on the console tagged as Vue warnings.
=> fix: duplicated key warning on new wallet page

src/renderer/components/Menu/MenuNavigation/MenuNavigation.vue, src/renderer/components/Menu/MenuNavigation/MenuNavigationItem.vue, src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
Fixes https://github.com/ArkEcosystem/desktop-wallet/issues/1237
This measure avoids a subsequent race-condition that was pushing an additional
entry to the navigation history. The result was that, when navigating from the
wallet page to the profiles section, the route was ignored.
Since, it was trying to load a wallet page with no address, the router
was redirecting to the wallets section. So the history was:
1 - /wallets/:address
2 - /profiles
3 - /wallets/:address (address = null)
=> fix: don't switch twice when selecting wallet on WalletSidebar

src/renderer/components/App/AppBackButton.vue
Sets the padding on the back button itself rather than the container, thus making the complete button clickable. Also changes the text to use the localized string instead of the hardcoded `Back`.
=> refactor: make complete back button clickable and use localized text

src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
Extension of #1309. Only show a tooltip if the value is truncated.
=> refactor: show tooltips only when value truncated

src/main/index.js
Since updating to Electron 5, webviews were disabled by default. This prevented the Exchange functionality in the wallet from working.
=> fix: enable webviews

src/renderer/pages/Wallet/mixin-on-create.js
There was a scenario where there was a problem with the crypto package on the develop branch. When importing or creating wallets with an Encryption Password, the wallets weren't being stored correctly. This would have caused problems because it would have resulted in not being able to send transactions from those wallets (would mean re-importing from the passphrase without an Encryption Password).
This change prevents wallets from being created when the password encryption fails (e.g. due to high load on a machine which can't talk to the BIP38 worker)
=> feat: do not create wallet if fails encryption of password

src/renderer/services/plugin-manager.js
Adds the ability to use the loader spinner in plugins via `<Loader />` like in other areas of the wallet if the `UI_COMPONENTS` permission is granted. I only exposed the `Loader` from `utils` as the other components in `utils` did not seem appropriate for plugins, although the PR can be revised to expose them as `UtilsComponents` if necessary.
Reason for adding: Plugins can communicate with external servers and these responses can sometimes take a while to be received. Showing the loading spinner provides visual feedback that the operation is ongoing and has not crashed. Using the wallet's spinner makes the design coherent and more native.
If adding a **new feature**, …
=> feat: allow use of the loader spinner in plugins

src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue, src/renderer/components/Transaction/TransactionModal.vue, src/renderer/components/Wallet/WalletDetails/WalletDetails.vue, src/renderer/components/Wallet/WalletHeading/WalletHeadingMenuLedger.vue, src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue, src/renderer/components/Wallet/WalletTransactions/WalletTransactions.vue, src/renderer/pages/Contact/ContactAll.vue, src/renderer/pages/Dashboard.vue, src/renderer/pages/Plugins.vue, src/renderer/pages/Wallet/WalletAll.vue, src/renderer/services/synchronizer/wallets.js
Instead of using lodash's `clone` method this PR relies on the spread operator to perfom shallow clones of the profile object before updating it.
=> refactor: use spread operator instead of lodash's clone before updating profile

src/renderer/components/Input/InputText.vue, src/renderer/components/Wallet/WalletGrid.vue, src/renderer/pages/Wallet/WalletAll.vue
- truncates the wallet name on the wallet grid view
- stops scrolling on InputText component
- reloads all wallets after renaming a wallet (previously the Ledger wallets would disappear)
- ~removes the additional space between currency symbol and value which is added by `vue-i18n`~
=> fix: truncate wallet name in grid view, scroll on InputText and reload wallets after rename

src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
Fixes a bug where disabling the protection is saved regardless of if it's for the local session or permanent. 
=> fix: screenshot protection

package.json, yarn.lock
On a fresh setup of the desktop wallet, the peer list is pulled from GitHub. This peer list only contains the p2p port. Version 0.2.0 of `@arkecosystem/peers` took the p2p port as the public API port, which is incorrect.
=> fix: port used from github peer list

package.json, yarn.lock
3.8.4 includes various fixes for ways to break out of the VM.
=> chore(deps): upgrade vm2 to 3.8.4

__tests__/unit/services/plugin-manager/websocket.spec.js, src/renderer/services/plugin-manager/websocket.js
Partially fixes #1447 and increases websocket test coverage to 100%.
=> refactor(plugins): add websocket methods

__tests__/unit/services/plugin-manager/timers.spec.js, src/renderer/services/plugin-manager.js
Resolves #1446 by implementing a `TIMERS` permission that exposes `clearInterval`, `clearTimeout`, `setInterval` and `setTimeout`.
It uses internal arrays to store the IDs of any timeouts and intervals to make sure they are all cleared once the route navigation changes and it also works with nested timers. A watchdog object is used to keep track of pending timeouts so they are immediately removed from the array once executed in order to prevent excessive memory usage that could potentially arise by repeatedly executing timeouts. The IDs are also removed from their respective arrays when `clearInterval` or `clearTimeout` are called. It also includes appropriate tests.
The reason for adding the feature was outlined in #1446.
If yes, please describe the impact and migration path for existing …
=> feat: timers in plugins

.github/workflows/lint.yml, .github/workflows/test.yml
=> chore: adjust workflows to match all branches on push

src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue, src/renderer/components/Network/NetworkModal.vue, src/renderer/services/client.js
Adding a custom network fails if the seed server has no port. This PR provides default values if the port is missing.
Regarding the changes made to: 
```
__parseCurrentPeer () {
const matches = /(https?:\/\/)([a-zA-Z0-9.-_]+):([0-9]+)/.exec(this.host)
const scheme = matches[1]
const ip = matches[2]
const isHttps = scheme === 'https://'
let port = isHttps ? 443 : 80
if (matches[3]) {
port = matches[3]
}
return {
ip,
port,
isHttps
}
```
If `this.host` contains no port, `matches` is `null` and `const scheme = matches[1]` throws a type error. Checking against `matches[3]` afterwards is useless at this point.
=> fix: provide default port when adding custom network

src/renderer/components/Selection/SelectionNetwork.vue, src/renderer/pages/Profile/ProfileNew.vue, src/renderer/services/client.js
When first creating a profile there is no option to add a custom network, which might be required for testing purposes or to connect to a bridgechain. Instead, the user is forced to choose one of the predefined ARK networks and is given the option to create a custom network only then.
=> refactor: custom network during onboarding

.github/workflows/test.yml
The default shell for windows has changed to PowerShell, causing the build steps to fail.
See https://github.blog/changelog/2019-10-17-github-actions-default-shell-on-windows-runners-is-changing-to-powershell/
This PR sets the shell to `cmd` instead.
=> ci: set shell to `cmd` on windows build steps

__tests__/unit/components/utils/WebFrame.spec.js, src/renderer/components/utils/WebFrame.js
Resolves #1525 by allowing webframes to access `ark:` URIs.
This will allow plugins that are effectively thin clients that render content in WebFrames to create transactions for in-plugin purchases or similar transactions, whose webframe content would not be able to directly access or manipulate modals (assuming modal support will be added to the plugin sandbox in future).
=> refactor(plugins): support ark uri scheme in webframes

__tests__/unit/services/plugin-manager/sandbox/websocket-sandbox.spec.js, src/renderer/services/plugin-manager/sandbox/websocket-sandbox.js
Resolves #1497 and fixes #1493 and includes appropriate tests. Also confirmed the described memory leak in #1497  is resolved.
=> refactor(plugins): add destroy method and binary websocket support

.github/workflows/lint.yml, .github/workflows/test.yml
Another try of https://github.com/ArkEcosystem/desktop-wallet/pull/1535 as the cache limit was raised from 200MB to 400MB https://github.com/actions/cache/releases/tag/v1.0.1
=> ci: add dependency caching

src/renderer/components/Wallet/WalletTransactions/WalletTransactions.vue
=> fix: new transactions notice

__tests__/unit/services/plugin-manager/plugin-sandbox.spec.js, __tests__/unit/services/plugin-manager/setup/components-setup.spec.js, src/renderer/services/plugin-manager/plugin-sandbox.js, src/renderer/services/plugin-manager/plugin-setup.js, src/renderer/services/plugin-manager/setup/components-setup.js
Fixes #1534 
Add a second VM to read the main file and compile the template.
=> fix(plugins): vue package in production

src/main/index.js
The issue in #1520 only occurred if the desktop wallet was already open (i.e. the `second-instance` event was called). It was caused by `--original-process-start-time` being added as `argv[2]` on Windows systems, meaning the URI handler received that string instead of the actual URI. Presumably there was a change to Electron or Chromium to either add that switch or it rearranged the order they were presented in `argv`.
This PR resolves #1520 by iterating through all the `argv` array elements to find the URI. This should be more resilient in case any future Electron/Chromium changes modify the order again.
Now works for me on Linux, macOS and Windows both when the wallet is closed and when it's already open.
=> fix: parse uri

__tests__/unit/services/client.spec.js, __tests__/unit/services/uri-handler.spec.js, src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue, src/renderer/i18n/locales/en-US.js, src/renderer/i18n/locales/it-IT.js, src/renderer/services/client.js, src/renderer/services/uri-handler.js
Fixes #1531
Resolves #1532
Where the same sender wallet exists on multiple profiles, if the wallet exists in the currently selected profile then it will select that, otherwise it will pick the first one it finds by iterating through the profiles.
=> feat: specify sender wallet and nethash in uri

src/renderer/styles/_table.css
#1494 broke table formatting for left-aligned headers that used the `text-left` class if the column contained numerical data and that column was being used to sort the data in the table. This is because that PR forces sorted headers to be flexboxes with `justify-content: flex-end` (since `vgt-right-align` is automatically applied if the column contains numerical data).
This fixes it by overriding this with `justify-content: flex-start` if the header also has the `text-left` class. This approach was chosen as it mirrors the existing `.vgt-table th.vgt-right-align.text-center` CSS rule for centre-aligned headers.
Although the wallet itself doesn't seem to use left-aligned sortable headers for numerical data, some plugins, including my own, will need this as plugins can't define their own …
=> fix: left aligned sortable table headers

__tests__/unit/services/plugin-manager/component/create-component.spec.js, src/renderer/services/plugin-manager/component/get-context.js
It was possible to bypass checks in the plugin system by overriding the href property.
=> fix: prevent href breakout

src/renderer/services/client.js, src/renderer/services/transaction.js, src/renderer/store/modules/transaction.js
Consolidated called to assign totalAmount to a transaction. This is as a result of fixing a bug where new transactions didn't have that property. A similar method already exists in [feat/2.6-tx-types](https://github.com/ArkEcosystem/desktop-wallet/tree/feat/2.6-tx-types), along with tests so I've excluded the tests from this PR.
=> fix: transaction amount on confirmation modal

__tests__/unit.jest.conf.js
=> chore: add test coverage reporters

__tests__/unit/services/client.spec.js, __tests__/unit/store/modules/delegate.spec.js, __tests__/unit/store/modules/ledger.spec.js, __tests__/unit/store/modules/peer.spec.js, __tests__/unit/store/modules/transaction.spec.js, src/renderer/i18n/locales/en-US.js, src/renderer/models/peer.js, src/renderer/services/client.js, src/renderer/store/modules/ledger.js, src/renderer/store/modules/peer.js
There is currently no need for the wallet to check on a peer's version since the only compatibility checks were for core 2.1.0. Also removed the use of core-wallet-api (port 4040), because the only thing it was used for was to get the core version for the above compatibility checks.
=> refactor: remove wallet api and peer version

src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
Relates to #1562, except for transactions created for a Ledger wallet. Transactions now use a `totalAmount` property to display on the confirmation modal (and also for sorting). In the future, we will remove this property and look at doing it a better way, so we don't need to worry about assigning that property whenever a transaction is created.
I'll look at tests at the same time as updating to not require `totalAmount`.
=> fix: ledger transaction amount on confirm modal

__tests__/unit/services/plugin-manager.spec.js, src/main/plugin-manager.js, src/renderer/App.vue, src/renderer/pages/PluginManager.vue, src/renderer/services/plugin-manager.js, src/renderer/services/plugin-manager/errors.js
Checks that the plugin is not enabled in the store before disabling it from the service. Adds check from #1581, deletes the path of the installed plugin when updating (fix for updating to new folder structure).
=> fix: delete plugin path of installed plugin when updating and various tweaks

src/renderer/components/MarketChart/MarketChart.vue
Fixes #1567. 
Also changes the `mode` of the tooltips so that only one event is fired if hovering over a point in between indeces. This gets rid of the double-label-tooltips. Also reduces the point hit radius by half, since the `intersect` option is set to `false` anyway.
=> fix: re-render chart if currency changed while being inactive

__tests__/unit/components/PluginManager/PluginManagerButtons/PluginManagerButtonInstallSource.spec.js, __tests__/unit/store/modules/session.spec.js, config/index.js, package.json, src/renderer/App.vue, src/renderer/components/MarketChart/MarketChart.vue, src/renderer/components/Modal/ModalWindow.vue, src/renderer/components/PluginManager/PluginManagerButtons/PluginManagerButtonInstallSource.vue, src/renderer/components/Profile/ProfileAdvancedModeConfirmation.vue, src/renderer/components/Profile/index.js, src/renderer/i18n/locales/en-US.js, src/renderer/models/profile.js, src/renderer/pages/PluginManager.vue, src/renderer/pages/Profile/ProfileEdition.vue, src/renderer/services/plugin-manager.js, src/renderer/store/modules/plugin.js, src/renderer/store/modules/session.js, yarn.lock
Includes some additions since the original release PR #1584
=> release: 2.7.0

__tests__/unit/components/PluginManager/PluginManagerModals/PluginRemovalModal.spec.js, src/renderer/components/PluginManager/PluginManagerModals/PluginRemovalModal.vue, src/renderer/store/modules/plugin.js
When a plugin has the STORAGE permission, it will ask whether to remove all data for the plugin when removing it from the wallet. The removal would fail if the plugin never stored data but the option to remove all was selected.
Resolves #1602
=> fix: delete plugin when no data stored

package.json, yarn.lock
After some debugging, I've concluded that the tests were failing due to a bad handler for error messages from `jest`. Even using `--silent` and `--noStackTrace`, jest keept holding the messages inside the memory. Updating jest and related packages seems to improve test speeds (even in band mode) and prevent leaks. 
- Updating dependencies for `jest`, `jest-extended` and `jest-vue-preprocessor`.
- Adds the `test:unit:band` for testing using reduced specs. 
- Faster tests.
=> fix: memory leak for tests

__tests__/unit/components/Selection/SelectionBackground.spec.js, src/renderer/components/Selection/mixin-selection-image.js
=> fix: translate the keypath values of the background and avatars modal

__tests__/unit/components/PluginManager/PluginManagerSideMenu.spec.js, src/renderer/components/PluginManager/PluginManagerSideMenu.vue, src/renderer/i18n/locales/en-US.js, src/renderer/services/plugin-manager.js, src/renderer/store/modules/plugin.js
Hides Themes when listing all plugins. Instead, themes will only be visible from their own category
Excluded tests while they are being written in #1583
=> refactor: omit themes from list of all plugins

src/main/index.js, src/renderer/SplashScreen.vue
- Disable saved fullscreen state & apply once main window shows
- UI tweaks - spacing & disable text selection
=> fix: splashscreen fullscreen & ui tweaks

src/renderer/i18n/locales/en-US.js
Make multisignature text consistent throughout
=> chore: Make multisignature text consistent

.github/workflows/draft-artifacts.yml, .github/workflows/publish-release.yml, .github/workflows/test.yml, scripts/notarize.js
The `GITHUB_BASE_REF` environment variable only exists when a PR comes from a fork `Only set for forked repositories. The branch of the base repository.` so we can use it to prevent notarisation from forks but still use it for our own needs.
Code signing still needs an adjustment.
=> ci: disable notarisation on forks

src/main/index.js
Resolve https://github.com/ArkEcosystem/desktop-wallet/issues/1702
=> fix: retrieve fullscreen state after splashscreen

src/renderer/mixins/electron.js
Changed but not mentioned in v7 or v8 changelog
=> fix: use showSaveDialog with promise instead of callback

src/renderer/components/Menu/MenuTab/MenuTab.vue
When the width is less than `<450` the **"Wallet design"** has a line break forcing the menu to increase in size, so the `align-self: stretch` forces the menu item to take up the entire space.
**Before:**
**After:**
=> fix: set the menu tab item to stretch

src/renderer/components/Transaction/TransactionForm/mixin.js, src/renderer/i18n/locales/en-US.js
=> fix: transaction submit when invalid password

src/main/index.js, src/main/menu.js
=> fix: show splash screen on reload

__tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainRegistration.spec.js, __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainUpdate.spec.js, __tests__/unit/components/Transaction/TransactionForm/TransactionFormBridgechain/mixin.spec.js, src/renderer/components/Input/InputEditableList.vue, src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainRegistration.vue, src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainUpdate.vue, src/renderer/components/Transaction/TransactionForm/TransactionFormBridgechain/mixin.vue, src/renderer/components/Transaction/TransactionPeerList.vue, src/renderer/i18n/locales/en-US.js, src/renderer/services/client.js
Changes:
- Show "no peer nodes" error message when list is empty
- Align empty error message to the left
- Add max height to seed node list
- Add count / max count to list and allow to 'overflow'  with items
- Add `required` error message to `name`, `genesisHash` and `bridgechainRepository` upon registration
- excludes unchanged fields from bridgechain update assets
- only shows changed fields in magistrate confirmation modals
- invalidates magistrate forms if no fields have changed
Fixes:
- Fixes the `tooShort` validation on bridgechain updates
- excludes the asset repository from a bridgechain registration asset if empty
- removes the non-existent `VALIDATION.TOO_MANY` error on the seed node input
=> refactor: adjust bridgechain transaction form validation

src/renderer/components/Announcements/AnnouncementsPost.vue, src/renderer/models/announcement.js, src/renderer/store/migrations/2.8.2 - remove summary from read announcements.js, src/renderer/store/modules/announcements.js
Since an announcement can't be marked as `unread` and the summary isn't shown once it has been marked as `read`, there is no reason to keep the summary around.
Includes a migration to remove the summary from already read announcements.
=> perf: remove summary when marking announcement as read

src/renderer/components/Transaction/TransactionMultiPaymentList.vue, src/renderer/components/Transaction/TransactionShow/TransactionShow.vue, src/renderer/components/Wallet/WalletAddress.vue
This PR adds a new prop to the `TransactionMultiPaymentList` so that the recipients of multipayment transactions can be linked to from the transaction show modal.
=> feat: add links to multipayment list on transaction show

src/renderer/mixins/formatter.js
#1753 only correctly reassigns the userLanguage to `en` if it is `en-US`. Other locales, like `de-DE`, `it-IT`, `fr-FR` and so on will also fallback to `en`.
With this more generic approach all locales with the format `xx-XX` are handled correctly.
=> refactor: more generic userLanguage handling

package.json, src/renderer/components/Modal/ModalWindow.vue, src/renderer/components/PluginManager/PluginManagerModals/PluginDetailsModal.vue, src/renderer/components/PluginManager/PluginManagerModals/PluginImageModal.vue, src/renderer/components/PluginManager/PluginManagerModals/index.js, src/renderer/components/PluginManager/PluginSlider.vue, yarn.lock
- Change to use plugin image thumbnails
- Add modal to view plugin thumbnails
Todo in the future:
- Slider component to reduce code smell between the 2 components
=> feat: plugin image slider

__tests__/unit/services/plugin-manager/sandbox/storage-sandbox.spec.js, src/renderer/services/plugin-manager/sandbox/storage-sandbox.js
Refactors the storage sandboxes `getOptions` method so that all global options can be retrieved.
=> refactor: allow all global plugin options to be retrieved at once

__tests__/unit/services/plugin-manager/sandbox/peer-current-sandbox.spec.js, src/renderer/services/plugin-manager/sandbox/peer-current-sandbox.js
This PR exposes the current peer through the wallet api to plugins and can be retrieved with `walletApi.peers.getCurrent()`. It also refactors the `get` / `post` methods to accept an options object, which for example allows to pass in query parameters instead of having to build the url.
=> feat: expose current peer to plugins and allow options in requests

__tests__/unit/components/Modal/ModalConfirmation.spec.js, src/renderer/components/Modal/ModalConfirmation.vue
Under certain circumstances it makes sense to have a confirmation modal with only one option. This PR adds a new prop to the `ModalConfirmation` component which allows to hide the cancel button.
=> feat: allow to hide cancel button of confirmation modal

src/renderer/store/modules/profile.js
In order to display graphics in the appropriate color scheme (dark / light) plugins need information about the currently defined theme.
This PR adds the `theme` property to the public getter of the profiles store module, which is exposed to the plugin system. The property holds the name and a boolean flag to indicate whether it is a dark or light theme.
```
{ 
name: "light",
isDark: false
}
```
=> feat: expose profiles themes to plugins

src/renderer/components/Wallet/WalletHeading/WalletHeadingSecondaryActions.vue, src/renderer/styles/_theme.css
Using the dark theme the "Resign Bussines" button has transparent background.
I added the following variables for the dark theme:
```
--theme-option-heading-button-disabled: #3d404f;
--theme-option-heading-button-text-disabled: #6d798a;
--theme-option-heading-button-disabled-hover: #555869;
--theme-option-heading-button-text-disabled-hover: #828d9e;
```
So the result is:
=> fix: update dark theme for disabled button in menu

src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmTransfer.vue, src/renderer/components/Transaction/TransactionShow/TransactionShow.vue
When a viewing a transaction modal with a large vendor field message, the message up into individual lines to keep the modal at a reasonable size. 
**Before:**
**After:**
=> fix: break words if the vendor field message is large

src/renderer/components/Input/InputCurrency.vue
Fixes the vertical alignment of the alternative amount in the currency input.
=> chore: fix alternative currency alignment

src/renderer/services/plugin-manager.js
Fixes: fetching of the preview images was nested in the catch black, therefore was never called when the service successfully read the logo file of a locally installed plugin.
Refactors: instead of fetching the preview images from the defined URLs directly, try to get the images from a default path first (`images/`).
=> refactor: try to fetch local plugin images first

__tests__/unit/services/plugin-manager/sandbox/storage-sandbox.spec.js, src/renderer/services/plugin-manager/sandbox/storage-sandbox.js
Extends the storage sandbox by a `clear(global = false)` method which allows plugins to clear their stored data at once.
=> feat: allow plugins to clear all options at once

src/renderer/components/Input/InputPassword.vue, src/renderer/components/Passphrase/PassphraseInput.vue
When toggling the visibility of the passphrase and password inputs the focus is set before the component is fully rendered, thus causing the focus to be set at the beginning of the input and not at the end.
=> refactor: wait for next tick when focussing password/passphrase input

__tests__/unit/services/plugin-manager/setup/menu-items-setup.spec.js, __tests__/unit/services/plugin-manager/setup/routes-setup.spec.js, src/renderer/services/plugin-manager/sandbox/route-sandbox.js, src/renderer/services/plugin-manager/setup/menu-items-setup.js, src/renderer/services/plugin-manager/setup/routes-setup.js
Multiple plugins that define the same routes can currently result in unexpected routing. For example the following configuration will potentially route to the original ARK Explorer plugin (if installed and enabled):
```
this.routes = [
{
path: '/my-ark-explorer,
name: 'ark-explorer',
component: 'MyExplorer
}
]
this.menuItems = [
{
routeName: 'ark-explorer',
title: 'My ARK Explorer'
}
]
```
This PR scopes the plugin routes under the plugin's id. Navigation through the `ROUTES` permission can still be done without using the scope.
=> feat: add scope to plugin routes and menu items

src/renderer/components/Transaction/TransactionTable/TransactionTable.vue
Removes the sorting capabilities of the `hash` column over IPFS. This prevents erros from unsortable parameters.
=> fix: remove sort option for IPFS from table

__tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmMultiPayment.spec.js, src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmMultiPayment.vue, src/renderer/components/Transaction/TransactionModal.vue, src/renderer/components/Transaction/TransactionShow/TransactionShow.vue, src/renderer/i18n/locales/en-US.js
**TransactionShow**
- aligns the smartbridge to the right and the label to top
**TransactionConfirmMultiPayment**
- adds the recipient count
- adds the total amount
- adds the vendorfield and fee
**TransactionModal**
- limits the max height to `80vh`
=> feat: multipayment display modals details

src/renderer/components/App/AppSidemenu/AppSidemenuPlugins.vue
If 5+ plugins are installed then add a scrollbar to the plugin list.
**before:**
**after:**
=> fix: add scrollbar to installed plugin list

src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue, src/renderer/i18n/locales/en-US.js, src/renderer/pages/Profile/ProfileEdition.vue, src/renderer/services/plugin-manager/setup/themes-setup.js
With this PR plugin themes can have an additional `name` property in their config, which will show up in the respective dropdowns in the app sidemenu and profile edition page.
This also adds localisation to the default light / dark themes and prefixes them with `Default: `.
I will add sorting to the plugin themes once #1823 is merged to not duplicate the necessary changes.
=> feat: add names to plugin themes

__tests__/unit/components/App/AppSidemenu/AppSidemenu.spec.js, src/renderer/components/App/AppSidemenu/AppSidemenu.vue, src/renderer/components/App/AppSidemenu/AppSidemenuPlugins.vue
With these changes the plugin page menu item gets activated upon navigating to a plugin page.
=> refactor: activate the plugin menu item when navigating to plugin route

src/renderer/components/PluginManager/PluginManagerModals/PluginRemovalModal.vue, src/renderer/store/modules/plugin.js
When removing a plugin only the options stored for a proper plugin id are deleted, the global options are not regarded. With these PR the "remove options" toggle shows up also for globally stored plugin options, and deletes those accordingly.
=> fix: also delete global options when removing a plugin

src/renderer/components/Modal/ModalWindow.vue
Fixes #1827. 
The `once` property in `addEventListener` has been removed because if true, the listener would be automatically removed when invoked.
The `keyCode` is  deprecated: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
The problem with using `keyCode` is that non-English keyboards can produce different outputs and even keyboards with different layouts can produce inconsistent results.
=> fix: close modal using the esc key after pressing other keys

__tests__/unit/store/modules/wallet.spec.js, src/renderer/store/modules/wallet.js
Plugins might need to know about the current vote of a profiles wallet. Instead of having to make a dedicated request to retrieve the vote of each wallet it should be included in the response of the `wallet/publicByProfileId` getter.
=> feat: include wallet vote in publicByProfileId getter

__tests__/unit/components/Plugin/PluginWrapper.spec.js, src/renderer/components/Plugin/PluginWrapper.vue
When a plugin changes the app footer in one of it's components a wormhole is opened with the respective content. This wormhole however isn't closed when the plugin wrapper is destroyed, causing the change of the footer to be persistent.
This PR closes the wormhole when the plugin wrapper is destroyed.
=> fix: plugin footer override on destroy

__tests__/unit/services/plugin-manager.spec.js, __tests__/unit/store/modules/plugin.spec.js, src/renderer/services/plugin-manager.js, src/renderer/services/plugin-manager/config-sanitizers.js, src/renderer/services/plugin-manager/plugin-configuration.js, src/renderer/store/modules/plugin.js
=> refactor: rename minVersion property to minimumVersion

src/renderer/components/Selection/SelectionTheme.vue, src/renderer/components/Transaction/TransactionModal.vue
=> refactor: remove lodash findkey

src/renderer/pages/Profile/ProfileEdition.vue, src/renderer/pages/Profile/ProfileNew.vue
When creating and editing a new profile, avatar and background images should not have click action. So there is no need for a cursor pointer and opacity styles.
**Current Behavior**
=> chore: remove the cursor and opacity for avatar and background selection

config/index.js
Minor change adding a comment about changing the plugin config.
It's already fairly obvious the plugin section shouldn't be changed when you look at what it does,
but this comment could still be pretty useful for others.
```javascript
// This section handles fetching Desktop-Wallet Plugins from the NPM registry.
// It should remain "ARK" unless intentionally implementing a custom package.
```
=> chore(config): add plugin comment

src/renderer/App.vue, src/renderer/services/plugin-manager.js, src/renderer/services/plugin-manager/adapters/npm-adapter.js, src/renderer/services/wallet.js, src/renderer/store/modules/network.js, src/renderer/utils/http.js
`got` by default has no timeout which means requests are ongoing until the server terminates them. Also, any exceptions thrown during the plugin manager bootstrap weren't handled so the wallet would get stuck.
=> fix: timeout NPM requests and continue execution

__tests__/unit/components/Input/InputPassword.spec.js, src/renderer/components/Input/InputPassword.vue, src/renderer/i18n/locales/en-US.js
> Resolves https://github.com/ArkEcosystem/desktop-wallet/issues/1895
Ensures that a value is set when `InputPassword#isValid` is called. Also adds a bit stricter and more readable regex validation to ensure certain strength criteria are met.
=> fix: ensure that password has value before validating it and better regex

__tests__/unit/components/Transaction/TransactionForm/TransactionFormTransfer.spec.js, src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue, src/renderer/i18n/locales/en-US.js
=> feat: auto-add the recipient if loading the modal using a URI

src/renderer/components/Transaction/TransactionConfirm/TransactionConfirm.vue
Canceling the save file dialog should not show a success message.
**Steps to Reproduce**
1. Go to wallets
2. Select a wallet
3. Click on "Send" button
4. Fill out the transaction form
5. Click on "Next" button
6. Click on "Save" button
7. Close / cancel the dialog box
8. See success message
=> fix: does not show success message when canceling a save file dialog

.storybook/Layout.tsx, .storybook/preview.js, src/app/components/Alert/Alert.stories.tsx, src/app/components/Alert/Alert.tsx, src/app/components/Alert/__tests__/Alert.spec.tsx, src/app/components/Alert/__tests__/__snapshots__/Alert.spec.tsx.snap, src/app/components/Alert/style.ts, src/app/components/Button/__tests__/__snapshots__/Button.spec.tsx.snap, src/app/components/Button/style.ts, src/app/components/ListDivided/ListDivided.tsx, src/app/components/ListDivided/index.tsx, src/app/components/SvgIcon/SvgIcon.tsx, src/app/components/SvgIcon/index.tsx, src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap, src/domains/profile/pages/Welcome/__tests__/Welcome.spec.tsx, src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap, src/domains/profile/routing.tsx, src/domains/wallets/pages/ImportWallet/__tests__/ImportWallet.spec.tsx, src/domains/wallets/pages/ImportWallet/__tests__/__snapshots__/ImportWallet.spec.tsx.snap, src/i18n/index.ts, src/i18n/locales/en-US/config.ts, src/i18n/locales/en-US/messages.ts, src/i18n/locales/index.ts, src/index.tsx, src/resources/assets/images/index.ts, src/resources/assets/svg/index.ts, src/router/index.tsx
As previously mentioned it should be avoided to use default exports because they lead to inconsistent naming and imports because you can use any name you want instead of being forced to use a specific one.
=> refactor: avoid default exports

.storybook/preview.js, cypress/plugins/index.js, package.json, src/app/components/SideBar/SideBar.stories.tsx, src/app/components/SideBar/SideBar.tsx, src/app/components/SideBar/SideBarItem/SideBarItem.stories.tsx, src/app/components/SideBar/SideBarItem/SideBarItem.tsx, src/app/components/SideBar/SideBarItem/__tests__/SideBarItem.spec.tsx, src/app/components/SideBar/SideBarItem/__tests__/__snapshots__/SideBarItem.spec.tsx.snap, src/app/components/SideBar/SideBarItem/index.tsx, src/app/components/SideBar/__tests__/SideBar.spec.tsx, src/app/components/SideBar/__tests__/__snapshots__/SideBar.spec.tsx.snap, src/app/components/SideBar/index.ts, src/resources/assets/svg/general.svg, src/resources/assets/svg/index.ts, src/resources/assets/svg/peer.svg, src/resources/assets/svg/plugin.svg, yarn.lock
=> feat: add side bar component

package.json, src/__tests__/__snapshots__/index.spec.ts.snap, src/index.tsx, src/tailwind.config.js, yarn.lock
The [TailwindCSS Debug Screens](https://github.com/jorenvanhee/tailwindcss-debug-screens) plugin will display the currently active screen in development mode.
=> chore: add tailwindcss debug screens

src/domains/profile/components/ProfileCard/ProfileCard.stories.tsx, src/domains/profile/pages/CreateProfile/CreateProfile.stories.tsx, src/domains/profile/pages/Welcome/Welcome.stories.tsx, src/domains/wallets/components/WalletMnemonicList/WalletMnemonicList.stories.tsx, src/domains/wallets/components/WalletMnemonicList/WalletMnemonicList.tsx, src/domains/wallets/components/WalletMnemonicList/__tests__/WalletMnemonicList.spec.tsx, src/domains/wallets/components/WalletMnemonicList/__tests__/__snapshots__/WalletMnemonicList.spec.tsx.snap, src/domains/wallets/components/WalletMnemonicList/index.ts, src/domains/wallets/pages/ImportWallet/ImportWallet.stories.tsx
Copy pasta from `3.0-slate` branch.
=> feat: add `WalletMnemonicList` component

src/app/components/Dropdown/Dropdown.stories.tsx, src/app/components/Dropdown/Dropdown.tsx, src/app/components/Dropdown/__tests__/Dropdown.spec.tsx, src/app/components/Dropdown/__tests__/__snapshots__/Dropdown.spec.tsx.snap, src/app/components/Dropdown/hooks.ts
General-purpose `Dropdown` component.
* Accepts a list of options `[{label: 'Option 1', value: '1'}]` - Triggers `onSelect` event
* or custom content `<Dropdown>custom content</Dropdown>`
* Custom toggle svg icon name  with `toggleIcon` prop
`<Dropdown iconName="settings">custom content</Dropdown>`
=> feat: component dropdown

src/app/components/Form/FormLabel.tsx, src/app/components/Form/__tests__/__snapshots__/FormLabel.spec.tsx.snap, src/app/components/Header/Header.tsx, src/app/components/Header/__tests__/Header.spec.tsx, src/app/components/Header/__tests__/__snapshots__/Header.spec.tsx.snap, src/app/components/Header/index.ts, src/app/components/ListDivided/ListDivided.tsx, src/app/components/ListDivided/ListDividedItem.tsx, src/app/components/ListDivided/__tests__/__snapshots__/ListDivided.spec.tsx.snap, src/app/components/ListDivided/__tests__/__snapshots__/ListDividedItem.spec.tsx.snap, src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap, src/domains/settings/pages/Settings/Settings.stories.tsx, src/domains/settings/pages/Settings/Settings.tsx, src/domains/settings/pages/Settings/__tests__/Settings.spec.tsx, src/domains/settings/pages/Settings/__tests__/__snapshots__/Settings.spec.tsx.snap, src/domains/settings/pages/Settings/available-settings/General.tsx, src/domains/settings/pages/Settings/available-settings/index.ts, src/domains/settings/pages/Settings/index.tsx
- Add settings generic page
- Add general settings content
- Adds sidebar component
- Adds header generic component
=> feat: add settings page

src/app/components/Dropdown/Dropdown.tsx, src/app/components/Dropdown/index.ts, src/app/components/Header/index.ts, src/app/components/ListDivided/ListDividedItem.tsx, src/domains/settings/pages/Settings/Settings.tsx, src/domains/settings/pages/Settings/__tests__/__snapshots__/Settings.spec.tsx.snap, src/domains/settings/pages/Settings/available-settings/General.tsx, src/domains/settings/pages/Settings/available-settings/index.ts
=> fix: build errors

src/app/components/Alert/Alert.tsx, src/app/components/Alert/__tests__/__snapshots__/Alert.spec.tsx.snap, src/domains/wallets/components/VerifyMessage/VerifyMessage.stories.tsx, src/domains/wallets/components/VerifyMessage/VerifyMessage.tsx, src/domains/wallets/components/VerifyMessage/__tests__/VerifyMessage.spec.tsx, src/domains/wallets/components/VerifyMessage/__tests__/__snapshots__/VerifyMessage.spec.tsx.snap, src/domains/wallets/components/VerifyMessage/index.ts
- Add verify message modal component. We could need to change this due to #2074 if we go for a generic modal.
**Verify ON**
**Verify OFF**
=> feat: add verify message

src/app/components/Dropdown/Dropdown.tsx, src/app/components/WalletCard/WalletCard.stories.tsx, src/app/components/WalletCard/WalletCard.tsx, src/app/components/WalletCard/__tests__/WalletCard.spec.tsx, src/app/components/WalletCard/__tests__/__snapshots__/WalletCard.spec.tsx.snap, src/app/components/WalletCard/index.ts
Add `Wallet Card` component.
Displays wallet as cards. Seen in dashboard page.
Usage:
```
<WalletCard
coinIcon="eth"
coinIconClass="border-theme-neutral-800"
avatarId="test"
walletName="Primary"
address="ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT"
balance="100,000 ETH"
actions={[
{ label: "Action 1", value: "1" },
{ label: "Action 1", value: "1" },
]}
onSelect={(selected: any) => console.log(selected)}
/>
```
=> feat: add wallet card component

__tests__/unit/__mocks__/@arkecosystem/ledger-transport.js, __tests__/unit/services/ledger-service.spec.js, __tests__/unit/services/transaction.spec.js, __tests__/unit/store/modules/ledger.spec.js, package.json, src/renderer/services/ledger-service.js, src/renderer/services/transaction.js, src/renderer/store/modules/ledger.js, yarn.lock
- update `Ledger-Transport` package, `1.0.5` -> `1.1.1`.
- add support for Schnorr signatures w/Ledger.
- \+ `signMessageWithSchnorr`
- \+ `signTransactionWithSchnorr`
- add check for tx-versions >= 2 in `services/transaction.js`.
- add/update unit tests for additions/changes.
~WIP until [Ledger-Transport](https://github.com/ArkEcosystem/ledger-transport) [1.1.0](https://github.com/ArkEcosystem/ledger-transport/pull/35) is released and can be updated here.~
WIP until testing is done and functionality is confirmed for NanoS & NanoX.
=> feat(ledger): add schnorr support

src/app/assets/svg/ark.svg, src/app/assets/svg/btc.svg, src/app/assets/svg/eth.svg, src/app/components/Badge/Badge.stories.tsx, src/app/components/Badge/Badge.tsx, src/app/components/Badge/__tests__/Badge.spec.tsx, src/app/components/Badge/__tests__/__snapshots__/Badge.spec.tsx.snap, src/app/components/Badge/index.ts, src/app/components/Badge/style.ts
General purpose badge component to be used along with avatars, coin icons et. all
* requires a parent with relative positon.
* position, size, shape, colors, controlled by regular (tailwind) css classes  (e.g -right-2 -bottom-2).
* `icon="name"` prop to internally render an `Icon` component.
* accepts slot for custom content.
Preview:
=> feat: add Badge component

src/app/components/Dropdown/Dropdown.stories.tsx, src/app/components/Dropdown/Dropdown.tsx, src/app/components/Dropdown/__tests__/Dropdown.test.tsx, src/app/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
Adds the feature to accept `toggleContent` to render custom elements.
Accepts function as a prop and provides `isOpen` state to render dynamically.
Example:
As element:
```jsx
<Dropdown
options={options}
toggleContent={<div>sample toggle content</div>}>
</Dropdown>
```
As a function:
```jsx
<Dropdown
options={options}
toggleContent={(isOpen) => (<div>sample toggle content</div>)}>
</Dropdown>
```
=> chore: add toggle content prop on `Dropdown`

src/app/components/TransactionListItem/TransactionListItem.stories.tsx, src/app/components/TransactionListItem/TransactionListItem.test.tsx, src/app/components/TransactionListItem/TransactionListItem.tsx, src/app/components/TransactionListItem/__snapshots__/TransactionListItem.test.tsx.snap, src/app/components/TransactionListItem/models.ts, src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
Add `compact` variant to `TransactionListItem` component. Uses same data fields as `default` variant.
Seen in Notifications transactions lists.
Preview:
Usage: 
```jsx
<TransactionListItem variant="compact" {...data}></TransactionListItem>
```
=> feat: add compact variant to `TransactionListItem`

src/app/components/WalletListItem/WalletListItem.stories.tsx, src/app/components/WalletListItem/WalletListItem.test.tsx, src/app/components/WalletListItem/WalletListItem.tsx, src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
Adds a variant prop to the WalletListItem component which if set to `singleAction` will display a button instead of the dropdown.
Also allows to not render the table cell for the wallet type icons by setting the `walletTypeIcons` prop to `null`.
=> feat: add singleAction variant to wallet list item component

src/app/components/NavBar/NavBar.stories.tsx, src/app/components/NavBar/NavBar.tsx, src/app/components/NavBar/__snapshots__/NavBar.test.tsx.snap, src/app/components/Notifications/Notifications.stories.tsx, src/app/components/Notifications/Notifications.tsx, src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap, src/app/components/Notifications/models.ts, src/app/components/Table/Table.styles.ts, src/app/components/Table/Table.tsx, src/app/components/Table/__snapshots__/Table.test.tsx.snap, src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
* Add `Notifications` dropdown in `NavBar`
* Add new props in `NavBar`
NavBar API:
```jsx
const notifications = {
pluginsHeader: "Plugin Jun 16, 2020",
plugins: [
{
logoClassName: "w-8 h-8 p-2 mr-4 rounded-lg bg-logo",
title: "ARK Explorer",
description: "- update v2.5.6",
action: {
label: "Update now",
value: "update",
},
},
],
transactionsHeader: "Transaction Jun 16, 2020",
transactions: [
{
date: "17 Mar 2020 22:02:10",
avatarId: "test",
type: "send",
address: "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
walletName: "My Wallet",
amount: "100 BTC",
fiat: "1,000,000 USD",
},
{
date: "17 Mar 2020 22:02:10",
avatarId: "test",
type: "receive",
address: "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
walletName: "My Wallet",
amount: "100 BTC",
fiat: "1,000,000 USD",
},
],
};
return (
<div>
<NavBar …
```
=> feat: integrate `Notifications` in `NavBar`

src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.test.tsx
The component calls `setState` (`handleBack()` and `handleNext()`) and re-renders. `findByTestId` waits until the `TestId` is found.
=> test: fix the warning not involved in act for `MultiSignatureDetail` tests

src/app/components/Address/Address.stories.tsx, src/app/components/Address/Address.tsx, src/app/components/Address/__snapshots__/Address.test.tsx.snap
Fixes the address font color when there's no name and adds size knobs to the storyboard, e.g.
=> fix: use darker color when no wallet name given

src/app/components/Header/Header.stories.tsx, src/app/components/Header/Header.test.tsx, src/app/components/Header/Header.tsx, src/app/components/Header/__snapshots__/Header.test.tsx.snap, src/domains/settings/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/wallets/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
Adds an `extra` prop to the Header component, useful for buttons or the like.
=> feat: add `extra` prop to wallet header

src/__snapshots__/index.test.ts.snap, src/domains/plugins/components/BestPlugins/BestPlugins.stories.tsx, src/domains/plugins/components/BestPlugins/BestPlugins.test.tsx, src/domains/plugins/components/BestPlugins/BestPlugins.tsx, src/domains/plugins/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap, src/domains/plugins/components/BestPlugins/index.ts, src/domains/plugins/i18n.ts
**Note:** Only the banner is missing. It can be added later.
=> feat: add best plugins modal

src/domains/plugins/components/PluginInfo/PluginInfo.spec.tsx, src/domains/plugins/components/PluginInfo/PluginInfo.stories.tsx, src/domains/plugins/components/PluginInfo/PluginInfo.tsx, src/domains/plugins/components/PluginInfo/__snapshots__/PluginInfo.spec.tsx.snap, src/domains/plugins/components/PluginInfo/index.ts
- Adds plugin info section to be used in the plugin details page
_Quick note:_ screenshots will be handled differently depending on the received data, the idea is to load images in the place of the current gray box placeholder
=> feat: add plugin info section component

src/app/components/Input/InputRange.tsx
Fix background width of `InputRange` when value is zero. 
Should still show a minimum background color when zero.
=> fix: add minimum colored bg width to `InputRange`

src/app/components/Header/HeaderSearchBar/HeaderSearchBar.test.tsx, src/domains/plugin/components/Comments/Comments.test.tsx, src/domains/plugin/components/Comments/__snapshots__/Comments.test.tsx.snap, src/domains/plugin/components/Comments/components/Reply/__snapshots__/Reply.test.tsx.snap, src/domains/plugin/pages/PluginDetails/PluginDetails.test.tsx, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
Gets rid of the i18n and header search bar warnings in the unit tests. There are more warnings remaining, but those should be taken care of when refactoring the tested component.
=> refactor: get rid of jest warnings

src/domains/transaction/pages/TransactionSendIPFS/TransactionSendIPFS.stories.tsx, src/domains/transaction/pages/TransactionSendIPFS/TransactionSendIPFS.tsx, src/domains/transaction/pages/TransactionSendIPFS/__snapshots__/TransactionSendIPFS.spec.tsx.snap
The distance between Network field and Sender will be fixed by  https://github.com/ArkEcosystem/desktop-wallet/pull/2282
=> feat: add `SelectAsset` in `TransactionSendIPFS` modal

src/domains/wallet/components/WalletBottomSheetMenu/WalletBottomSheetMenu.tsx, src/domains/wallet/components/WalletRegistrations/WalletRegistrations.stories.tsx, src/domains/wallet/components/WalletRegistrations/WalletRegistrations.test.tsx, src/domains/wallet/components/WalletRegistrations/WalletRegistrations.tsx, src/domains/wallet/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap
Add empty mode to the `WalletRegistrations` section.
=> refactor: add empty mode to `WalletRegistrations`

src/app/components/SelectDropdown/SelectDropdown.stories.tsx, src/app/components/SelectDropdown/SelectDropdown.test.tsx, src/app/components/SelectDropdown/SelectDropdown.tsx, src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
* Add initial selected value on `SelectDropdown`
* Add `onChange` event
Usage:
```jsx
const options = [
{
label: "Option 1",
value: "1",
},
{
label: "Option 2",
value: "2",
},
{
label: "Option 3",
value: "3",
},
];
const { container } = render(
<SelectDropdown
option={(option: any) => <div>{option.label}</div>}
toggle={() => {
return (
<div className="flex items-center flex-inline">Select</div>
);
}}
selected={{ label: "Option 1", value: "1" }}
options={options}
onChange={(selectedItem) => console.log(selectedItem)}
/>,
);
```
=> refactor: add form events on `SelectDropdown`

jest.setup.js, package.json, src/domains/plugin/components/Comments/Comments.test.tsx, src/domains/plugin/components/Comments/__snapshots__/Comments.test.tsx.snap, src/domains/plugin/components/Comments/components/Reply/Reply.test.tsx, src/domains/plugin/components/Comments/components/Reply/__snapshots__/Reply.test.tsx.snap, src/domains/plugin/components/Comments/utils.test.ts, src/domains/plugin/components/Comments/utils.ts, src/domains/plugin/pages/PluginDetails/PluginDetails.test.tsx, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
Adds a jest setup to set a mockdate before each test. The mocked date has been arbitrarily set to `2020-07-01T00:00:00.000Z`.
=> test: mock date globally

src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap, src/domains/vote/components/AddressListItem/AddressListItem.tsx, src/domains/vote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap, src/domains/vote/components/DelegateList/DelegateList.tsx, src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap, src/domains/vote/components/DelegateListItem/DelegateListItem.tsx, src/domains/vote/components/DelegateListItem/__snapshots__/DelegateListItem.test.tsx.snap, src/domains/vote/pages/Votes/Votes.test.tsx, src/domains/vote/pages/Votes/Votes.tsx, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
UI changes requested by @samharperpittam.
=> refactor: votes page ui adjustments

cypress/integration/startup.spec.js, package.json, src/__snapshots__/index.test.ts.snap, src/app/contexts/Environment.tsx, src/app/index.tsx, src/domains/profile/pages/Welcome/Welcome.test.tsx, src/domains/profile/pages/Welcome/Welcome.tsx, src/domains/profile/routing.ts, src/tests/fixtures/identity.ts
- Adds an extra step for when the app detects an env var called `REACT_APP_BUILD_MODE` equal to `demo` firing a demo bootstrap adding only a profile.
=> feat: add demo environment

src/app/components/CircularProgressBar/CircularProgressBar.stories.tsx, src/app/components/CircularProgressBar/CircularProgressBar.test.tsx, src/app/components/CircularProgressBar/CircularProgressBar.tsx, src/app/components/CircularProgressBar/__snapshots__/CircularProgressBar.test.tsx.snap, src/domains/plugin/components/InstallPlugin/InstallPlugin.tsx, src/domains/plugin/components/InstallPlugin/__snapshots__/InstallPlugin.test.tsx.snap
Render the `%` in a smaller font.
=> refactor: `CircularProgressBar` component ui adjustments

src/app/components/Breadcrumbs/Breadcrumbs.test.tsx, src/app/components/Breadcrumbs/Breadcrumbs.tsx, src/app/components/Link/Link.test.tsx, src/app/components/NavigationBar/NavigationBar.test.tsx, src/app/components/SideBar/SideBar.test.tsx, src/app/components/SideBar/SideBarItem/SideBarItem.test.tsx, src/app/index.test.tsx, src/domains/contact/pages/Contacts/Contacts.test.tsx, src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx, src/domains/profile/pages/MyRegistrations/components/HistoryModal/HistoryModal.test.tsx, src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap, src/domains/profile/pages/MyRegistrations/components/RepositoryModal/RepositoryModal.test.tsx, src/domains/profile/pages/MyRegistrations/components/RepositoryModal/__snapshots__/RepositoryModal.test.tsx.snap, src/domains/profile/pages/MyRegistrations/components/RepositoryModal/components/RepositoryLink/RepositoryLink.test.tsx, src/domains/profile/pages/MyRegistrations/components/RepositoryModal/components/RepositoryLink/__snapshots__/RepositoryLink.test.tsx.snap, src/domains/profile/pages/Welcome/Welcome.test.tsx, src/domains/setting/pages/Settings/Settings.test.tsx, src/domains/vote/pages/Votes/Votes.test.tsx, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap, src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx, src/utils/testing-library.tsx
Adds a helper method for tests that renders a component with a Router. Routes can be passed to the method and it will expose the history object.
```ts
import { renderWithRouter } from "testing-library";
const { history } = renderWithRouter(<MyComponent />, {
routes: ["/", "/my/component/route"],
});
```
=> refactor: add renderWithRouter helper method

src/app/components/Card/Card.tsx
Fix `handleClick is not a function` error on click event in Card component when `handleClick` callback is not provided.
=> chore: fix card handleclick error on `Card`

src/app/components/Header/HeaderSearchBar/HeaderSearchBar.test.tsx, src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Add support for extra slot to add additional menu items (e.g plugin filters):
Preview:
=> feat: add extra slot in `HeaderSearchBar`

src/app/components/FilterNetwork/FilterNetwork.stories.tsx, src/app/components/FilterNetwork/FilterNetwork.test.tsx, src/app/components/FilterNetwork/FilterNetwork.tsx, src/app/components/FilterNetwork/__snapshots__/FilterNetwork.test.tsx.snap
The News page uses this component without showing the "all" option. See the image below:
=> chore: add `hideViewAll` props to `FilterNetwork` component

src/app/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap, src/app/components/Divider/Divider.styles.ts, src/app/components/Divider/__snapshots__/Divider.test.tsx.snap, src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap, src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap, src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx, src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap, src/domains/plugin/components/PluginManagerNavigationBar/styles.ts, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
Fixes the paddings of the plugin navigationbar items to match the designs. Also replaces the anchor tags with buttons so they can be activated without changing url in the storybook.
=> refactor: fix paddings in plugin navigation

src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap, src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap, src/domains/exchange/components/ExchangeCard/__snapshots__/ExchangeCard.test.tsx.snap, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap, src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap, src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap, src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/tailwind.config.js
Remove white shadow from `shadow-xl` in `tailwind.config`
Fixes issues when a shadowed element is on top of darker background.
Example:
=> refactor: remove white shadow from `shadow-xl`

src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap, src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap, src/domains/exchange/components/ExchangeCard/__snapshots__/ExchangeCard.test.tsx.snap, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap, src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap, src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap, src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap, src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/tailwind.config.js
Replace hardcoded value with `neutral-rbg` and opacity for `shadow-xl`
=> fix: use neutral variable in `shadow-xl`

src/app/components/Card/Card.stories.tsx, src/app/components/Card/CardControl.tsx, src/app/components/Card/__snapshots__/CardControl.test.tsx.snap
The `readonly` is not supported for `checkbox` and `radio`.
> The readonly attribute is supported by  text, search, url, tel, email, password, date, month, week, time, datetime-local, and number<input> types and the <textarea> form control elements.
**Reference:** https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly
=> refactor: remove readonly and add disabled property

src/domains/profile/components/SelectRecipient/SelectRecipient.stories.tsx, src/domains/profile/components/SelectRecipient/SelectRecipient.test.tsx, src/domains/profile/components/SelectRecipient/SelectRecipient.tsx, src/domains/profile/components/SelectRecipient/__snapshots__/SelectRecipient.test.tsx.snap, src/domains/profile/components/SelectRecipient/index.ts
Create `SelectRecipient` component to be used in Transaction Send form
* Allows user to enter custom address (free text input)
* When clicked on the "user" icon, the `ContactSearch` modal is opened to pick existing contacts.
=> feat: create `SelectRecipient` form input

config-overrides.js
Prevent using `electron-renderer` as config target in webpack config-overrides.
Fixes `global is not defined` error in storybook.
=> fix: modify webpack config for storybook

.storybook/main.js, .storybook/mocks/fsMock.js, config-overrides.js
- This adds a custom configuration for the storybook webpack to avoid the `electron-renderer` target removal from the base config to make storybook works since this target is needed to correctly load the node packages used into the app.
=> fix: webpack config

src/domains/transaction/e2e/transactions-routing.e2e.ts, src/domains/wallet/components/SignMessage/SignMessage.test.tsx, src/domains/wallet/components/SignMessage/SignMessage.tsx, src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap, src/domains/wallet/e2e/sign-message-action.e2e.ts, src/domains/wallet/e2e/verify-message-action.e2e.ts, src/domains/wallet/i18n.ts
- Add i18n
- Add json data for signature
- Add test to the copy button
- Move E2E tests to wallet domain
=> refactor: `SignMessage` modal tweaks

src/app/assets/svg/currencies/index.ts, src/app/assets/svg/index.ts
Moves the currency icons to their own module.
=> chore: move currency icons to own module

src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap, src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap, src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap, src/domains/network/components/SelectNetwork/SelectNetworkInput.tsx, src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap, src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap, src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap, src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap, src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap, src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap, src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Remove white shadow from the network icon when the `SelectNetworkInput` component is disabled.
=> chore: add `noShadow` to the network icon in the `SelectNetworkInput`

src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx, src/domains/profile/pages/CreateProfile/CreateProfile.tsx, src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
=> chore: remove error message when select an item of dropdown

src/domains/wallet/components/SignMessage/SignMessage.tsx, src/domains/wallet/components/VerifyMessageStatus/VerifyMessageStatus.tsx, src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
- Break the message when is very long.
- Reset the state when close the modal.
Fixes: https://trello.com/c/e8pcMUhN/108-implement-message-signing#comment-5f292d9f40a8c362146a9989
=> refactor: show form in `SignMessage` when closing modal

src/domains/contact/components/CreateContact/CreateContact.stories.tsx, src/domains/contact/components/CreateContact/CreateContact.test.tsx, src/domains/contact/components/CreateContact/CreateContact.tsx, src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap, src/domains/contact/e2e/create-contact.e2e.ts, src/domains/contact/i18n.ts
Depends on https://github.com/ArkEcosystem/desktop-wallet/pull/2596
* Add validations in Contact name field (existing contact from sdk, empty name)
* Add coverage and e2e tests
=> refactor: add `CreateContact` validations and tests

src/app/services/Cache.test.ts, src/app/services/Cache.ts, src/app/services/HttpClient.test.ts, src/app/services/HttpClient.ts, src/app/services/index.ts
This will cache HTTP requests for 10 seconds based on their URL. This reduces the number of requests that have to be sent when the wallet boots because it would retrieve things like the network configuration once instead of 100 times if you have 100 wallets.
=> feat: cache HTTP requests based on their URL

src/domains/contact/components/ContactForm/ContactForm.test.tsx, src/domains/contact/components/CreateContact/CreateContact.test.tsx, src/domains/contact/components/UpdateContact/UpdateContact.test.tsx, src/domains/contact/pages/Contacts/Contacts.test.tsx, src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx, src/domains/vote/pages/Votes/Votes.test.tsx, src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx, src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
=> chore: rename `selectAsset` variations to `selectNetworkInput`

src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
Fixes: 
```
● Dashboard › should fetch more transactions
expect(received).toHaveLength(expected)
Expected length: 20
Received length: 10
Received array:  [<tr class="border-b border-dotted border-theme-neutral-300" data-testid="TransactionRow"><td … /><td … /><td … /><td … /><td … /><td … /><td … /><td … /></tr>, <tr class="border-b border-dotted border-theme-neutral-300" data-testid="TransactionRow"><td … /><td … /><td … /><td … /><td … /><td … /><td … /><td … /></tr>, <tr class="border-b border-dotted border-theme-neutral-300" data-testid="TransactionRow"><td … /><td … /><td … /><td … /><td … /><td … /><td … /><td … /></tr>, <tr class="border-b border-dotted border-theme-neutral-300" data-testid="TransactionRow"><td … /><td … /><td … /><td … /><td … /><td … /><td … /><td … /></tr>, <tr …
```
=> fix: dashboard tests

src/domains/dashboard/pages/Dashboard/Dashboard.tsx, src/domains/profile/components/SignIn/SignIn.test.tsx, src/domains/profile/middleware.test.ts, src/domains/profile/middleware.ts, src/domains/splash/e2e/splash-screen.e2e.ts, src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
Moves the setting of the screenshot protection to the profile middleware, so that it's enabled / disabled on every matching route change.
=> refactor: move screenshotprotection to profile middleware

src/domains/dashboard/e2e/navbar-routing.e2e.ts, src/domains/news/e2e/common.ts, src/domains/news/e2e/filtering.e2e.ts, src/domains/news/e2e/news-routing.e2e.ts, src/domains/plugin/e2e/common.ts, src/domains/plugin/e2e/plugins-routing.e2e.ts, src/domains/profile/e2e/common.ts, src/domains/profile/e2e/create-profile-action.e2e.ts, src/domains/profile/e2e/create-profile-routing.e2e.ts, src/domains/profile/e2e/delete-profile-action.e2e.ts, src/domains/profile/e2e/my-registrations-routing.e2e.ts, src/domains/profile/e2e/navigate-profile-settings.e2e.ts, src/domains/profile/e2e/welcome-screen.e2e.ts, src/domains/setting/e2e/common.ts, src/domains/setting/e2e/save-settings.e2e.ts, src/domains/setting/e2e/settings-routing.e2e.ts, src/domains/splash/e2e/splash-screen.e2e.ts, src/domains/transaction/e2e/delegate-registration.e2e.ts, src/domains/transaction/e2e/transactions-routing.e2e.ts, src/domains/wallet/e2e/delete-wallet-action.e2e.ts, src/domains/wallet/e2e/sign-message-action.e2e.ts, src/domains/wallet/e2e/update-wallet-name-action.e2e.ts, src/domains/wallet/e2e/verify-message-action.e2e.ts, src/utils/e2e-utils.ts
Some general refactoring of e2e tests.
=> refactor: cleanup and use utils in e2e tests

.github/workflows/test.yml, .testcaferc.json
e2e failure screenshots are not being uploaded at the moment.
=> ci: screenshots path

src/app/components/Dropdown/Dropdown.styles.ts, src/app/components/Dropdown/Dropdown.tsx, src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
https://app.clickup.com/t/7mqgb1
=> refactor: explicitly align dropdown content and remove min width

src/renderer/services/plugin-manager.js
=> fix: use default timeout to fetch the plugin logo

src/app/components/PercentageBar/PercentageBar.tsx, src/app/components/PercentageBar/__snapshots__/PercentageBar.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Removes the negative margin from the first percentage bar item.
=> fix: remove negative margin on first bar item

src/domains/wallet/components/MnemonicList/MnemonicList.tsx, src/domains/wallet/components/MnemonicVerification/MnemonicVerificationProgress.tsx, src/domains/wallet/components/MnemonicVerification/__snapshots__/MnemonicVerificationProgress.test.tsx.snap
Use the index as key instead of the mnemonic word to avoid potentially duplicate keys.
=> refactor: use index as key for mnemonic list

src/app/components/Input/InputCurrency.test.tsx
This PR fix the error message below:
```
PASS  src/app/components/Input/InputCurrency.test.tsx (374 MB heap size)
● Console
console.error node_modules/@testing-library/react/dist/act-compat.js:52
Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one.
```
=> test: fix `InputCurrency` tests

src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.stories.tsx, src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.test.tsx, src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.tsx, src/domains/transaction/components/SecondSignatureDetail/__snapshots__/SecondSignatureDetail.test.tsx.snap, src/domains/transaction/components/SecondSignatureDetail/index.tsx, src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx, src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx, src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap, src/domains/transaction/i18n.ts
Task: https://app.clickup.com/t/28z4e7
=> feat: add second signature detail

src/domains/setting/pages/Settings/Settings.test.tsx, src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
* Fix `Settings` test errors
* Fix `DelegateRegistrationForm` test errors
=> test: fix `act` errors

src/app/components/Modal/Modal.test.tsx, src/app/components/Modal/Modal.tsx, src/app/components/Modal/__snapshots__/Modal.test.tsx.snap
Task: https://app.clickup.com/t/296a7y
=> feat: close modal with ESC key

src/app/components/Modal/Modal.test.tsx, src/app/components/Modal/__snapshots__/Modal.test.tsx.snap, src/domains/news/components/NewsOptions/NewsOptions.test.tsx, src/domains/news/components/NewsOptions/NewsOptions.tsx
Task: https://app.clickup.com/t/4kpd5n
=> feat: search for a news when pressing the enter key on the input

src/app/components/EmptyBlock/EmptyBlock.stories.tsx, src/app/components/EmptyBlock/EmptyBlock.test.tsx, src/app/components/EmptyBlock/EmptyBlock.tsx, src/app/components/EmptyBlock/__snapshots__/EmptyBlock.test.tsx.snap, src/app/components/EmptyBlock/index.tsx, src/domains/dashboard/components/Transactions/Transactions.tsx, src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/vote/components/MyVoteTable/MyVoteTable.tsx, src/domains/vote/components/MyVoteTable/__snapshots__/MyVoteTable.test.tsx.snap, src/domains/wallet/i18n.ts, src/domains/wallet/pages/WalletDetails/WalletDetails.tsx, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
=> feat: add `EmptyBlock` component

src/domains/profile/pages/Welcome/Welcome.test.tsx, src/domains/profile/pages/Welcome/Welcome.tsx, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
Require password when profile card options (delete, settings) are selected for a password-protected profile card
=> feat: add password protection on `Welcome` card actions

src/app/App.tsx
- Remove a duplicated import for `useNetworkStatus` hook
=> fix: remove duplicated import

src/app/components/Input/utils.ts
`max / 100` alone does not guarantee that the step satisfies in fact the condition, that the difference between `max` and `min` must be divisible by `step`.
=> fix: adjust fallback to guarantee step is valid

src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
=> fix: not show the button to view more if the wallet has no transactions

src/app/components/Notifications/__snapshots__/NotificationTransactionItem.test.tsx.snap, src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap, src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap, src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.tsx, src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Use `whitespace-no-wrap` for date and amount columns in `TransactionRow`
=> fix: prevent wrapping label and date in `TransactionRow`

src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletRegistrations/WalletRegistrations.tsx, src/domains/wallet/pages/WalletDetails/components/WalletRegistrations/WalletRegistrationsSkeleton.tsx, src/domains/wallet/pages/WalletDetails/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.tsx, src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVoteSkeleton.tsx, src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
Reduces the line-height in the empty state of both components, so that in all different states the components content has an equal height and therefore doesn't cause any layout shifts when the state changes.
=> refactor: reduce line height in `WalletVote` and `WalletRegistrations` component

src/app/components/Notifications/Notifications.tsx, src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap, src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
An element with `position: sticky;` is positioned based on the user's scroll position.
=> fix: remove sticky position of titles in notifications

src/app/App.tsx, src/domains/error/pages/ApplicationError/ApplicationError.stories.tsx, src/domains/error/pages/ApplicationError/ApplicationError.test.tsx, src/domains/error/pages/ApplicationError/ApplicationError.tsx, src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
Task: https://app.clickup.com/t/2aztwr
=> fix: move `ErrorBoundary` inside the environment provider

src/domains/network/components/SelectNetwork/SelectNetwork.test.tsx, src/domains/network/components/SelectNetwork/SelectNetwork.tsx
Deselect network when clicking on selected asset option
=> refactor: toggle asset selection on `SelectNetwork`

src/domains/network/components/SelectNetwork/SelectNetwork.test.tsx, src/domains/network/components/SelectNetwork/SelectNetwork.tsx
Instead of clearing network options when the user deselects network by selection icon, keep network options open.
Example of previous behavior:
After:
=> refactor: `SelectNetwork` UX adjustments

src/domains/transaction/pages/SendIpfs/SendIpfs.tsx, src/domains/transaction/pages/SendTransfer/SendTransfer.tsx, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap, src/domains/transaction/pages/SendVote/SendVote.tsx
Hide back and continue buttons in the transactions page.
=> refactor: hide buttons while waiting for ledger confirmation

src/app/components/Pagination/Pagination.tsx, src/app/components/Pagination/__snapshots__/Pagination.test.tsx.snap, src/domains/news/pages/News/__snapshots__/News.test.tsx.snap, src/domains/plugin/components/Comments/__snapshots__/Comments.test.tsx.snap, src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap, src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap, src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap, src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
https://app.clickup.com/t/cgv4ag
TODO:
=> fix: pagination dark mode styling

src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap, src/domains/dashboard/components/WalletsControls/WalletsControls.tsx, src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Fixes the border color in the `WalletsControls` component.
=> fix: adjust border color in WalletsControls

src/app/hooks/index.ts, src/app/hooks/use-fees.test.tsx, src/app/hooks/use-fees.ts, src/app/hooks/use-validation.test.tsx, src/domains/transaction/components/DelegateRegistrationForm/FormStep.tsx, src/domains/transaction/components/MultiSignatureRegistrationForm/FormStep.tsx, src/domains/transaction/components/SecondSignatureRegistrationForm/GenerationStep.tsx, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx, src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.tsx, src/domains/transaction/pages/SendIpfs/SendIpfs.tsx, src/domains/transaction/pages/SendRegistration/SendRegistration.tsx, src/domains/transaction/pages/SendTransfer/SendTransfer.tsx, src/domains/transaction/pages/SendVote/FormStep.tsx, src/domains/transaction/pages/SendVote/SendVote.tsx, src/domains/transaction/validations/Common.ts
-   [x] Create new hook: `const { findByType} = useFees()`
-   [x] Sync fees on demand when calling `findByType` if fees are not already synced
-   [x] Use static fee when min/max/avg are zero or undefined
-   [x] Adjust fee validations
=> fix: ensure transaction fees are synced and available

src/app/components/Link/Link.tsx, src/app/components/Link/__snapshots__/Link.test.tsx.snap, src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap, src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/news/components/BlockfolioAd/__snapshots__/BlockfolioAd.test.tsx.snap, src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap, src/domains/news/pages/News/__snapshots__/News.test.tsx.snap, src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap, src/domains/transaction/components/DelegateResignationDetail/__snapshots__/DelegateResignationDetail.test.tsx.snap, src/domains/transaction/components/EntityDetail/__snapshots__/EntityDetail.test.tsx.snap, src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap, src/domains/transaction/components/LegacyMagistrateDetail/__snapshots__/LegacyMagistrateDetail.test.tsx.snap, src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureRegistrationDetail.test.tsx.snap, src/domains/transaction/components/SecondSignatureDetail/__snapshots__/SecondSignatureDetail.test.tsx.snap, src/domains/transaction/components/TransactionDetail/TransactionExplorerLink/__snapshots__/TransactionExplorerLink.test.tsx.snap, src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap, src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap, src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap, src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap, src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap, src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap, src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
Use dotted underline on hover state in `Link` component
Examples:
=> refactor: use dotted underline in `Link`

src/app/components/Dropdown/Dropdown.styles.ts, src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap, src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap, src/domains/transaction/components/FilterTransactions/__snapshots__/FilterTransactions.test.tsx.snap, src/domains/vote/components/VotesFilter/__snapshots__/VotesFilter.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
https://app.clickup.com/t/crxe88
=> fix: use proper dropdown background in dark mode

jest.setup.js, src/app/hooks/use-profile-synchronizer.test.tsx, src/app/hooks/use-profile-synchronizer.ts
-   [x] Use the` process.env.TEST_PROFILES_RESTORE_STATUS` flag to prevent multiple profile restoring in unit tests.
-   [x] Ensure profiles are restored properly in all modes, except in unit tests (where `TEST_PROFILES_RESTORE_STATUS` is used to coordinate restoration status)
-   [x] Fix `isDemo` check to only perform fixtures migration and profile password reset in demo mode.
=> fix: restore profile on normal & demo mode

src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap, src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/news/components/NewsCard/NewsCard.tsx, src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap, src/domains/news/pages/News/__snapshots__/News.test.tsx.snap, src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap, src/domains/transaction/components/DelegateResignationDetail/__snapshots__/DelegateResignationDetail.test.tsx.snap, src/domains/transaction/components/EntityDetail/__snapshots__/EntityDetail.test.tsx.snap, src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap, src/domains/transaction/components/LegacyMagistrateDetail/__snapshots__/LegacyMagistrateDetail.test.tsx.snap, src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureRegistrationDetail.test.tsx.snap, src/domains/transaction/components/SecondSignatureDetail/__snapshots__/SecondSignatureDetail.test.tsx.snap, src/domains/transaction/components/TransactionDetail/TransactionExplorerLink/TransactionExplorerLink.tsx, src/domains/transaction/components/TransactionDetail/TransactionExplorerLink/__snapshots__/TransactionExplorerLink.test.tsx.snap, src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx, src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap, src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap, src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap, src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap, src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap, src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
-   [x] Use external icon in Explorer links
-   [x] Use external icon in News links
=> refactor: use icon in external links

src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.tsx, src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
https://app.clickup.com/t/cpz5b2
=> chore: add external icon to `Learn more` link

src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx, src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap, src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Remove the external link icon from transaction rows
=> fix: remove external icon from transaction rows

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowInfo.tsx
https://app.clickup.com/t/d1121u
=> chore: use i18n keys in `TransactionRowInfo`

src/app/components/Dropdown/Dropdown.tsx
Fixes the DW from crashing if a dropdown option group is used without options.
=> fix: empty dropdown options groups

src/app/components/Form/FormField.tsx, src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx, src/app/components/Input/Input.tsx
This changes fixed bug with input focus when users clicked on the search icon
With these changes, users don't need to set focus on input manually
I added a new prop isFocused for the Input component. In the Input component, I created a ref via React hook useRef.  
On the component render via React hook useEffect I check if the prop isFocused is true. And then I call the focus method for current ref.
-   [x] Documentation _(if necessary)_
=> fix: focus on search icon

src/domains/transaction/components/TransactionDetail/TransactionDetail.test.tsx, src/domains/transaction/components/TransactionDetail/TransactionDetail.tsx, src/domains/transaction/components/TransactionDetail/__snapshots__/TransactionDetail.test.tsx.snap
Removes the unused `labelExtra` prop from the `TransactionDetail` component.
=> chore: remove labelExtra prop from `TransactionDetail`

src/app/components/Amount/Amount.tsx, src/app/components/NavigationBar/NavigationBar.tsx, src/app/components/WalletListItem/WalletListItem.tsx, src/domains/wallet/components/SearchWallet/SearchWallet.tsx, src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx
The balance is divided by 1e8 once already in the SDKs `convertedBalance` method, there's no need to do that again when in the DW while formatting a converted balance in a cryptocurrency.
=> fix: calculate correct converted balance

src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap, src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap, src/domains/transaction/components/TotalAmountBox/TotalAmountBox.tsx, src/domains/transaction/components/TotalAmountBox/__snapshots__/TotalAmountBox.test.tsx.snap, src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap, src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Fixes the background color of the `TotalAmountBox` component.
=> chore: use correct background color

src/app/components/NavigationBar/NavigationBar.tsx, src/domains/transaction/hooks/use-transaction-builder.ts
Seems outdated, as the transaction forms that use this hook already handle the errors in their scope.
* SendTransfer: https://github.com/ArkEcosystem/desktop-wallet/blob/develop/src/domains/transaction/pages/SendTransfer/SendTransfer.tsx#L144
* SendVote: https://github.com/ArkEcosystem/desktop-wallet/blob/develop/src/domains/transaction/pages/SendVote/SendVote.tsx#L244
* SendIpfs: https://github.com/ArkEcosystem/desktop-wallet/blob/develop/src/domains/transaction/pages/SendIpfs/SendIpfs.tsx#L88
- …
=> refactor: remove outdated todos in transaction builder

package.json, src/app/App.tsx, src/styles/app.css, src/styles/focus-visible.css, yarn.lock
Fix setting focus on button only on tabbing no click
These changes are important for UI
Added focus-visible polyfill and added some styles for focus only on tabbing
=> fix: buttons focus only in tabbing no onclick

.github/PULL_REQUEST_TEMPLATE.md
Your current GitHub PR template links to `learn.ark.dev` which redirects `/*` to `ark.dev`. I Googled the new URL for your contribution guidelines and updated it. 
-   [x] Documentation _(if necessary)_
=> chore: update contribution guidelines url

README.md
Homebrew removed the `cask` subcommand in 2.6.0 [[release notes](https://brew.sh/2020/12/01/homebrew-2.6.0/)] ([detailed explanation](https://github.com/ansible-collections/community.general/issues/1524#issuecomment-749945392). This updates your README to have the proper flag to still install from cask. 
Tested with Homebrew 2.7.7 on Catalina, new command works, old one does not.
-   [x] Documentation _(if necessary)_
=> chore: update homebrew install mechanism

src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
=> refactor: use send-all functionality only on single recipient transaction

scripts/generate-test-workflow.js, src/app/components/Input/InputCurrency.tsx, src/app/components/Input/InputRange.test.tsx, src/domains/transaction/components/InputFee/InputFee.tsx, src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx, src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
-   [x] Reduce multiple rerenders in input component
-   [x] Prevent from adding 0 when removing last digit from input component
=> fix: allow last digit removal in fee input

src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap, src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
Fixes overlapping issue in Plugin Manager
=> fix: increase z-index in `HeaderSearchBar`

src/domains/plugin/pages/PluginManager/PluginManager.tsx, src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
=> fix: make secondary navbar in `PluginManager` sticky

src/app/components/Dropdown/Dropdown.tsx, src/domains/transaction/components/FilterTransactions/__snapshots__/FilterTransactions.test.tsx.snap
https://app.clickup.com/t/ed0q0c
=> fix: do not render empty dropdown option group

src/app/hooks/use-profile-synchronizer.ts
-   [x] Cleanup code and move profile restoration checks and logic in `useProfileSyncStatus`
-   [x] Refine checks using `shouldRestore` to prevent duplicate restorations
-   [x] Fix reload issue in dev mode for passwordless profiles (white screen  or profile saving without restoring)
=> refactor: adjust profile restoration logic

src/app/components/Input/InputRange.tsx, src/app/hooks/use-currency-display.test.tsx, src/app/hooks/use-currency-display.ts
=> refactor: replace obsolete array of values in `InputRange` with single input value

.github/workflows/test.yml, scripts/generate-test-workflow.js, src/domains/splash/pages/Splash/Splash.test.tsx, src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
Covered src/domains/splash to 100%
Added more test cases for missed lines and branches. Changed test.yml and generate-test-workflow.js for src/domains/splash to 100
=> test: increase `src/domains/splash` coverage to 100%

package.json
The generated artifact contains John and Jane profiles since the `build:mac` relays on this script.
=> build: remove the E2E flag for production build

src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap, src/domains/setting/pages/Settings/available-settings/General.tsx
https://app.clickup.com/t/fd58ne
=> fix: adjust label color of transaction history setting
